angular/material

src/components/progressCircular/progressCircular.js, src/components/progressCircular/progressCircular.scss
Started looking to port progressCircular to angular2 and found that most of the code is unused and that the animation is now done by generating 101 sets of style rules (one for each value 0 to 100). The output of this CSS is ~2 kilobytes, and should probably be refactored to do the animation from javascript. For now I've removed the dead code and did some minor refactoring.
=> chore(progressCircular): remove dead code, minor refactor, add comments

config/karma.conf.js
This invalid value made the karma runner in WebStorm fail.
=> chore(karma): fix invalid logLevel config value

src/components/dialog/dialog.js
Return values for these methods were missing.
=> docs(dialog): add return values to `hide` and `cancel` methods.

src/components/virtualRepeat/virtualRepeater.js, src/components/virtualRepeat/virtualRepeater.spec.js
This is used by the calendar to start at a specific month instead of rendering a date far in the past and then jumping.
@kseamon
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/angular/material/3484)
=> feat(virtualRepeat): add md-start-index attribute.

docs/app/css/style.css, docs/app/partials/layout-alignment.tmpl.html, docs/app/partials/layout-options.tmpl.html, docs/config/template/ngdoc/api/componentGroup.template.html, docs/config/template/ngdoc/lib/macros.html
This is necessary in order to enable components that use a `<table>` element (e.g., date-picker).
=> fix(docs): style tables w/ css class instead of element.

src/components/datepicker/dateLocaleProvider.js
I'm well aware that this is a pretty hacky solution, but I haven't been able to think of something cleaner. 
It's also not something that I can see how to write a unit test for, since it depends on a specific timezone being set for the _operating system_.
All of this only comes into play when users use the default parsing/formatting instead of something like moment (like they're supposed to).
@ThomasBurleson @robertmesserle for review
=> fix(datepicker): handle DST incocnsistency encountered in some timezones. Fixes #4215

src/components/datepicker/calendar-theme.scss, src/components/datepicker/calendar.scss, src/components/datepicker/datePicker-theme.scss, src/components/datepicker/datePicker.scss, src/core/services/theming/theming.js
This change also tweaks a few visual properties based on UX team feedback.
BREAKING CHANGE: swap `background-hue-1` and `background-hue-2` (this is unlikely to affect the vast majority of people).
@rschmukler for review
=> fix(datepicker): make dark theme picker not terrible. Fixes #4614

src/components/datepicker/datePicker.js, src/components/datepicker/datePicker.spec.js, src/components/datepicker/demoBasicUsage/index.html, src/components/datepicker/demoBasicUsage/script.js, src/components/datepicker/demoBasicUsage/style.css
The `required` attribute was already support due to the magic of `ng-model`. This PR adds `mindate` and  `maxdate` $error fields for ngMessages.
I also reorganized the tests in the datepicker spec (new `describe` block for floating pane tests). Only the `'ngMessages suport'` tests are new.
@mhchen for review
=> feat(datepicker): support for ngMessages. Closes #4672.

src/components/datepicker/datePicker.js, src/components/datepicker/datePicker.spec.js
Problem was that error flags only got called on `$render`, which didn't occur because the ngModel isn't updated when the value is invalid.
@mhchen for review
=> fix(datepicker): apply ngMessages errors when using text input. Fixes #5353

src/components/dialog/dialog.js, src/components/dialog/dialog.spec.js
=> chore(dialog): re-add (deprecated) `content` method for alert() and confirm(). Fixes #5790

src/components/toast/toast.js
=> fix(toast): add missing a11y context. See #349

src/components/virtualRepeat/virtual-repeater.js, src/components/virtualRepeat/virtual-repeater.spec.js
=> fix(virtualRepeat): fix sizer not shrinking when items reduce in number.

src/components/virtualRepeat/demoDeferredLoading/style.css, src/components/virtualRepeat/demoInfiniteScroll/style.css, src/components/virtualRepeat/demoScrollTo/style.css, src/components/virtualRepeat/demoVerticalUsage/style.css
Apply padding to the container children that are not headers
Fixes #6421
=> docs(virtualRepeat): fix padding on vertical demos

src/components/panel/panel.js
@jelbourn @gmoothart @ErinCoughlan @DerekLouie 
Please review.
Position was being calculated base on panel size before it was being rendered.
=> update(panel): Update positioning to be calculated after the panel is rendered.

src/components/panel/panel.js, src/components/panel/panel.spec.js
Allows attachTo to accept an Element, JQLite object, or a query selector.
@jelbourn @gmoothart @KarenParker @DerekLouie Please review.
Fixes #7678
=> update(panel): Extends attachTo config accepted types.

src/components/panel/panel.js, src/components/panel/panel.spec.js
1. $mdPanel.open returns a promise that resolves to MdPanelRef. This lets the user chain on open.
2. Tests resolve promises before completing, removing the need for async tests.
@KarenParker @gmoothart @DerekLouie @ThomasBurleson @jelbourn  Please review.
=> fix(panel): Make all tests wait for promises to resolve.

src/components/panel/panel.js
Fixes centering and built-in animation transforms by combining them. 
@jelbourn @ThomasBurleson @KarenParker @gmoothart @DerekLouie Please Review.
Note: Does NOT fix custom animations overwriting the panel centering transforms. That nasty matrix math will come in a future PR.
=> feat(panel): Allows centering to be used with animation transforms.

src/components/panel/demoBasicUsage/panel.tmpl.html, src/components/panel/demoPanelAnimations/panel.tmpl.html
@KarenParker @gmoothart @DerekLouie Please review.
There is no action associated with the button, so the panel seems broken when it's clicked.
=> fix(panel): Remove useless button in dialog demos.

src/components/bottomSheet/demoBasicUsage/script.js
Currently the demo is broken, because `$templateResult` is not a known service.
This is obviously a typo. The correct name is `$templateRequest`.
=> docs($mdBottomSheet): fix demo code

src/components/icon/icon.spec.js, src/components/icon/js/iconDirective.js, src/components/icon/js/iconService.js
=> fix(icon): static svg urls are trustable

src/components/autocomplete/autocomplete.scss, src/components/autocomplete/js/autocompleteDirective.js, src/components/list/list.scss, src/components/navBar/navBar.js, src/components/navBar/navBar.scss, src/components/toast/toast.js, src/components/toast/toast.scss
With new support to disable the Layouts API globally, the md components now use flexbox css instead of the Layout API. This CSS can be easily overriden with future releases of the Layout Flexbox engine.
=> update(components): replace Layout attributes with flexbox css

src/core/util/prefixer.js, src/core/util/prefixer.spec.js
* The prefixer currently throws an error, when the jqLite element / native element is empty / undefined.
This was noticeable when having a `md-fab-actions` element without any child elements.
**FYI**: Checking the `nodeType` is more elegant, than comparing the prototype. It's the same way jQuery uses as well.
cc. @ErinCoughlan
=> fix(prefixer): do not throw an exception if element is undefined

src/components/panel/panel.js, src/components/panel/panel.spec.js
A JQLite reference of the Container/Wrapper and Panel elements have been added to the MdPanelRef object as public properties. It is now possible to use the standard `addClass`, `removeClass`, `toggleClass`, etc methods on those referenced elements.
Fixes #9109
=> feat(mdPanel): Wrapper and Panel elements referenced in the MdPanelRef

src/components/panel/panel.js
All references to `panelContainer` and `panelEl` have been verified as public, and the methods that contained the offending references have been corrected.
Fixes #9374 
Ping @ErinCoughlan
=> fix(panel): Element reference error

src/components/datepicker/js/datepickerDirective.js, src/components/datepicker/js/datepickerDirective.spec.js
Forwards the aria-label from the wrapper datepicker to the generated input.
FIxes #9340.
=> fix(datepicker): forward aria-label to generated input

src/components/virtualRepeat/virtual-repeater.js, src/components/virtualRepeat/virtual-repeater.spec.js
Fixes the virtual repeater not re-rendering, if the list is scrolled slightly and the user switches to a shorter array of items.
Fixes #9315.
=> fix(virtual-repeat): not re-rendering when switching to a smaller list

src/components/sidenav/sidenav.js, src/components/sidenav/sidenav.spec.js
* Adds the ability to select which element's scrolling will be disabled when a sidenav is open. This can be useful in the cases where the scrollable container isn't the direct parent of the sidenav.
* Adds unit tests for the parent scroll prevention.
Fixes #8634
=> feat(sidenav): configurable scroll prevent target

src/components/datepicker/calendar.scss, src/components/menuBar/menu-bar.scss, src/components/slider/slider.scss
* Reworks the `md-calendar-cell` mixin to allow for the height to be specified, avoiding the need for a duplicate property when overriding.
* Removes the `text-align: start` from the menu bar since, at least according to MDN, it's not supported by IE. Also the rtl mixin right before it does exactly the same.
* Reworks the rtl setup for the inverted slider so it doesn't result in duplicate properties.
=> fix(datepicker, menu, slider): remove duplicate properties

.github/CONTRIBUTING.md, docs/guides/COMMIT_LEVELS.md
* An typo for `enhancements` was fixed
* Fixed invalid links to the `docs/guides` directory.
* Fix wrong spelling of @robertmesserle's name
Closes #9328.
=> docs(contributing): fix invalid links and typo

src/components/datepicker/js/datepickerDirective.js, src/components/datepicker/js/datepickerDirective.spec.js
Forwards the datepicker's tabindex to the generated input element, instead of making the wrapper element focusable.
Fixes #8147.
=> fix(datepicker): forward tabindex to generated input

src/components/datepicker/js/calendarMonthBody.js, src/components/datepicker/js/calendarYearBody.js
Fixes the datepicker jumping forward if the current month is also the first one being rendered (e.g. when the min date is in the same month as the model). This was caused by an extra unnecessary call to `generateContent` which made the first month in the calendar to be re-rendered at the bottom after the user has scrolled past it. When the first month is at the bottom, the calendar tries to focus the active date, causing the browser to scroll to the bottom. Afterward the virtual repeater updates the view again, which makes the calendar skip a few months.
Fixes #9284.
=> fix(datepicker): jumping forward if min date is in the same month as model

src/components/datepicker/js/calendar.js, src/components/datepicker/js/calendar.spec.js
Fixes the datepicker's keyboard navigation not working if the user scrolls too much. This is due to the fact that after a month is destroyed, the browser automatically shifts focus to the body which prevents the calendar from picking up keyboard events. This change switches to listening for keyboard events on the body.
Fixes #9294.
=> fix(datepicker): keyboard navigation not working if the user scrolls too much

src/components/dialog/dialog.js, src/components/dialog/dialog.spec.js
* Properly remove the transition classes on the dialog element from the transition3d animator.
* Toggle the `fullscreen` class, instead of just adding it. Necessary for prerendered dialogs, because those could change from `fullscreen: true` to `fullscreen: false`
cc. @topherfangio @EladBezalel 
Fixes #9276.
=> fix(dialog): remove transition classes after hide

src/components/dialog/dialog.js, src/components/dialog/dialog.spec.js, test/angular-material-spec.js
By default the dialog searches for possible focus targets. Using the `md-autofocus` directive and querying for buttons inside of the `md-dialog-actions` element.
* Some developers don't have any actions inside of the dialog, so there will be no focus target and Screenreaders are not able to detect the new change.
The dialog should focus the actual dialog element when no focus target is available.
Users are still able to disable the auto focus (as same as before) by using the `focusOnOpen` option.
> `mockElementFocus` now mocks the HTMLElement prototype instead of the jqLite prototype.
> This allows us to test focus on native HTML elements as well.
Fixes #9271.
=> fix(dialog): focus dialog element when no actions are set

src/components/progressCircular/js/progressCircularDirective.js
* Fixes the indeterminate animation not working on certain iOS versions which pass in the `DOMHighResTimestamp` to `requestAnimationFrame`, but don't support `performance.now`.
* Adds fallbacks to the prefixed versions of `requestAnimationFrame`.
Fixes #9253.
=> fix(progressCircular): better support for older ios versions

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/autocompleteController.js, src/components/autocomplete/js/autocompleteDirective.js
Developers are currently not able to use ngBlur or ngFocus on the autocomplete, since the autocomplete is handling its focus from an underlaying input.
References #4492
=> feat(autocomplete): forward ngBlur and ngFocus attributes

src/components/tooltip/tooltip-theme.scss, src/components/tooltip/tooltip.scss
Use Material Design colors for tooltip
- Set tooltip opacity to 0.90
- Use background-700 for background color
- Use background-700-contrast for foreground color
Previously, the background color was set to a foreground-2 and the
foreground color was set to A100 of the background which causes
visibility issues when either changing the background palette from
grey or using a dark theme.
Fixes #9159
=> fix(tooltip) correct background and foreground color

docs/app/js/app.js, src/core/services/meta/meta.js, src/core/services/meta/meta.spec.js, src/core/services/theming/theming.js, src/core/services/theming/theming.spec.js
- provides an easy way to set and change the browser color according the material design spec colors and the defined themes
fixes #8062
=> feat(browser-color): enable browser header coloring

src/components/chips/chips.spec.js, src/components/chips/js/chipsController.js, src/components/chips/js/chipsDirective.js
* Allows developers to convert the remaining input text into a new chip on input blur.
This is useful for example, when having chips for email addresses.
Closes #3364.
=> feat(chips): md-add-on-blur functionality

gulp/tasks/watch-demo.js, gulp/tasks/watch.js
When developing locally, either with `gulp watch-demo` or `gulp watch`, Gulp unnecessarily watches and runs a build when the unit tests change.
=> chore(gulp): disable watch for spec files

src/components/autocomplete/js/autocompleteDirective.js, src/components/subheader/subheader.js, src/components/virtualRepeat/virtual-repeater.js
Dgeni shows a warning when it cannot find the correct link files. Since we are using an Angular app, the only way I have found around it is to use the `ng-href` attribute so Dgeni ignores them.
Ping @ThomasBurleson for review.
=> fix(docs): Fix dangling links.

src/components/datepicker/js/calendar.js, src/components/datepicker/js/calendar.spec.js, src/components/datepicker/js/calendarMonth.js, src/components/datepicker/js/calendarMonthBody.js, src/components/datepicker/js/calendarYear.js, src/components/datepicker/js/calendarYearBody.js, src/components/datepicker/js/dateLocaleProvider.js
* Allows for the datepicker's first and last renderable dates to be configured via the $mdDateLocaleProvider. This lets developers specify when the calendar begins and ends.
* Makes the month and year views consistent by having the same start and end dates. Previously the month view started from 1933, whereas the year view started from 1816.
* Simplifies the logic for determining the start and end dates.
* Fixes not being able to use the keyboard to navigate to the first item in the year view, if a minimum date is specified.
Fixes #9269.
=> feat(datepicker): configurable start/end dates, consistency improvements

src/components/datepicker/calendar.scss
Fixes the arrow on the month header pointing in the wrong direction on RTL.
Referencing #9214.
=> fix(datepicker): arrow direction in rtl

src/components/select/select.js
Some users expressed confusion about the fact that the `value` attribute always evaluates to a string as opposed to the `ng-value` attribute which allows any value.
Add a note to the docs to describe the differences and give an example of how to properly use `ng-if` with the `value` attribute.
Fixes #9373.
=> docs(select): Add note about value/ng-value differences.

src/core/services/theming/theming.js, src/core/services/theming/theming.spec.js
*  insure we clone properly the a configuration map object.
*  implement unit test to verify.
=> fix(theming): fix read-only $mdThemingProvider.configuration()

gulp/util.js
PR #8850 made this change, but it seems unintentional because the symbol `cleanCSS` doesn't exist anywhere.
=> fix: undo change to unknown symbol for prod build

src/components/panel/panel.js, src/components/panel/panel.spec.js
The user is now able to provide an ID as a property of the panel configuration object. When an ID is provided, the created panel is added to a tracked panels object. Any subsequent requests made to create a panel with that ID are ignored. This is useful in having the panel service not open multiple panels from the same user interaction when there is no backdrop and events are propagated.
Fixes #9356
Also, several syntax issues throughout the documentation/commenting have been corrected.
Fixes #9357
Ping ErinCoughlan
=> feat(panel): Configuration ID for tracking

src/components/select/demoBasicUsage/index.html, src/components/select/select.js, src/components/select/select.scss, src/components/select/select.spec.js
After a recent change to the asterisk colors, the `md-no-asterisk` option was no longer working.
- Update code to add a new `.md-no-asterisk` CSS class and fix styles.
- Add appropriate tests.
- Add `md-no-asterisk="false"` to demo so users can easily turn it on
and test the fixed functionality.
Fixes #9339.
=> fix(select): Ensure `md-no-asterisk` attribute works.

gulp/util.js
* After an update to the new `gulp-filter` major version (without any changelog) 
it seems that `gulp-filter` can no longer match files (which aren't at the root level)
This new behavior makes completely sense, and the old one was not valid.
> Previous Version: `*.css` matches `src/core/core.css | src/core/core-default-theme.css`
> New Version: `*.css` matches no files, because at the project root are no CSS files.
* Now using multi level globs to match the core module files properly, because those are not at the root level (but `src/core/`).
=> fix(build): properly filter core module files with updated gulp-filter

src/components/dialog/dialog.js
Adds classes to help identify the confirmation and close buttons in a dialog. This helps with writing tests that involve the dialog, because it doesn't depend on DOM order.
CC @ErinCoughlan
=> fix(dialog): add extra classes to identify buttons

src/components/tabs/js/tabsDummyWrapperDirective.js
Check if MutationObserver is in window. If not fall back to DOMSubtreeModified event.
Closes: [9395](https://github.com/angular/material/issues/9395)
=> fix(tabs): ie10 MutationObserver issue

src/components/autocomplete/demoInsideDialog/dialog.tmpl.html, src/core/services/layout/layout.js
The autocomplete demo with the dialog currently logs a warning for the `ng-cloak` being present on the dialog template.
Removing `ng-cloak` removes that warning and also fixes the warning in the console.
=> fix(autocomplete): properly run animation for dialog in demo.

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/demoInsideDialog/dialog.tmpl.html, src/components/autocomplete/js/autocompleteController.js
* The autocomplete opens the dropdown when the `md-autofocus` attribute is specified.
* The documentation is not mentioning anything about it (it probably was), but anyways this is interfering with the normal functionality of the `md-autofocus`  attribute, because it is used, to mark an element to be focused upon opening. (e.g `$mdSidenav`, `$mdBottomSheet`, `$mdDialog`)
* This also fixes an issue where the autocomplete dropdown shows up twice, when having the 
autocomplete inside of a dialog.
This change now provides consistency for the `md-autofocus` attribute on the autocomplete as well.
@ThomasBurleson This **can** be marked as a breaking change, but the functionality was not documented for long time.. so not sure.
=> fix(autocomplete): remove autofocus ambiguity.

src/components/card/card.scss
Use flexbox for img elements when child of md-card-title-media
Fixes #9355
=> fix(card): limit img size when using md-card-title-media

src/components/input/input-animations.spec.js, src/components/input/input.js
After some recent changes to the input animations, the input could get into a state where animated messages were still being shown even if they were invalid.
The underlying issue was that the animation was not calling the `done` function and Angular's animation framework was thus not actually removing the element from the DOM, so any further message animations found the old message in the DOM and attempted to show it.
- Ensure all input animations properly call the `.done()` method
which is returned by `$animateCss()`.
- Update tests to check for `.done()` calls and use a better
method for flushing the animations.
- Remove some old/commented code.
Fixes #9454.
=> fix(input): Ensure animated messages disappear.

src/components/datepicker/js/datepickerDirective.js, src/components/datepicker/js/datepickerDirective.spec.js
Adds the ability to specify the datepicker's timezone via the `ng-model-options` attribute, e.g. for UTC, the element would look like this:
```
<md-datepicker ng-model="date" ng-model-options="{ timezone: 'utc' }"></md-datepicker>
```
This works by re-using the logic from Angular's `input[type="date"]` directive.
Fixes #8448.
Fixes #8936.
=> feat(datepicker): add timezone support

src/components/datepicker/datePicker-theme.scss, src/components/datepicker/datePicker.scss, src/components/datepicker/js/datepickerDirective.js, src/components/datepicker/js/datepickerDirective.spec.js
The current approach for positioning the datepicker's calendar works by expanding the input container in order to fill a gap in the floating calendar pane and using negative margins to prevent the UI from jumping around. This comes with some drawbacks:
* It causes the input element to shift down slightly when the calendar gets opened.
* It can shift all of the elements surrounding the datepicker, despite the negative margins.
* It makes it hard to refactor the positioning.
This new approach solves all of the above-mentioned issues by using an element with a box-shadow to create the overlay, avoiding the need for expanding the container.
Referencing #9342.
=> fix(datepicker): improved overlay positioning

src/components/tabs/demoDynamicHeight/readme.html, src/components/tabs/js/tabsDirective.js
Some users are unaware of the new `<md-nav-bar>` component which can provide a better option for page-level navigation.
- Update tabs demo and docs to include a note about, and link to,
the `<md-nav-bar>` component demo & docs.
- Update some tab docs with proper line wrapping to follow our
standards.
Fixes #6676
=> docs(navbar): Add mdNavBar note to tab docs.

src/core/services/compiler/compiler.js
Currently the `controllerAs` logic in the compiler is done manually, however the same result can be achieved by passing the `controllerAs` value to the `$controller` factory.
=> fix(compiler): remove manual controllerAs logic

gulp/util.js
Now minifies the theme css for the Angular constant.
As discussed:
>- Now minifying the SCSS for the $MD_THEME_CSS constant. (new)
> - Not minifying the SCSS, when exporting a release build for bower-material. (currently)
R: @EladBezalel 
Fixes #9066.
=> chore(build): minify theme template for ng constant

src/components/menuBar/js/menuBarController.js, src/components/menuBar/menu-bar.scss, src/components/menuBar/menu-bar.spec.js
fix(menu-bar): unable to close menu when clicking on toolbar
* Fixes not being able to close a toolbar menu by clicking on the wrapping toolbar. Works by adding an extra click handler on the toolbar that closes the menu. Note that the same effect could be achieved by removing the `z-index` altogether, but that could break the functionality that allows users to jump from one menu to the next without clicking.
* Moves the menu bar's z-index to CSS so it's easier to manage.
* Adds call to `disableOpenOnHover` when the scope is destroyed, in order to clean up leftover event handlers.
Fixes #8965.
Cheers to @topherfangio for catching a potentially breaking error.
=> fix(menu-bar): unable to close menu when clicking on toolbar

src/core/services/theming/theming.js, src/core/services/theming/theming.spec.js
- Added `defineTheme` functionality to `$mdTheming` service
- Added support for promise and a function that returns a promise on `md-theme` directive to support async build of themes
fixes #2965
=> feat(themes): register theme on the fly

docs/app/partials/layout-children.tmpl.html, docs/app/partials/layout-tips.tmpl.html, src/core/style/layout.scss
A recent change which was supposed to fix an IE11 bug accidentally altered the `flex-basis` for the flex children of all `.layout-column` flex containers in all browsers.
Unfortunately, there is no IE11-specific fix.
- Revert the original change.
- Update the Layout Troubleshooting page with a new demo.
- Update the Layout Children docs to mention the new demo.
- Remove old Chrome-specific demo which was incidentally fixed
by reverting this change.
Reverts ce0ebbf.
Fixes #9354.
=> fix(layout): Revert overzealous IE11 flexbox fix.

src/components/dialog/dialog.js, src/components/dialog/dialog.spec.js
I recently noticed while playing with the pre-rendered dialog around, that despite of the pre-rendered dialog, the interim element triggers a compilation in the `$mdCompiler`.
It doesn't introduce any bugs, but it's unnecessary and could damage the performance.
Also moves the content element stuff into its own function, which makes the source more clean and allows us to maintain it easily.
Plays nicely together with #9299.
cc. @EladBezalel @topherfangio
=> fix(dialog): do not compile an empty element when using a content element

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/highlightController.js, src/components/autocomplete/js/highlightDirective.js
* The highlight controller no longer sanitizes the term or content, because this would require complex libraries like `ngSanitize`
* Also there is no need to sanitize those strings, because after this change we never insert them as HTML nodes anymore.
* We decompose the content string into different tokens and then compose them together into different elements.
This allows us to be 100% sure that we only insert trusted HTML code and no unsafe HTML code, which could include XSS attacks.
* This approach also supports now HTML identifiers and special text characters in the highlight text and content.
Fixes #8356
=> fix(autocomplete): properly parse unsafe strings to prevent advanced XSS attacks

src/components/tabs/js/tabsController.js
Fixes md-tabs scroll blocking happening when single tab is larger than containing canvas (e.g. tabs containing long text elements).
=> fix(tabs): scroll blocks in pagination (related to #5439)

src/components/input/input.js, src/components/input/input.scss
* Fixes the textarea's resize handle being in the wrong position if the `md-input-container` is taller than the textarea.
* Moves the icon placement logic to the compile function, in order to be called less and to run before any other DOM manipulation logic.
* Removes some unnecessary SASS nesting.
Fixes #9151.
=> fix(textarea): resize handle position occasionally wrong

src/components/checkbox/checkbox.js, src/components/checkbox/checkbox.spec.js
Fixes the checkbox not getting marked as checked on the first load when using `ng-checked`.
Fixes #9349
=> fix(checkbox): not being marked as checked with ng-checked on load

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/autocompleteController.js, src/components/chips/js/chipsController.js
Currently the `md-autocomplete` shows its dropdown only by changing the `searchText` from `null` to an empty string.
> This triggered a searchText change, which resulted in triggering a query.
This approach doesn't seem to be very elegant.
> The autocomplete should manually trigger a query and possibly open the dropdown if matches are available.
--
@topherfangio Can you take a look (especially on the chips with autocomplete behavior)
@ThomasBurleson I consider this as too risky for 1.1.0 (specifically the behavior with the chips)
Fixes #9283. Closes #9288. Closes #9289.
=> fix(autocomplete): properly show dropdown on focus when minlength is met

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/autocompleteController.js
* Currently the `md-require-match` attribute checks whether an item is selected or not. The validity shouldn't be set to false, if the searchText is empty.
Closes #9072.
**Breaking Change**: The autocomplete validator `md-require-match` no longer matches if the search text is empty
=> update(autocomplete): md-require-match only turn invalid if search text is provided

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/autocompleteDirective.js
* A lot of developers requested a way to pass the `ng-trim` attribute to the underlaying input element.
This is reasonable, because ngTrim always trims the searchText and can cause deviations with the search results.
* Also added a more generic way of forwarding the the (currently) three attributes to the input element, without doing this in the template.
Fixes #4492
=> feat(autocomplete): support ng-trim on the underlaying input

gulp/util.js, src/core/services/theming/theming.js
* The theming service currently only matches from the beginning of the `md-default-theme`, but all preceding selectors without whitespaces are being ignored.
* The regex is doing more than it actually needs. Having an extra group for the target is unnecessary   (Since we only want to concatenate the start and the end without the `.md-default-theme` class).
* Kristiyan also helped with this effort and we figured out, that NanoCSS accidentally removes the theme color expressions from the `border` CSS property.
Shout-out again to @crisbeto 
Fixes #9480
=> fix(theming): match preceding selectors as well

docs/config/template/index.template.html
* Normally modern webapp do not allow the developer to zoom into the page on mobile.
This applies the most common meta tag to the docs page and makes the demos look way better on mobile.
* Components, which have a text input (like datepicker, autocomplete or normal input) no longer zoom in, when clicking on them.
I had a quick chat with @topherfangio about it, and we were not 100% sure, why we didn't apply that meta tag before.
=> docs(): viewport should be not scalable

docs/config/template/ngdoc/lib/properties.template.html, src/core/services/theming/theming.js
After this will be merged i will update #9475 to add docs there as well
=> docs(theming): added documentation to $mdTheming service

src/components/autocomplete/autocomplete.scss, src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/autocompleteController.js, src/components/autocomplete/js/autocompleteDirective.js
* Adds an attribute, which allows developer to overwrite the amount of items shown in the autocomplete dropdown.
- When the dropdown doesn't fit into the possible space it will shrink accordingly (as same as before)
- When the specified amount of items is higher than the current matches then it will shrink (as same as before)
* Fixes the item height deviations between CSS and JavaScript.
* Removed the unnecessary CSS for the dropdown height, because everything will be handled from the JS (same as before)
* Added tests for the dropdown height calculation, which make sure that everything is now calculated properly.
> I really like how the items are now showing up. No cutted items anymore :tada:  
Fixes #9306. Closes #8751.
=> feat(autocomplete): allow developers to specify amount of dropdown items

src/core/style/variables.scss
The `rem` SCSS function currently uses a hard-coded font size variable, which makes it impossible for developers to overwrite the global font-size.
> The rem function should be moved behind the initialization of the global `$font-size` variable, and should use this one.
Fixes #9486.
=> fix(variables): rem function should use global $font-size variable

src/core/util/util.js, src/core/util/util.spec.js
Fixes the `$mdUtil.getClosest` method not working properly when looking for elements with a lowercase `nodeName` (e.g. SVG).
Fixes #9509.
=> fix(util): getClosest not working on elements with lowercase nodeName

src/components/datepicker/datePicker.scss
Fixes the datepicker error messages not being aligned with other `md-input-container` instances. The issue was caused by an unnecessary float on the input element and the calendar icon pushing down the messages. The fix removes the float and pulls the icon up with a margin while pushing it down via `top`.
Fixes #9342.
**Before:**
**After:**
BREAKING CHANGE: 
CSS `md-date-picker`: Prevents the button from wrapping around, as well as it pushing down the error messages more than they should be.
```css
.md-datepicker-button { 
top : $button-left-right-padding * 2 - $md-datepicker-border-bottom-gap / 2;
}
.md-input {
float: none;
}
```
=> fix(datepicker): error message alignment in md-input-container

src/components/autocomplete/js/autocompleteController.js, src/components/dialog/dialog.js, src/components/input/input.js, src/core/util/util.js, src/core/util/util.spec.js
* Properly determines the viewport top offset, without any consistency issues for the `scrollTop`.
* The `scrollTop` method had a wrong name when passing an element, because it resolved the client rects in relative to the viewport.
* Now it determines the viewport top offset from the window (instead of using the body element - this is deprecated)
* Also makes sure that the calculations in the source are not too long (extra variables)
**FYI**: Mostly some cleanup in the `disableBodyScroll` function.
Fixes #9370.
=> fix(util): properly determine viewport top offset

src/components/tooltip/tooltip.js, src/components/tooltip/tooltip.spec.js
Until now, each tooltip used to register 3 events on the window (scroll, resize and blur), even if it isn't being displayed. These can really add up on a page with a lot of tooltips. This change introduces a service that keeps track of the event handlers and only registers 1 global handler on the window for each event.
Referencing #9506.
=> perf(tooltip): reduce amount of event listeners on the window

src/components/sidenav/sidenav.js, src/components/sidenav/sidenav.spec.js
Triggers a resize event whenever a sidenav is opened. This allows components like virtualRepeat and textarea to resize properly.
Fixes #7309.
@topherfangio you and @DevVersion had a discussion on the issue about having a more generic solution to this. What do you think about having the changes from here until that happens?
=> fix(sidenav): notify child components when the element is opened

src/core/services/compiler/compiler.js, src/core/services/compiler/compiler.spec.js
* Pass the `$element` local to the instantiated controller, as same as a normal Angular 1.x DDO.
Closes #9507.
=> feat(compiler): pass $element to controller instantiation

src/components/chips/js/chipsController.js, src/components/navBar/navBar.js, src/components/sticky/sticky.spec.js, src/components/tooltip/tooltip.js, src/core/services/layout/layout.spec.js, src/core/services/theming/theming.spec.js
The chips, navbar and tooltip had a few cases where they look up all the elements of a certain class or node name, but they only use the first one. This change switches to using `querySelector` which will stop looking after the first match.
=> perf(chips,navbar,tooltip): avoid extra DOM lookups

src/components/chips/chips.spec.js, src/components/chips/js/chipsController.js
* An error will be thrown if the chips component is used in combination with an autocomplete.
It did not make the chips unuseable, the chips just didn't return the focus to the input element.
Fixes #9520.
=> fix(chips): no longer throw an error when returning focus to input.

src/components/panel/panel.spec.js
When running the panel tests separately from all the others, the one about disabling scrolling was failing. This wasn't happening when running it together with all the other components, because some other component (not sure exactly which one, but it seemed like either dialog or autocomplete) wasn't cleaning up the DOM properly and was leaving a scroll mask lying around.
This change removes the DOM lookup for the scroll mask, because it looks like it got disabled in PR #8901, however the test didn't get updated.
@bradrich can you confirm that this is desired behaviour?
=> chore(panel): fix failing unit test

src/components/autocomplete/autocomplete.spec.js, src/components/panel/panel.spec.js
* The scroll mask was not removed by two specs of the autocomplete and could cause unexpected issues in other suites, when setting focus on those.
=> fix(autocomplete): two specs leak the scroll mask element

src/components/menuBar/menu-bar.spec.js
Fixes one of the menuBar specs which wasn't flushing out the interim element, which caused it to leak scroll mask elements.
=> fix(menuBar): test leaking scroll mask element

src/components/panel/panel.js
70c146f:
* Use constant-width formatting for the position guides:
(compare with https://material.angularjs.org/latest/api/type/MdPanelPosition#addPanelPosition)
f8c0b31:
* Fix the smart quotes around `use strict`.
* Remove unused `toppings` variable/parameter.
* Avoid escaping problem (`&amp;`) by slightly changing syntax.
Note: this file is checked in to github with CRLF line endings. I did not fix that.
=> docs(mdPanel): fix formatting

.gitmodules
Removes the old Git submodule for Material Icons, which is not used anywhere.
=> chore(): remove old git submodule

src/components/fabSpeedDial/fabSpeedDial.js, src/components/fabToolbar/fabToolbar.js, src/components/tooltip/tooltip.js
Current jsDocs show examples using `icon="xxx.svg` instead of `md-svg-src="xxx.svg"`.
=> docs(toolbar): update (fabToolbar, fabToolbar & tooltip) docs

src/components/panel/panel.js, src/components/panel/panel.spec.js
* Allows for a function to be passed to the `withOffsetX` and `withOffsetY` methods which will help when trying to determine the offset dynamically.
* Switches to assigning the offset before the position, in order to avoid tiny jumps in the UI on slower browsers.
Fixes #9608.
=> feat(panel): allow passing in a function to the offset methods

src/components/switch/switch.scss
* The switch does not properly display in RTL mode - this is due to the recent changes to the RTL mixin, which introduced a reset value.
* Inside of the switch the container should have a 0px reset value
| Before | After |
| ------ | ------ |
|
=> fix(switch): invalid container margin in RTL

src/components/panel/panel.js, src/components/panel/panel.spec.js
* Adds an API that can be used for registering interceptors on the panel.
* Adds support for an `onClose` interceptor that allows the user to prevent a panel from closing.
Fixes #9557.
=> feat(panel): add interceptors API and onClose hook

src/components/dialog/dialog.js, src/components/dialog/dialog.spec.js, src/core/services/compiler/compiler.js, src/core/services/compiler/compiler.spec.js, src/core/services/interimElement/interimElement.js
- This moves the `contentElement` logic from the `$mdDialog` (as introduced in https://github.com/angular/material/commit/135cb3a290bee19a1395fc3a7440599c5ff5aef5) to the `$mdCompiler`.
This allows the `$mdPanel` to take advantage of this functionality and does not block the port of the dialog to the `$mdPanel`
**FYI**: Don't be too nitpicky about the docs, those were mostly not written by me (rather fix those in a new PR)
Base for #9366
=> feat(compiler): support for content elements

src/core/util/util.js, src/core/util/util.spec.js
* When the scroll mask is disabled per the new options which were recently added, the specified element will be used as scroll mask (under the hood)
If restoring scroll, the scroll mask will be removed from the DOM (even the disabled one) - This is invalid.
This causes an issue when restoring the scroll, while the element is still showing up (e.g dialog with z-index)
@ThomasBurleson Also I need to correct my self, the issue within the `$mdPanel` is not reproducable (**but present**), because the element will be anyways detached by the panel.
Part of #9256
=> fix(util): disableScrollAround should not remove disabled scroll mask

src/components/sidenav/sidenav.js, src/components/sidenav/sidenav.spec.js
Fixes the sidenav not evaluating expressions inside of the `md-component-id` attribute.
Fixes #9052.
=> fix(sidenav): allow for data bindings in md-component-id

src/components/menu/js/menuController.js, src/components/menu/js/menuServiceProvider.js, src/components/menu/menu.spec.js
Iterate through menu items until it finds a non disabled item
Previously, menu would attempt to focus first item. If the item
was disabled, no attempts were made to seek another focusable item.
Fixes #9165
=> fix(menu): focus first non disabled item

src/components/dialog/dialog.spec.js, src/components/menu/js/menuServiceProvider.js, src/core/services/interimElement/interimElement.js, src/core/services/interimElement/interimElement.spec.js
* Adds support for multiple interim elements (like dialog)
* When single interim (default) is enabled, then interims should hide properly (as in toasts).
---
When opening interim elements, by rapidly clicking on the open button as an example, the toasts / interims will overlap. But those shouldn't overlap. This is against the specs.
> See https://material.angularjs.org/HEAD/demo/toast
@ThomasBurleson Nothing really changed for the components. It just fixed the issue with overlapping and opens the door of having multiple interims (this was just included into that fix)
Fixes #8624. References #9166 References #8630.
=> feat(interimElement): properly handle multiple interims.

docs/content/CSS/typography.md, src/core/style/layout.scss
Fix use of `flex-basis` when setting the max-width or max-height values.
This allows `flex-offset` to work flex items correctly stretched.
Fixes #5345.
=> fix(layout): fix use of flex-basis in layout modes

src/components/colors/colors.spec.js
The unit tests for the `md-colors` directive were causing a leak since they were being compiled and added to the DOM, but were never being removed.
=> chore(colors): fix leaking elements during unit tests

src/core/services/interimElement/interimElement.js, src/core/services/interimElement/interimElement.spec.js
* SHA 421fed4 introduced multiple interim elements support (internal right now)
* If multiple interim elements are showing up, the last one can't be closed in some situations (because we accidentally splice it too early)
Not considered as a breakingbug for now, because the `multiple` option is not public yet
=> fix(interim): do not immediately splice interim.

src/core/util/autofocus.js, src/core/util/autofocus.spec.js
The autofocus directive currently supports an empty attribute value because `jqLite` toggles the class if the `force` param is `undefined`.
> This means if you change it several times to the same `undefined` value it does incorrectly update the autofocus class (See associated test)
Also the autofocus directive does now determine the class immediately and does not require a second digest to run (The previous delay could cause issues with the $mdCompiler element linking).
References #9273.
@ThomasBurleson: This is a preparation fix to address the aforementioned issue with the $mdPanel and just to make the autofocus directive _faster_.
=> fix(autofocus) properly parse attribute expression

src/components/virtualRepeat/virtual-repeater.js, src/components/virtualRepeat/virtual-repeater.spec.js, src/core/util/constant.js
* The virtual repeat tests right now create two times more than 1.5 Million items at same time (2 million and 1.6 million).
* This is extremely filling the available memory (especially on Saucelabs) and potentionally slows / crashes the test suite.
**FYI**: The tests are still testing the same, just overwriting the max pixels per element constant, to be able to use a smaller amount of items (but using the same logic)
References #9560
=> test(virtual-repeat) reduce memory consumption significant

src/components/autocomplete/autocomplete.spec.js, src/core/core.js, src/core/core.spec.js
* Fixes a test in the autocomplete that was failing, because it wasn't triggering a digest.
* Adds a shim for `$q.resolve`, which was first introduced in Angular 1.4.1, in order to prevent similar errors in the future.
=> fix(build): fix errors on angular 1.3

src/components/panel/panel.js, src/components/panel/panel.spec.js
The panel element wasn't being removed when it's scope is destroyed (e.g. when navigating to a different page).
Fixes #8683.
=> fix(panel): element not being removed when scope is destroyed

src/components/datepicker/js/datepickerDirective.js, src/components/datepicker/js/datepickerDirective.spec.js
Fixes the datepicker not supporting certain events inside `ngModelOptions.updateOn`. These are usually events that don't bubble (e.g. `blur`) and should be bound to the input, however since the `ng-model-options` are on the root element, Angular binds it's handlers to it.
Fixes #9577.
=> fix(datepicker): updateOn not working with non-bubbling events

src/components/panel/panel.spec.js
Fixes the panel interceptor tests failing on the Angular 1.5.9 snashot due to "Possibly unhandled exceptions".
The `callInterceptors` function was removed, because it was flushing the panel, preventing tests from being able to handle rejected promises. This could've been handled within the function itself, however that could cause confusion down the road, when the changes from snapshot get released.
=> chore(panel): fix failing tests in snapshot

src/components/dialog/dialog.js
* Mention briefly that content elements will be not linked to any scope / or will not instantiate any controller.
Closes #9571.
=> docs(dialog): content elements will be not linked

docs/app/css/style.css, docs/app/js/anchor.js, docs/app/js/app.js, docs/gulpfile.js
* Very often I want to link a user to a specific topic in the docs, but it is just not possible, and they needed to search for the topic I meant manually
* Having a directive, which automatically creates anchors for all title elements does make this SUPER easy, and we can just send the user a easy (accessible) link.
> Note that the GitHub Readme works kind of the same.
Example links:
- http://localhost:8080/api/directive/mdListItem#secondary-items
- http://localhost:8080/api/directive/mdListItem#proxy-item
- http://localhost:8080/api/directive/mdAutocomplete#validation
- http://localhost:8080/#training-videos
@ThomasBurleson I would like to have a quick discussion about it, before we start reviewing this.
=> docs(): title elements will be auto anchored.

src/components/chips/chips.spec.js, src/components/chips/contact-chips.spec.js, src/components/datepicker/js/datepickerDirective.spec.js, src/components/select/select.spec.js
Fixes unit tests in the chips, contact chips, datepicker and select components that were leaking elements in older Angular version. This was causing other tests to fail.
=> chore(chips, datepicker, select): clean up test leaks in angular < 1.5

src/components/panel/demoPanelAnimations/index.html, src/components/panel/demoPanelAnimations/script.js, src/components/panel/panel.js, src/components/panel/panel.spec.js, src/core/util/animation/animate.js
* Adds the ability to specify the duration of an animation the panel.
* Fixes the `MdPanelAnimation` not showing up in the docs.
Fixes #9177.
=> feat(panel): configurable animation duration

src/components/panel/demoBasicUsage/index.html, src/components/panel/demoGroups/index.html, src/components/panel/demoGroups/script.js, src/components/panel/demoGroups/style.global.css, src/components/panel/panel.js, src/components/panel/panel.spec.js
Panels are now capable of being grouped together by any designation the user sees fit. Grouping allows the user to specify logic for a collection of panels. For instance, all popups in the header can be considered one group with a maximum of one popup open at a time. Dialogs within dialogs are another example of groups. This implementation prevents the panel from storing a ridiculous amount of data in memory or polluting the DOM with several panels. This helps performance and gives the user more flexibility about how to use panels.
Fixes #8971
Ping @ErinCoughlan
=> feat(panel): Panel grouping

src/components/panel/panel.js, src/components/panel/panel.spec.js
Accounts for the computed offsets of the panel element when determining whether it is on screen.
Fixes #9628.
=> fix(panel): take offsets into account when checking if element is on screen

src/components/datepicker/js/datepickerDirective.js, src/components/select/select.js, src/core/util/util.js, src/core/util/util.spec.js
* AngularJS recently made a breaking API change which is is currently in Snapshot (https://github.com/angular/angular.js/commit/87a2ff76af5d0a9268d8eb84db5755077d27c84c)
* This commit introduces a cross-version compatibility method to support the older and newer API.
=> fix(ngModelCtrl) compatibility with snapshot breaking changes

src/core/util/util.js
The previous behavior assumes the existence of the now() function in browsers that provide the 
window.performance API. This change verifies it is available and if not, uses existing fallbacks.
According to the [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/API/Performance#Browser_compatibility) reference page, the following browsers have the `window.performance` API, but not support for `now()`:
* Chrome 6-23
* Firefox 7-14
* IE 9
=> fix(util): check for definition of window.performance.now before using in mdUtil

docs/app/js/anchor.js
* Currently anchors will be always created, regardless of being inside of a toolbar or inside of a sidenav.
* The anchors should be only created inside of a `md-content` element.
**FYI**: We need to _manually_ compile the template, because we don't want to compile the directive, when being outside of a `md-content`.
=> ﻿docs(anchor): only create anchors inside of md-content.

docs/app/css/style.css, docs/app/img/icons/ic_arrow_up_24px.svg, docs/app/js/app.js, docs/config/template/index.template.html, src/core/util/util.js
* Adds a Jump to Top Fab button at the right bottom of the docs page.
* The FAB button automatically shows when the content is scrolling (this runs outside of Angular to not trigger a digest per each scroll event)
Small Preview video (lags)
>  https://i.gyazo.com/8d0c14c6637ed277bd573272e26bcbf4.mp4
=> docs(): add jump to top fab button

src/components/icon/demoLoadSvgIconsFromUrl/index.html, src/components/icon/demoLoadSvgIconsFromUrl/script.js
* The icon demo with the SVG files from URLs was not working for the codepen checkout, because it seems like the "inlined" SVG has some escaping issues (especially when being wrapped inside of single qoutes inside of HTML).
* Moving the SVG template into the Script (as same as for the decoded SVG) does fix the issue, and is also makes the demo look better.
Fixes #9561.
=> fix(icon): codepen demo issue

src/components/virtualRepeat/virtual-repeater.js
* Add information about a common issue where developers were expecting the VirtualRepeat to detect changes outside of another scope. (#9711)
* Added entry to common issues where developers were confused, whether the directives will be compiled / linked multiple times or not (#8638)
Closes #8638. References #9711
=> ﻿docs(virtual-repeat): extend common issues section

docs/app/css/layout-demo.css, docs/app/css/style.css, docs/gulpfile.js, gulp/util.js, scripts/gulp-utils.js
* Uses the shared autoprefixer from the gulp utils to autoprefix the docs CSS (instead of always doing it manually as in #9786)
> Kept a few special properties like (`-webkit-font-smoothing` because those can't be autoprefixed)
Closes #9785
=> chore(docs): autoprefix docs stylesheet

docs/app/css/style.css
* In 8b4d2f98f5112ba0b83109af00dbbed3f93f7a5f the overflow property has been accidentally removed.
=> fix(docs): re-add accidentally removed css

docs/app/js/app.js, src/components/dialog/dialog.js, src/components/dialog/dialog.spec.js, src/components/panel/panel.spec.js, src/core/services/interimElement/interimElement.js
* Fixes the docs site not working against the latest snapshot.
* Fixes the `dialog` throwing an error about `ngSanitize` not being present and then compiling the contents anyway.
* Makes the `interimElement` compatible both with the latest changes to promises from Angular PR #15213 and the current promise handling in Angular <= 1.5.
* Reintroduces the panel changes from #9688 which were overwritten accidentally.
* Fixes an error that was being swallowed during unit tests, but was still showing up in the `$exceptionHandler`.
=> fix(docs, dialog, interim, panel): compatibility with latest angular snapshot

src/components/menuBar/js/menuBarController.js, src/components/menuBar/menu-bar.spec.js
Fixes nested menus not getting closed properly when the user clicks on the toolbar.
Fixes #9599.
=> fix(menu-bar): nested menus not closing when clicking on the toolbar

src/components/panel/panel.js
Fixes a JS error in the panel, if the user's browser uses the prefixed `transform` property.
=> fix(panel): use prefixed transform property

src/components/select/select.js, src/core/util/util.js, src/core/util/util.spec.js
Occasionally, `ng-repeat` appears to modify the DOM in such a way that it allows duplicates of selected items. When this happens, the `md-select` has issues displaying the proper label.
Add a quick filter to ensure there are no duplicate selections in our labels.
NOTE: I was unable to reproduce this in a spec; it appears to be related to the scope digests and never happens in the spec. I did update one of the demos to do some manual testing and ensure this fix works as expected, but it didn't have any real use inside of the demo so I removed it before submission.
Fixes #9442.
=> fix(select): Fix duplicates in label.

src/components/sidenav/sidenav.js, src/components/sidenav/sidenav.spec.js, src/core/core.js, src/core/services/interaction/interaction.js, src/core/services/interaction/interaction.spec.js
This is a re-submit / rework of my old PR (#5589), should start from clean again. 
Sample use-case:
- Sidenav want's to restore focus after the pane gets closed, this should only happen for keyboard interactions.
Fixes #5563 Fixes #5434 Closes #5583
=> feat(interaction): added service to detect last interaction

src/core/services/interimElement/interimElement.js, src/core/services/interimElement/interimElement.spec.js
* Dialogs, Bottom-Sheets and Toasts have presets, which all depend on the `build` preset automatically.
* Due to the new `muliple` property in the `$$interimElement` factory, developers can explicitly pass the multiple property per JSON, but not as a preset method.
@ThomasBurleson: This just creates an alias for the given option.
=> ﻿feat(): support multiple as a default preset method

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/autocompleteController.js, src/components/autocomplete/js/autocompleteDirective.js, src/core/services/liveAnnouncer/live-announcer.js, src/core/services/liveAnnouncer/live-announcer.spec.js
* Removes the static messages, which should be detected by the screenreaders
* Introduces a Screenreader Announcer service (as in Material 2 - https://github.com/angular/material2/pull/238)
* Service can be used for other components as well (e.g Toast, Tooltip)
---
I plan to walk through all components after this PR has been merged, and improve their accessibility announcements.
> Also this could help providing proper accessibility announcements for Dialogs, Toasts and Chips.
Fixes #9603.
=> ﻿fix(autocomplete): provide proper accessibility announcements

src/components/checkbox/checkbox.js, src/components/menuBar/js/menuItemDirective.js, src/components/switch/switch.js, src/components/tooltip/tooltip.js, src/core/util/constant.js
There are several directives that are supposed to run before `ngAria` and who have a hardcoded priority of 210. This change moves the priority to a constant so it's easier to maintain.
=> chore(): move hardcoded priority value to a constant

docs/app/css/style.css, docs/app/js/app.js, docs/app/partials/menu-toggle.tmpl.html
* Fixes users being able to tab through the hidden content on the docs site.
* Switches the docs site's menu accordions to use `$animateCss` for their transitions. This allows us to reliably know when an animation has started and finished.
Fixes #8896.
=> fix(docs): prevent tabbing over hidden content; better animation handling

src/components/card/card.scss
Safari has an alignment issue with SVG icons when its parent has
any padding, causing its content to shift placement
* Force SVG elements to inherit height and width properties.
Fixes #9147
=> fix(card): fix alignment with avatar icons in Safari

src/components/toolbar/toolbar.scss
Checkboxes should center vertically when inside a toolbar
* Inherit margins from parent as in h1, h2, and h3
Fixes #9500
=> feat(toolbar): add CSS rules for checkbox support

src/components/datepicker/js/datepickerDirective.js, src/components/datepicker/js/datepickerDirective.spec.js
* Adds the `aria-owns` attribute to the datepicker, linking it to the calendar pane. This is necessary since the calendar isn't a child of the datepicker in the DOM.
* Adds the `aria-expanded` attribute, indicating when the calendar is open.
* Moves the accessibility tests to their own separate suite.
Fixes #9727.
=> fix(datepicker): add aria-owns and aria-expanded support

src/components/panel/panel.js, src/components/panel/panel.spec.js
* Makes the panel's current actual position available, when passing in a function to the `withOffsetX` and `withOffsetY` methods. This allows users to make better decisions when determining the offset.
* Fixes some extra indentation that was throwing off IDEs when determining the file's indentation level.
* Fixes the `_isOnScreen` method not being marked as private.
This PR is a followup to #9697.
=> fix(panel): make the actual position available in the offset methods

src/components/input/input-theme.scss
According to Material Design spec and a11y accessibility, a focused
text field should have a secondary text opacity
* Change input placeholder color from foreground-3 to foreground-2 on focus
Fixes #8903
=> fix(input): increase placeholder contrast on focus

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/autocompleteDirective.js
* Added support for ng-pattern attribute on the autocomplete
* Added ng-trim to supported attribute docs as well.
Fixes #9755. References #4492.
=> ﻿feat(autocomplete): support ng-pattern attribute

src/components/input/input.js, src/components/input/input.spec.js
* Currently the md-maxlength char counter was not updated properly and listening on the different events is unnecessary.
ngModelController will also update the model, when the `input` event gets called.
Additonally we can cover all updates in the $validator itself, because it will always update, when changes get applied to the model.
Fixes #1870. Referencing #8351
=> fix(input): md-maxlength not properly updates on model changes.

src/components/tabs/js/tabsDirective.js, src/components/tabs/tabs.spec.js
* Remove role="tab" from dummy tabs
Fixes #9450
=> fix(tabs) dummy tabs should not have acccessibilty roles

src/components/list/list.js, src/components/list/list.spec.js, src/components/menu/demoBasicUsage/index.html, src/components/menu/demoBasicUsage/script.js, src/components/menu/demoCustomTrigger/index.html, src/components/menu/demoCustomTrigger/script.js, src/components/menu/demoCustomTrigger/style.css, src/components/menu/demoMenuPositionModes/index.html, src/components/menu/demoMenuPositionModes/script.js, src/components/menu/demoMenuWidth/index.html, src/components/menu/js/menuController.js, src/components/menu/js/menuDirective.js, src/components/menu/menu.spec.js, src/components/menuBar/demoBasicUsage/index.html, src/components/menuBar/js/menuBarDirective.js
* Deprecates the `$mdOpenMenu` method in favor of `$mdMenu.open` in order to simplify the API.
* Exposes the `$mdMenu.close` method on the menu's scope, allowing for custom closing behavior.
Fixes #8446.
=> feat(menu): expose close method on element scope; deprecate $mdOpenMenu

src/components/dialog/dialog.js, src/components/dialog/dialog.scss, src/components/dialog/dialog.spec.js
* Removes the `.md-actions` deprecation from pre- v1.0.0
* Simplifies the method to search for a close button
Closes #9633
=> update(dialog): remove .md-actions deprecation

src/components/panel/panel.js, src/components/panel/panel.spec.js
Prevents the panel from going outside the viewport by adjusting the position.
If developers want more control over how the panel gets repositioned, they can specify addition fallback positions via `addPanelPosition`.
Related to #9641.
Fixes #7878.
=> update(panel): constrain panel to viewport boundries

docs/app/css/style.css
Removes an instance of the outdated gradient syntax from the docs CSS. This was causing a warning to be logged by Autoprefixer.
=> chore(docs): remove outdated gradient syntax

src/components/autocomplete/js/autocompleteDirective.js
Developers might have an autocomplete inside of a VirtualRepeat container and will wonder why the autocomplete's dropdown items are not updating.
> This is because the VirtualRepeat only updates the scope bindings (rather than re-creating the autocomplete) and the autocomplete displays the previously cached results.
Closes #9815.
=> docs(autocomplete): common issue inside of virtual repeat

src/components/icon/demoFontIconsWithLigatures/index.html, src/components/icon/js/iconDirective.js
For md-icon font ligatures, `ng-bind` should be used, to keep logic modular inside the md-icon declaration. This is also an
important change for users that use multilingual support in their applications and use our demo code as a template
* Update icon demo to use ng-bind instead of inline text interpolization
* Update icon documentation to explain ng-bind usage and its importance with localization support
`ng-bind` is more also more efficient than text interpolization.
Fixes #9750
=> docs(icon): l10n translations mangles interpolated font ligature

.travis.yml
Updates the Travis configuration
* Use the latest NodeJS LTS version
* Removes unnecessary caching directory (.pub-cache for Dart)
* No longer runs Travis explicitly on the `feat/panel` and  `patch` branch.
* Removes the Graphical Interface initialization, because everything runs on Saucelabs now (slows builds down)
* Removes unnecessary Modes (Normal, and Browsers) because we removed those a few months ago.
=> chore: clean travis configuration

src/components/colors/colors.spec.js
IE and Edge convert RGB colors to RGBA automatically, which was being handled by the `colors` unit tests via browser sniffing in IE. The browser sniffing doesn't work in Edge, which was causing the tests to fail. This hasn't been noticed until now since we've only been running the tests against IE 11.
These changes switch to using feature detection to check whether the browser converts to RGBA.
=> fix(colors): failing unit tests against Edge

src/components/navBar/demoBasicUsage/index.html
Add a missing closing div tag to the basic usage demo for the navbar component.
=> demo(navbar): Add closing div tag.

src/core/util/constant.js
The `$mdConstant` service uses Angular's `$sniffer` service to determine the browser's prefix via the `vendorPrefix`.
`vendorPrefix` was removed with https://github.com/angular/angular.js/commit/35482babd9eb0970edbc99f223e04594a9d09364.
These changes provide the same functionality, without depending on `$sniffer`. They also fix the current CI failures.
=> fix(constant): remove dependency on $sniffer

src/components/sidenav/sidenav.scss
sidenav was missing CSS a pre-animation state when transitioning
from closed to locked open
* Add CSS for missing pre-animation state
* Add comments to clarify animation logic
Fixes #9425
=> fix(sidenav): correct animation from closed to locked open

src/components/datepicker/js/dateLocaleProvider.js, src/components/datepicker/js/datepickerDirective.js, src/components/datepicker/js/datepickerDirective.spec.js
* Passes in the timezone when formatting the date in the datepicker directive.
* Combines a few redundant calls into a method.
Fixes #9725.
=> fix(datepicker): pass in the timezone when formatting the date

src/components/progressCircular/demoBasicUsage/script.js, src/components/progressCircular/js/progressCircularDirective.js, src/components/progressCircular/progress-circular.spec.js
* Fixes the `path` element not being updated when a progress circle's `md-diameter` changes.
* Fixes a warning being logged for the progress circlar demo.
* Does some minor cleanup in the progress circle directive.
Fixes #9841.
=> fix(progress-circular): path not being re-rendered when diameter changes

gulp/config.js
Since the CSS is being compiled in alphabetical order, the mdPanel styles end up after most components in the compiled CSS, which makes it hard for components that implement mdPanel to override it's styles (the `opacity` in particular). This change sorts the panel styles to the top, right after all of the core structural CSS. This is a temporary solution until we get rid of interimElement and move mdPanel into the core.
CC @ErinCoughlan @bradrich
=> update(build): sort panel styles to the top

src/components/panel/panel.js, src/components/panel/panel.spec.js
Hooks up the `contentElement` option from `$mdCompile` to `$mdPanel`, allowing for a pre-compiled element to be used as the panel's content.
Relates to #9675.
Fixes #9757.
=> feat(panel): add contentElement option

src/components/checkbox/checkbox.js, src/components/checkbox/checkbox.spec.js
* Right now (as same as with the button) the focus will be automatically restored when switching the browser tabs (this is bad UX).
* Using the new $mdInteraction service could remove the random $timeout and just fix this issue easily.
References #7963. References #8749.
=> fix(checkbox): properly show focus effect

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/autocompleteController.js, src/components/autocomplete/js/autocompleteDirective.js
Because obstructions in the viewport (liked fixed-position elements) cannot be automatically detected, allow users to override top/bottom positioning when needed.
Usage:
```html
<md-autocomplete md-items="item in ctrl.querySearch(ctrl.searchText)"
md-dropdown-position="bottom"
...
```
Fixes #9769.
=> Add md-dropdown-position option to mdAutocomplete.

src/components/navBar/demoBasicUsage/index.html, src/components/navBar/navBar.js, src/components/navBar/navBar.scss, src/components/navBar/navBar.spec.js
* Adds support for the `md-no-ink-bar` attribute for the navBar (as same as in the tabs)
> Notice that the inkbar will be only hidden (as same as within the `md-tabs` component)
> = Reduces watchers and also keeps the Code A LOT more clear.
Closes #9862.
=> feat(navBar): option to disable ink bar

src/core/util/util.js, src/core/util/util.spec.js
Currently the `disableScrollAround` function measures the body in order to determine whether to hide it's overflow. This measurement can get thrown off by the `html` node's scrollbar that gets added a few lines above. This change switches to adding the scrollbar to the `html` node after the body measurements are done.
Fixes #9860.
=> fix(util): body overflow-x breaking disableScrollAround

src/components/panel/panel.js, src/components/panel/panel.spec.js
Hello,
@ErinCoughlan @bradrich 
Here is a small PR to add an "on close success" hook for users who want to run some code after a panel successfully closes.
It also adds an optional parameter to the "close" function which allows the user to specify a string describing why the close happened (standardized strings have been added to the "escapeToClose" and "clickOutsideToClose" functions. 
Please Review.
=> feat(panel): Adding a hook on close success.

src/components/navBar/navBar.js
With the current approach, the navbar creates 3 child buttons and uses 3 `ng-if` statements to determine which one to render. This seems wasteful.
This PR moves that logic to the compilation phase which will only be triggered once (per occurrence in the DOM) and won't add any more watches.
=> perf(navbar): reduces amount of watchers and buttons per item

src/components/sidenav/sidenav.js, src/components/sidenav/sidenav.spec.js
Currently the sidenav triggers the resize handlers whenever it is opened, however in most cases the element heights haven't been computed properly, causing wrong measurements. This PR moves the event trigger to an `rAF` call in order to give the browser more time to calculate the dimensions.
Fixes #9745.
=> fix(sidenav): allow more time before triggering a resize of the children

src/components/datepicker/js/datepickerDirective.js, src/core/services/gesture/gesture.js
Removes the datepicker's dependency on `$mdGesture` by inlining the check. This is a preparation for the switch over to HammerJS.
Fixes #9793.
=> fix(datepicker): remove dependency on $mdGesture

src/components/button/button.js, src/components/button/button.spec.js, src/core/services/interaction/interaction.js, src/core/services/interaction/interaction.spec.js
* Only apply the focus effect for keyboard interaction (as same as it does currently, but not with a random timeout).
Similar to #9827 
Fixes #8749. References #7963
=> fix(button): properly show focus effect

src/components/tabs/js/tabsController.js, src/components/tabs/js/tabsDirective.js
`aria-activedescendant` should be blank if no tabs could be found
* Add null check when searching for currently focused tab
Fixes #9279
=> fix(tabs): properly blank activedescendant attr when no tabs exist

src/components/autocomplete/autocomplete.scss
* The autocomplete used in the "very early" stages of its implementation some special keyframes for the dropdown entering / leaving.
* Those have been replaced with a simple opacity transition and the old keyframes are just unused and bloating the component SCSS.
=> update(autocomplete): remove unused css keyframes

src/components/navBar/demoBasicUsage/index.html, src/components/navBar/navBar.js, src/components/navBar/navBar.spec.js
Options can now be passed through the `sref-opts` attribute on the `md-nav-item` element to the `ui-sref-opts` attribute that will be added to the rendered DOM element. All known options from the [`ui-router-opts` wiki](https://ui-router.github.io/docs/latest/interfaces/transition.transitionoptions.html) are supported.
Fixes #9481
=> feat(md-nav-item): Support for `ui-sref-opts` on `md-nav-item`

gulp/util.js
Adds a config that will turn instances of `something.$inject` into `something['$inject']`.
This helps in cases where Closure strips the injector due to the object annotation having a `@constructor` directive.
Note that the regular JS builds have the same output as before.
Fixes #9758.
CC @jelbourn
=> fix(build): prevent closure from stripping $inject annotations

src/components/tabs/js/tabsController.js, src/components/tabs/js/tabsDirective.js, src/components/tabs/tabs.spec.js
* Fixes the tabs directive setting the `aria-controls` attribute when a tab doesn't have content.
* Fixes the tabs adding unnecessary elements when a tab's content consists only of whitespace or it doesn't have content, but any of it's siblings do.
* Switches to a faster way of checking whether a tab element has content.
* Adds unit tests for the `md-no-tab-content` behavior.
Fixes #9108.
=> fix(tabs): don't set aria-controls when there is no content; better empty tab handling

src/components/dialog/demoThemeInheritance/dialog1.tmpl.html, src/components/dialog/demoThemeInheritance/index.html, src/components/dialog/demoThemeInheritance/script.js, src/components/dialog/demoThemeInheritance/style.css, src/components/dialog/dialog.js, src/components/dialog/dialog.spec.js, src/core/services/theming/theming.js, src/core/services/theming/theming.spec.js
- Dialogs now can also inherit promise/function defined themes and listen to the targetElement theme changes
- Removed wrong tests, we now assume that if an interpolation is being used in `md-theme` it was meant to be watched,
unless one-way binding (::) was applied.
Related to #9475
> Note: rebased on #9475 until it would be merged in.
cc @ErinCoughlan, @ThomasBurleson, @topherfangio
=> feat(dialog themes): extended theme inheritance of dialogs

src/components/datepicker/js/datepickerDirective.js, src/components/datepicker/js/datepickerDirective.spec.js
Adds the `md-date-locale` attribute which can be used to overwrite the locale formatting on a per-element basis.
This wasn't possible before, because the locale was global and it was being applied during the `config` phase.
These changes relate to PR #9736, because the specific datepicker modes might require special formatting (e.g. only showing the MM/YY on a credit card form).
Fixes #9270.
=> feat(datepicker): allow the date locale to be overwritten on a per element basis

src/components/datepicker/js/calendar.spec.js, src/components/datepicker/js/calendarMonth.js, src/components/datepicker/js/calendarYear.js
The datepicker's calendar uses `md-virtual-repeat` to render itself. The virtual repeater expects that all elements that it has rendered will have a certain height, however this may not be the case if it renders an empty month/year element in the calendar. If this happens (it's usually if the current value and the maximum date are in the same month), the calendar can start jumping while scrolling.
This change adds an empty `<tr>` that will ensure that even empty elements have a height. When the element is compiled, the empty `<tr>` will be overwritten.
Fixes #9863.
=> fix(datepicker): ensure that all month/year elements have the expected height

src/components/autocomplete/autocomplete.scss, src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/autocompleteController.js, src/components/autocomplete/js/autocompleteDirective.js
*  Adds a new attribute, which allows developers to explicitly show the clear button for all types of autocomplete's.
Closes #4841. Closes #2727
=> feat(autocomplete): option to toggle the clear button

src/components/select/select.spec.js
- Replaces a lot of redundant uses of `injector` in individual unit tests with a single one in the `beforeEach`.
- Removes a few unused variables and arguments.
- Cleans up some of the utility functions.
=> chore(select): clean up testing setup

docs/app/js/app.js
Fixes a JS error in the docs site due to an assumption that the `offsetParent` of the list items will always be defined. This isn't the case on mobile since the sidenav is hidden off-screen.
=> chore(docs): fix js error on mobile

src/components/dialog/dialog.js
- Add a brief documentation on how to show multiple dialogs at the same time.
- Adds the `multiple` option to the preset methods (as same as for the $$interimElement default preset)
@ThomasBurleson I plan to add a demo as well (but this should be in another PR and preferably
after the panel conversion)
Closes #8630.
=> docs(dialog): explain how to show multiple dialogs

src/components/bottomSheet/bottom-sheet.js
* Adds missing documentation for the `bindToController` option inside of the bottomSheet directive / service.
Closes #8811
=> docs(bottom-sheet): document bindToController option

src/components/dialog/demoThemeInheritance/script.js
* Recently a new demo has been added in b7ae33ea0d16242f451f49671c341c3923e9f53.
This demo uses the same Angular module name as the first demo (so they interfere and don't work)
Fixes #9977
=> chore(dialog): fix broken demos

src/components/tabs/js/tabsController.js
Tab buttons did not receive focus style unless the user performed
certain keypress events while navigating. This logic did not account
for tabbing into the component
- Set variable when tab button is focused
- Use mdInteraction to detect keyboard interaction
This new logic is similar to that of mdCheckbox
Fixes #9039
=> fix(tabs): improve tab button focus styling logic

src/components/datepicker/js/datepickerDirective.js, src/components/datepicker/js/datepickerDirective.spec.js
- Fixes a JS error in the datepicker, when used with `openOnFocus`, caused by `closeCalendarPane` being called twice in a row. This was introduced accidentally when combining a few redundant calls into the `onExternalChange` method.
- Fixes NVDA reading out "Unknown", instead of the calendar, due to the `aria-owns` attribute being set on the `input`. This change moves the `aria-owns` to the datepicker itself.
**Note:** these issues are still only in master, they weren't a part of 1.1.1
=> fix(datepicker): reference error and calendar not being read out by nvda

src/components/radioButton/radio-button.js, src/components/radioButton/radio-button.spec.js
- Fixes all of the radio buttons within a radio group having `aria-checked` set to true on load, when using `ng-value`.
- Cleans up the `radioButton` directive.
Fixes #9400.
=> fix(radio-group): wrong aria-checked value on load when used with ng-value

src/components/button/button.scss, src/core/style/mixins.scss
Buttons should include proper touch target area of 48x48px. Developers
should be able to use denser buttons to target mouse users.
- Add mixin for md-dense objects
- Add minimum touch target for buttons
- Add md-dense option for buttons
=> feat(button) add md-dense support

src/components/tabs/demoStaticTabs/index.html, src/components/tabs/demoStaticTabs/readme.html, src/components/tabs/demoStaticTabs/script.js, src/components/tabs/demoStaticTabs/style.scss, src/components/tabs/tabs-theme.scss
- Adds icons to a demo.
- Fixes typo in aforementioned demo.
- Corrects color of icons in a disabled/non-focused tab label.
Closes #9536
=> fix(tabs): Icon color isn't correct when the tab item is not active

src/components/panel/panel.js
Previously, the panel would bind to a scroll event and determine within the handler whether to do anything. This change moves the check outside of the event handler and only binds if scrolling is enabled.
=> fix(panel): don't bind scroll event if scrolling is disabled

src/components/tooltip/demoBasicUsage/index.html, src/components/tooltip/demoBasicUsage/script.js, src/components/tooltip/demoBasicUsage/style.css, src/components/tooltip/tooltip-theme.scss, src/components/tooltip/tooltip.js, src/components/tooltip/tooltip.scss, src/components/tooltip/tooltip.spec.js
Tooltip has been refactored to use the MdPanel API to position, animate open and closed, and show the tooltip as a result of user interaction.
Breaking Change: Tooltips with not content will no longer show and result in an error.
Fixes #9563
=> feat(tooltip): Tooltip use MdPanel API

src/components/list/list.js, src/components/list/list.spec.js
- The list item no longer resolves the aria-label text from the content incorrectly<br/>
(`aria-hidden` is currently ignored - SHA b3cb84d3fa9408fb3f7192020eaef0d2c82bd929 fixed this for `$mdAria`)
- Now shows ARIA warnings for list-items being clickable
- Fixes incorrect tests with uncompiled buttons due to missing `buttons` module registration.
Fixes #9933.
=> fix(list): expect aria-label with respect to aria-hidden

src/components/navBar/navBar.js, src/components/navBar/navBar.spec.js
- Fixes the tabs in the navbar not being read out by screen readers. This is due to the fact that they were being highlighted as focused, but focus wasn't actually being passed to them.
- Some minor cleanup in the navbar.
Fixes #9383.
=> fix(navbar): tabs not being read out by screen readers

src/components/input/input-animations.spec.js, src/components/input/input.js, test/angular-material-mocks.js
In certain scenarios, the `ng-messages` of an autocomplete would fail to animate properly leaving them in a state where they were in the DOM, but not visible to the user.
This was ultimately caused by the animations not properly retrieving the messages element to animate, but was also tangentially caused by the animations not properly calling the `done` callback upon failure.
There are three associated fixes:
1. Log a warning if the messages element or it's children cannot
be found.
2. Ensure the `done` callback always fires even on failures.
3. Ensure the `getMessagesElement()` method correctly returns when
the element passed IS the messages element itself.
Fixes #9468.
=> fix(autocomplete): Fix messages not appearing.

src/components/datepicker/datePicker.scss, src/components/select/select-theme.scss
- Fixes the datepicker's arrow being off a few pixels inside `md-input-container`, as well as being too close to the bottom when not in a `md-input-container`.
- Fixes the select's arrow icon being too dark, because it inherits from the closest `color` rule.
Relates to #9798.
For reference, here's what it looked like before:
And here's what it looks like after:
=> fix(datepicker,select): arrow button consistency

src/components/tabs/tabs.scss
Certain browsers had issues with resizing tab content md-tabs' parent
would change size or have an unspecified size during creation (for
example in a dialog). Converting to flexbox solves this issue.
- Set md-tab-content to flexbox
- Set md-tab-content's div to fill parent
- Set md-pagination-wrapper to flexbox
Fixes #9206, #9704, #9779
=> fix(tabs): support flexible content layout

src/components/virtualRepeat/virtual-repeater.js
- Removes an instance where the virtual repeater wraps the `document` in a jqLite wrapper and then unwraps it immediately.
- Removes an unused function.
=> chore(virtual-repeat): remove a couple of pointless expressions

docs/app/css/style.css, docs/app/js/css-api-table.js, src/components/toolbar/demoBasicUsage/index.html, src/components/toolbar/toolbar.js, src/components/truncate/demoBasicUsage/index.html, src/components/truncate/demoBasicUsage/style.scss, src/components/truncate/truncate.js, src/components/truncate/truncate.scss, src/components/truncate/truncate.spec.js
Currently, the title text of a toolbar wraps around on small screens causing the toolbar to become larger than expected.
- Provide a new `md-truncate` component that applies the appropriate styles
for using CSS-based text-overflow with an ellipsis.
This component is designed to work nicely with the Toolbar component,
but is also reusable and can be used in any other component.
- Add docs/demos for the new component.
- Update Toolbar demos to use new `md-truncate` component and show proper
usage.
Additionally, add the appropriate CSS docs in a new CSS & Styles section which includes a new doc-only directive (`docs-css-api-table`) that creates a clean way to view documentation regarding available CSS classes.
Fixes #9026.
---
_**Edit:** Add screenshot of new docs section._
=> fix(toolbar): Title text should allow ellipsis.

src/components/datepicker/js/calendar.js, src/components/datepicker/js/calendar.spec.js
If use the md-calendar directly in the body without datepicker, boundKeyHandler will disable some keyEvent on other input elements in the page. So only apply the handleKeyEvent on the document.body when the md-calendar is inside datepicker. Otherwise, apply on the calendar element only.
=> fix(md-calendar): boundKeyHandler preventDefault on other input elements

src/components/subheader/subheader.js, src/components/subheader/subheader.spec.js
Previously, due to the way the sticky headers work, lists with an `md-subheader` were being read out by screen readers as follows:
- Header 2
- Header 1
- Header 1
- Content 1
- Header 2
- Content 2
This can be confusing for users since it doesn't reflect the real structure of the page, as well as not reading out the headers as being headers.
These changes add the ARIA attributes that allow for the content to be read out as:
- Header 1
- Content 1
- Header 2
- Content 2
Fixes #9392.
=> fix(subheader): add accessibility support

src/components/datepicker/datePicker.scss, src/components/datepicker/js/datepickerDirective.js
Usually the datepicker uses padding and a negative margin to prevent
clicks on the triangle button from shifting the entire element, which
is unnecessary in the case where the triangle icon is disabled. This
change removes the negative margin and padding in that case.
Fixes #9850.
=> fix(datepicker): remove negative margin if triangle icon is disabled

src/components/chips/chips.spec.js, src/components/chips/js/chipsController.js
- Sometimes the ngModel of the custom input element (provided by the user) does not have any initial $viewValue.
- The chips component always expects the chipBuffer to be a string and a non-string reference can cause Runtime Exceptions.
Fixes #9867.
=> fix(chips): use empty chip buffer if not a string

src/components/panel/panel.js, src/components/panel/panel.spec.js
If both the `clickOutsideToClose` and `propagateContainerEvents` parameters are set to true within the panel configuration, then the panel will be closed when a click happens outside of the panel.
Fixes #9388
=> fix(panel): clickOutsideToClose with propagateContainerEvents

src/components/panel/panel.js, src/components/panel/panel.spec.js
- Adds the ability to update the animation of a panel, without having to re-create it.
- Adds a unit test for verifying that the backdrop animation duration matches the one of the panel. This was missed in #9570.
=> feat(panel): add the ability to update the animation of an existing panel

src/components/dialog/dialog.js, src/components/dialog/dialog.spec.js
- Currently the dialog always restores focus to the origin element upon close.
- The focus should be only restored if the dialog was opened with keyboard interaction - Same behavior as with the sidenav closing ([See here](https://github.com/angular/material/blob/master/src/components/sidenav/sidenav.js#L463))
Fixes #7963.
=> fix(dialog): only restore focus with keyboard interaction

src/components/panel/panel.js, src/components/panel/panel.spec.js
The panel wasn't being constrained to the viewport when opening it multiple times in a row, due to the "constrain to viewport" logic only running if the `_actualPosition` isn't known. These changes make it so the panel always gets constrained to the viewport.
Fixes #9942.
=> fix(panel): panel not being constrained to viewport on repeat openings

src/components/panel/panel-theme.scss, src/components/panel/panel.js, src/components/tooltip/tooltip-theme.scss, src/components/tooltip/tooltip.js
- Initialized theming through `$mdTheming` on the panel element and container after the panel is created.
- Fixed the panel and tooltip theme Sass files to remove unthemed styles and complicated syntax.
- Removed an unnecessary `$mdTheming` call from the tooltip directive.
Fixes #10030
=> fix(mdPanel): Panel and tooltip theming

src/components/select/select.js
The documentation for md-select's `multiple` attribute is repetitive and unhelpful.
This PR adds language to clarify the ui and model changes when the attribute is set to true.
> When set to true, allows for more than one option to be selected. The model is an array with the selected choices.
=> docs(select) clarify multiple attribute

src/components/chips/chips.spec.js, src/components/chips/js/chipsController.js
- Properly adds the selected item of the autocomplete to the chips when `md-add-on-blur` is enabled
- No longer adds chips on blur when `md-require-match` is enabled (previously user could add non-matches to the chips)
- Moves logic into an extra function to keep blur listener clear.
@ThomasBurleson I do not consider this as a `backlog` issue, since this is more likely a broken attribute of the `md-chips`
Fixes #9582.
=> fix(chips): add-on-blur with autocomplete

src/components/progressCircular/js/progressCircularDirective.js, src/components/progressCircular/js/progressCircularProvider.js, src/components/progressCircular/progress-circular.scss, src/components/progressCircular/progress-circular.spec.js
Previous animation did not properly animate the circle stroke
* Use persistent SVG path for all animations
* Change `stroke-dashoffset` to match spec on every requested frame
* Rotate object -90 degrees every iteration
* Correct overall counter clockwise animation timing in SCSS
Instead of creating a new SVG path every frame, we will instead simply
animate the `stroke-dashoffset` parameter. This allows us to match spec
while also increasing performance by simplifying logic per frame.
Fixes #9879
=> fix(progressCircular): update animation to spec

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/autocompleteController.js, src/components/autocomplete/js/autocompleteDirective.js
This allows a `md-autocomplete-wrap` to be applied to an ancestor of a `md-autocomplete` and cause that element to be used for evaluating the width of the autocomplete instead of the the `md-autocomplete-wrap` element. This addresses #4450 which constrains the width of the menu that pops up to the width of the auto complete wrapper.
When using chips and possibly in other situations it would be desirable to have the menu be the width of the chips component.
Adding support for this attribute would allow for this and other similar behavior.
A working version of this change can be seen at https://codepen.io/allenperl/pen/KzmQwr.
=> Add md-autocomplete-snap="width"

src/components/chips/contact-chips.spec.js, src/components/chips/js/contactChipsDirective.js
Add md-min-length to md-contact-chips and propagate attribute to md-autocomplete.
Add md-has-not-found=true attribute to md-autocomplete.
Fixes #2423.
=> fix(md-contact-chips): support md-min-length on md-contact-chips.

src/components/checkbox/checkbox.js, src/components/input/demoErrors/index.html, src/components/input/demoErrors/script.js, src/components/input/input-animations.spec.js, src/components/switch/switch.js
Add support for animating ng-messages on md-checkbox, in line with input, md-select and md-datepicker (as explained in #9430). Fixes #9430 and #8267.
Tested locally, but still need to add tests. I would appreciate if someone could review.
The tests are based on the test of the [input-animations.spec.js](https://github.com/angular/material/blob/master/src/components/input/input-animations.spec.js).
=> feat(checkbox/switch): add support for animating ng-messages

src/components/autocomplete/autocomplete.scss, src/components/autocomplete/autocomplete.spec.js
The `VirtualRepeat` determines the original size (when shrank) of the dropdown from the computed style.
Commit b114302717341638bb627792c197ec3c43e069ff removed the fixed height from the SCSS, because of the dynamic dropdown height.
Setting the height to `100%` allows the `VirtualRepeat` to properly determine the dimension of the dropdown.
Fixes #9726.
=> ﻿fix(autocomplete): dropdown shrink restore

src/components/menuBar/menu-bar.scss
Firefox does not support flex on buttons
* Change text to use float instead flex for positioning
Fixes #9771
=> fix(menuBar): do not use flex for buttons

src/components/tooltip/tooltip.js
The tooltip role was being assigned to an element that is being detached and not re-attached, causing an a11y issue. The tooltip role is now being assigned to the panel element through the `role` attribute.
Fixes #10045
=> fix(mdTooltip): Tooltip role

src/components/tooltip/tooltip.js, src/components/tooltip/tooltip.spec.js
=> fix(tooltip): properly interpolate tooltip text to prevent possible XSS

docs/content/Theming/05_under_the_hood.md
Update function references on theming docs to match the current state of theming files.
As I was doing research on theming to solve another issue, I found out the theming docs are a little outdated and decided to open a pull request to update them :grinning:
=> docs(theming): update references on theming docs

src/components/menu/js/menuDirective.js, src/components/menu/js/menuServiceProvider.js, src/components/menu/menu.spec.js
No longer throws runtime exceptions in the $mdMenu service when no `md-menu-content` element is specified.
> When the `$mdMenu` service is used programmatically it will show a warning and just doesn't setup the interaction.
When the `md-menu` directive misses the `md-menu-content` element a normal error will be thrown, so developers can detect before actually opening the menu, that the `md-menu-content` element is missing.
Fixes #9709.
=> fix(menu): avoid runtime errors when menu-content isn't set.

src/components/tooltip/tooltip.js
The test failures were occurring due to the tooltip using the panel API. All requests to destroy the scope need to also be accompanied by requests to destroy the panel.
Fixes #10114
=> fix(mdTooltip): AngularJS 1.3.20 test failures.

src/components/navBar/navBar.js, src/components/navBar/navBar.spec.js
It is possible that _getTabs returns an array of undefined when mapping over linkArray as .controller('mdNavItem') can return undefined if it cannot find the corresponding controller which will cause an error to be shown in the console during the digest cycle.
This change assures that we do not attempt to update the tabs in the case that tabs is an undefined array.
=> fix(nav-bar): null check tabs when updating nav-bar

src/components/select/select.js, src/components/select/select.spec.js
Fixes the select component being unable to switch between falsy options (e.g. `0` and `false`) due to a use of non-strict comparison.
Fixes #9533.
=> fix(select): unable to switch between falsy options

src/components/list/demoBasicUsage/index.html, src/components/list/demoListControls/style.css, src/components/list/list-base.scss, src/components/list/list.js, src/components/list/list.scss, src/components/list/list.spec.js, src/components/toolbar/toolbar.scss
- Simplifies the List components SCSS
- Fixes Dense Mode for List and introduces super elegant approach
- Make SCSS more modular by having a base and dynamic variables
- Remove unnecessary DOM node level for button wrap.
- No longer wrap proxied elements inside of buttons
- Multiple Secondary Items should align properly and have consistent spacing.
- Dense Mode should not cut characaters on different environments.
@EladBezalel and I had a short meeting and I showed him some of the new approaches.
R: @EladBezalel 
Fixes #6152. Fixes #8890 References #8482.
=> refactor(list): simplify list component scss

src/components/panel/demoPanelProvider/index.html, src/components/panel/demoPanelProvider/script.js, src/components/panel/demoPanelProvider/style.global.css, src/components/panel/panel.js, src/components/panel/panel.spec.js
Fixes #10006 - Allows users to be able to add the $mdPanelProvider to the config block
of their application. They can use this provider to create one or more
configurations for upcoming panel elements.
Fixes #10162 - Alters the configuration of a panel with a user-defined id that has been
saved when that panel is re-created. This will update the configuration properties such
as panelClass, etc.
=> feat(panel): Panel provider

src/components/menu/js/menuServiceProvider.js
* Re-adds the accidentally removed `inherit` function from commit 0b65e08e24fd017250e0637a96b445f25f76c754
=> fix(menu): menu content should inherit theme

docs/config/template/index.template.html, src/components/chips/chips.spec.js, src/components/chips/contact-chips.spec.js, src/components/chips/demoBasicUsage/index.html, src/components/chips/demoBasicUsage/readme.html, src/components/chips/demoContactChips/script.js, src/components/chips/js/chipDirective.js, src/components/chips/js/chipsController.js, src/components/chips/js/chipsDirective.js, src/components/chips/js/contactChipsController.js, src/components/chips/js/contactChipsDirective.js
Previously, chips had no, or very broken, support for accessibility.
Make many updates to fix broken functionality and add required features.
- Remove existing `aria-hidden` attributes.
- Dynamically apply required `role` and `aria-owns` attributes.
- Ensure `tabindex` is set properly on all elements. Particularly,
you can now tab to, and navigate through, a set of chips in
readonly mode.
- Provide new `input-aria-label` option to identify the inputs.
- Provide new `container-hint` option used when the element is in
readonly mode.
- Provide new `md-chip-append-delay` option which controls the delay
(in ms) before a user can add a new chip (fixes screen readers).
- Fix issue with `delete-hint` never being read by screen readers
because it was outside of the chip.
- Fix keyboard navigation …
=> fix(chips): Add basic accessibility support.

docs/content/Theming/01_introduction.md, docs/content/Theming/06_browser_color.md
Using markdown caused issues with routing.
* Use ng-href to link to pages
Fixes #10203
=> fix(docs): fix broken links in theming docs

.travis.yml, config/sauce-browsers.json, scripts/sauce/setup-tunnel.sh, scripts/travis-run-script.sh
* Now runs tests for Angular v1.6.1 on the Travis CI in an optional mode.
Closes #10205
=> chore: run tests for angular 1.6 on travis

config/sauce-browsers.json
* Currently in Saucelabs for Firefox v50 a single unit test for the input component fails
A few people from the team were asked to reproduce it, but nobody was able to reproduce it locally.
* Reverting this change from SHA e8d29db61f7dc9ebe476406f9e3321e792eb3418 to make the CI green. We are investigating, but this should not affect the CI
=> chore: rollback to firefox 49 sauce browser

src/components/navBar/navBar.js, src/components/navBar/navBar.spec.js
NavBarItems should populate aria-label attribute automatically
* Inject $mdAria into navBarItem controller
* Use text content from element to populate aria-label during postLink
* Create new spec tests
Fixes #10110
=> fix(navBar): automatically add aria-label for navBarItem

src/components/datepicker/datePicker-theme.scss, src/components/select/select-theme.scss
Change the dropdown icon colors for Select and Datepicker to be
darker by default.
**Old Styles**
- Default: foreground-3 (light grey)
- Hover: foreground-2 (darker grey)
**New Styles**
- Default: foreground-2 (darker grey)
- Disabled: foreground-3 (light grey; select only; datepicker
hides the icon when disabled)
Note that the hover effect appeared not to work and since it used
the proper default color, it has been removed.
Also added some newlines for clarity.
=> fix(select/datepicker): Fix dropdown icon colors.

src/components/autocomplete/js/autocompleteController.js
Fix TypeError/NPE in Autocomplete when assuming `$scope.searchText`
was available.
=> fix(autocomplete): Fix TypeError in autocomplete.

src/components/tabs/js/tabsController.js, src/components/tabs/tabs.scss, src/components/tabs/tabs.spec.js
Since tabs now use flexbox for sizing, manually sizing is no longer needed.
This solves issues related tabs inside flexible containers like dialogs.
* Remove updatePagingWidth() function
* Revert width to default values
Fixes #9429
=> fix(tabs): remove manual pagination sizing algorithm

src/components/tooltip/tooltip.js, src/components/tooltip/tooltip.spec.js
Also stop putting things directly on `$rootScope` in the tooltip tests.
=> fix(tooltip): always resolve expressions against the correct scope

src/components/dialog/dialog.js, src/components/dialog/dialog.scss, src/components/dialog/dialog.spec.js
I was asked by @EladBezalel to revert SHA https://github.com/angular/material/commit/2c286b41d6a4d85f2be88986d1331f84241a9b3a.
The deprecation needs to be re-introduced to support older Angular applications, which didn't update yet.
=> fix(dialog): re-add md-actions deprecation class.

src/components/swipe/swipe.js, src/core/services/gesture/gesture.js
- slider was based on mdGesture service that set `touch-action: pan-x` in case the gesture was horizontal;
according the [google pointer-events documentation](https://developers.google.com/web/updates/2016/10/pointer-events):
```
pan-x: The browser is only allowed to perform the horizontal scroll default action.
```
that means we should had enabled `pan-y` and vice-versa instead.
- swipe directive didn't had any `touch-action` css styles, added `touch-action: none` on the directive element on link
fixes #10294, #10187, #10145
=> fix(gestures): slider and swipe touch

src/components/select/select.js, src/components/select/select.spec.js
Fixes an issue, introduced in #9945, that caused the select to override the initial model value.
CC @jelbourn
=> fix(select): don't override initial model value

docs/app/js/app.js
During the last release, the docs site navigation was broken for a bit because the response from `docs.json` wasn't parsed properly. As a result, the versions were `[]` and didn't display.  Seems that the resp object wasn't updated when we switched from `success()` to `then()`.
=> chore: fix response from docs.json

src/components/datepicker/js/datepickerDirective.js, src/components/datepicker/js/datepickerDirective.spec.js
This change adds the ability to have a date string (e.g. "2016-01-02") as the source for the datepicker. Until now only Date objects were allowed.
Fixes #6253.
Fixes #9535.
=> feat(datepicker): allow date strings as the source for ng-model

src/components/icon/icon.spec.js, src/components/icon/js/iconDirective.js, src/core/services/aria/aria.js, src/core/services/aria/aria.spec.js
mdIcon was improperly assuming its parent's text content would be announced didn't apply ARIA roles properly
* Apply `img` role by default
* Don't change ARIA if it's already valid
* Prioritize `alt` attribute for aria-label
* Apply `aria-hidden` attr if parent or parent's parent has ARIA label and is not part of role or tagName whitelist
* Fallback to icon name as an aria label
* Apply `aria-hidden` attr instead of `aria-hidden` when all checks fail
* Add spec tests to ensure new functionality
* Remove improper spec test based on text content
Fixes #9629
=> fix(icon): fix aria roles and attributes

src/components/chips/chips.spec.js
Fixes a couple of chips tests which were failing against Angular 1.3.x due to a timeout that wasn't being flushed.
=> fix(chips): failing unit tests against Angular 1.3

src/components/virtualRepeat/virtual-repeater.js
Fixes [#10144](https://github.com/angular/material/issues/10144) - There is an issue with Chrome that when the browser window is small enough, the intial DOM manipulations alter the scroll, which leads to the caldendar opening to the wrong month. Scrolling twice on the first render to ensure that the position is correct fixes this.
CodePens:
- [Broken Datepicker](http://codepen.io/phillypham/pen/gLJXgY)
- [Fixed Datepicker](http://codepen.io/phillypham/pen/xRNPdJ)
=> fix(virtualRepeat): DOM manipulation may alter scroll

src/components/button/button-theme.scss
There were two `&.md-accent` selector and the former one was obviously unnecessary.
Indeed, the `.md-accent` always use color `{{accent-A*}}` rather than `{{accent-*}}`.
=> mdButton: remove duplicate selectors

src/components/panel/panel.js, src/components/panel/panel.scss
Using a style attribute is prohibited when using strict CSP rules. Fixes #10085.
=> fix(panel): use class instead of style attribute to fix CSP violation

src/components/bottomSheet/bottom-sheet.js, src/components/bottomSheet/demoBasicUsage/script.js
Newer versions of Angular will throw a `Possibly unhandled rejection`
exception if you show a bottom sheet without providing a `.catch()`
clause to handle the rejection.
Add notes to `$mdBottomSheet` documentation and demos to show
proper usage.
=> docs(bottomsheet): Add notes about `.catch()` usage.

src/components/datepicker/js/dateLocaleProvider.js
doc(mdDateLocaleProvider): Fix typo
Fix a typo in `$mdDateLocaleProvider.monthFormatter` documentation.
=> doc(mdDateLocaleProvider): Fix typo

src/components/autocomplete/js/autocompleteController.js
The available space beneath a wrap included space above viewport. When heights of the body
and viewport did not match (e.g. on mobile) dropdown was displayed on the wrong side.
This change make it so available space is calculated properly.
Fixes #10188
=> fix(autocomplete): incorrect evaluation of available space in viewport

src/core/services/gesture/gesture.js
Fixes [#3990](https://github.com/angular/material/issues/3990) - when a user clicks enter/go on an iOS device, the form's submit function is not triggered.
=> fix(mdGesture): fix form submit via enter/go button on iOS (#3990)

src/core/services/layout/layout.js, src/core/services/layout/layout.spec.js
Angular 1.6 added a 'don't trim white-space in attributes' commit (angular/angular.js@97bbf86).
fixes #10426.
=> fix(layout): trim attribute values before use

src/core/services/theming/theming.js
=> docs(theming): defineTheme documentation

src/components/tooltip/tooltip.js, src/components/tooltip/tooltip.spec.js
The tooltip now does not override or update the parent
element `aria-label` unless the parent's `aria-label` does not exist,
or it has been previously set by the tooltip. It determines if it
has been set by the tooltip by placing the `aria-labelledby` attribute
on the parent element and setting it to `tooltip`.
Thx to @bradrich  for original PR.
Fixes #10242.
=> fix(mdTooltip): Tooltip parent aria label override

release.js
Fix deployment of docs to *code.material.angularjs.org*.
Fixes #10329.
=> chore(release): fix duplicate keys in firebase.json

src/components/checkbox/checkbox.js, src/components/checkbox/checkbox.spec.js
When md-checkbox has ng-checked set, checkbox should still be clickable, and work as regular checkbox. 
The only case I see right now where `attr.checked` should be used as `$viewValue`  is when `ng-click` && `ng-checked` is provided - we can then assume `ng-checked` could be changed by `ng-click` callback. This behavior is used in `demoSyncing` for example.
Fixes #10468
=> fix(checkbox): click handling when ngCheckbox is set

src/components/radioButton/radio-button.js
`ngModel` and `ngChange` are part of the `mdRadioGroup` directive and  not of the `mdRadioButton` directive.
Thx to @sebakerckhof!
Fixes #10421.
=> docs(radioButton): ngModel and ngChange are mdRadioGroup properties

src/components/tooltip/tooltip.scss
- according the [spec](https://material.io/guidelines/components/tooltips.html#tooltips-interaction) show and hide duration should be 150ms
fixes #10467
=> polish(tooltip): change transition duration to 150ms

src/core/style/layout.scss
Pulled the flex-33 and flex-66 classes out of the loop. I also removed some odd duplication in the selector. 
> Reduction of 179 KB (uncompressed) from core.css.
Fixes #10504.
=> fix(core): eliminates many (but not all) redundant rules in layout CSS

src/components/tooltip/tooltip.js, src/components/tooltip/tooltip.spec.js
Reinstates scope fix from https://github.com/angular/material/commit/685b9029d699c486ef27f9d00a0c49b90a363552, which was accidentally reverted in https://github.com/angular/material/pull/10464.  Blocking 1.1 release due to Google test failures.
cc: @ThomasBurleson
=> fix(tooltip): resolve expressions against correct scope

src/components/tooltip/tooltip.js, src/components/tooltip/tooltip.spec.js
We recently started setting `aria-labelledby` on parent elements to track if the `aria-label` had already been set by the tooltip. It seems we should use a different attribute as a marker because `aria-labelledby` will take precedence over `aria-label` when set on the same element. In this case, it will point to an element that only exists on the DOM when the tooltip is showing, which hurts accessibility. This is currently blocking 1.1.4 release due to Google breakages.
cc: @ThomasBurleson
=> fix(tooltip): use different attribute to track setting of aria-label

src/components/datepicker/js/calendar.spec.js, src/components/virtualRepeat/virtual-repeater.js, src/components/virtualRepeat/virtual-repeater.spec.js
Fixes https://github.com/angular/material/issues/10144
Datepicker scrolls to wrong date in Chrome.
Issue reproducible in Chrome here: https://material.angularjs.org/latest/demo/datepicker -> “Custom calendar trigger" (Click "Open" a few times and it will reoccur)
Video of bug: https://youtu.be/4Tj0k6b8rVg
=> fix(virtualRepeat): Fix datepicker scroll to wrong current date

src/components/datepicker/js/calendarMonth.js, src/components/datepicker/js/calendarYear.js, src/components/virtualRepeat/virtual-repeater.js
Remove use of `style` tag to conform to CSP better.
_Note: No additional tests since existing tests cover this case._
Fixes #10389.
=> fix(calendar): Conform to CSP.

src/components/dialog/dialog.js
Following #7400 $mdDialog: resolve doesn't work with Promises
=> docs(mdDialog) Remove 'resolve' option from show() method

src/components/panel/panel.js
Change $mdPanel with propagateContainerEvents set to true to not close when it is clicked. #GoodnessSquad
Fixes: #10495
=> fix(panel): fix propagateContainerEvents

src/components/autocomplete/js/autocompleteDirective.js
I am attempting to use md-autocomplete and 'lock' in a users selection once an autocomplete is selected. I ng-disable the directive accordingly. However, I still want the user to be able to clear the autocomplete, even if it is disabled - I simply don't want them to be able to edit the existing text. This pull request will still allow the clear button to be shown even if it is disabled. If the developer doesn't want a clear button when the control is disabled, they can simply update their boolean expression inside of the md-clear-button attribute.
=> update(autoComplete): allow clear button even if directive is disabled

src/components/dialog/demoBasicUsage/script.js, src/components/dialog/dialog.js
Prompt dialog must have ability to make input field required and prevent closing dialog in this case.
Fixes #10135
=> feat(prompt): implement "required" flag for prompt dialogs

src/core/services/gesture/gesture.js
on some touch devices tap is often lost due to small finger movements
fixes #10492
=> feat(mdGesture): allow to change maxClickDistance through $mdGestureProvider.setMaxClickDistance

src/components/panel/panel.js
This adds more documentation so that users of $mdPanel are able to easily inject the correct reference to the created panel in their controller.
The example source code has 'mdPanelRef' as the name of its import, but the rendered HTML in the docs site, converts this to 'MdPanelRef'.
This might be indicative of a larger problem with the dgeni process; Either way, I think the lines I added to the documentation should be enough to remove confusion.
=> Fix casing and add clarity to documentaton on mdPanelRef

src/components/select/select.js, src/components/select/select.spec.js
Fixes a bug that prevented the select from being able to reopen, if it was destroyed while there was an ongoing animation.
Fixes #10453.
=> fix(select): unable to reopen if element was destroyed while closing

src/components/chips/chips.spec.js
Fixes a test in chrome that failed because the test tried to set a programmatic selection on a number input.
Chrome throws a DOMException if something tries to set a text selection on a number input.
=> chore(chips): fix chrome test for selection

src/components/tabs/js/tabsController.js, src/components/tabs/js/tabsDirective.js, src/components/tabs/tabs.scss, src/components/tabs/tabs.spec.js
This commit does a few things related to accessibility:
1) Hides md-dummy-tabs completely from screen readers with aria-hidden.
With this change, screen readers do not hear the dummy tabs read out
when using linear navigation. Instead of focusing the dummy tabs, the
visible tabs are focused. There was a comment that mentions focusing the
dummy tabs as a way to avoid animation issues; however, I could not
replicate the mentioned issues.
2) Fixes the ARIA roles so users can hear "tab 1 of 3" instead of just
"tab" by moving role="tablist" to the direct parent element (which
contains the items marked role="tab"). (VoiceOver in particular)
3) Fixes keyboard interaction to match recommended ARIA practices by
focusing on the active tab when using TAB navigation, then resolving the
focus/active …
=> fix(tabs): Accessibility and keyboard interaction fixes

src/components/tabs/demoDynamicTabs/script.js, src/components/tabs/js/tabsController.js, src/components/tabs/tabs.scss, src/components/tabs/tabsPaginationService.js, src/components/tabs/tabsPaginationService.spec.js
Tabs currently attempts no RTL support for scrolling and pagination.
Update component to properly support RTL.
- Add new MdTabsPaginationService to handle some calculations in
a more testable way.
- Add many instances of RTL checks/math.
- Add minimum tab width based on spec (or tabs width if smaller).
- Update SCSS to account for RTL mode with pagination icons.
- Also add check to ensure pagination buttons ignore clicks when
disabled.
Fixes #9292.
=> fix(tabs): Add proper RTL support.

src/components/tabs/demoDynamicTabs/index.html
Add `md-swipe-content` to tabs demo to be consistent with the tab two description.
Description says: "You can swipe left and right on a mobile device to change tabs."
=> docs(tabs): add `md-swipe-content` attribute to demo

docs/app/js/codepen.js
codepen updated their api to only support https
https://blog.codepen.io/2017/03/31/codepen-going-https/
> NOTE: this breaks development codepens since it's being block by codepen itself
fixes #10692
=> chore(codepen): changed codepen access to https

scripts/bower-material-release.sh, scripts/release.sh, scripts/snapshot-docs-site.sh
Replace deprecated GH_TOKEN with new ANGULARJS_MATERIAL_BUILDS_TOKEN environment variable name.
Fixes #10692, #10734
=> update(scripts): use ANGULARJS_MATERIAL_BUILDS_TOKEN

src/components/input/input-animations.spec.js, src/components/input/input.scss
With commit cf7f21a, animations were moved to input.js in response to an ng-enter
flicker issue with Angular 1.4.x. While the flicker was fixed, new animation bugs
arised. Angular 1.4.x added and backported a ng-enter-prepare to avoid this bug.
* Use `.ng-enter-prepare` to avoid flicker on Angular 1.4+
* Use `.ng-enter:not(.ng-enter-active)` to prepare animations on 1.3 and below
* Update spec tests to use computedStyle
Fixes #6767, #9543, #9723, #10240
Related: angular/angular.js#13408
=> fix(input): correct initial animation state of messages

src/core/util/util.js
`scrollTop` value is restored on `documentElement `instead of `body `when
`overflow-y: scroll` is defined on `html `element.
Closes #10272 #10432
=> fix(util): scrollTop set on proper scroll target

src/core/util/util.js
Fixed an issue where md-dialog contains md-autocomplete elements. These elements remove the scroll mask before the dialog is closed, resulting in an exception when closing the dialog. This a symptom fix. I don't assume that the mask is still there before I try to delete it. But now the dialog closed properly and no errors.
=> Don't assume that the scrollMask is present when closing the md-dialog

src/components/tabs/tabs.scss
Make md-tab-content elements visibility: hidden; entirely instead of setting opacity to zero when inactive. This prevents screen readers and other assistive technology from seeing and interacting with the visibly hidden containers.
=> fix(tabs): Hide md-tab-content elements entirely when inactive.

src/components/panel/panel.js
Return 'center' instead of undefined when on an RTL page.
Fixes #10536
=> fix(panel): correctly reverse x-position in RTL

src/components/select/select.js, src/components/select/select.spec.js
1. Add role="presentation" to the container divs so assistive technology
(primarily VoiceOver) to accurately count and announce "item 3 of 7".
https://www.w3.org/TR/wai-aria/roles#presentation
2. Only add aria-owns when the md-select element does not contain its
menu element in the DOM. This means when the select is opened, as
opening the select means the element, previously nestled within
md-select, gets appended to the end of the DOM.
3. Dynamically hide md-select-value with aria-hidden to get an accurate
item count for the md-select. This can't just be hidden all the time
because VoiceOver does not allow linear navigation into selects with no
visible options.
4. Move autoFocus call to after the select menu element is fully rendered
in order to properly focus the first item in the …
=> fix(select): A11y fixes allowing screen readers (VoiceOver) to read list item position

src/components/progressLinear/progress-linear-theme.scss
Style the buffer bar and dashed bar for color intention md-primary in progress-linear buffer mode
Fixes [#10078](https://github.com/angular/material/issues/10078)
=> fix(progress-linear-theme): add md-primary support to progress-linear (buffer mode)

src/components/dialog/dialog.js, src/components/dialog/dialog.spec.js
=> fix(dialog): generate `aria-label` with dialog title (if exists) when `.ariaLabel()` is not specified

src/components/tabs/js/tabsController.js, src/components/tabs/tabs.spec.js
As per the ARIA spec on tabs
(https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel, see "Keyboard
Interaction" section), LEFT ARROW should move the focus to the last tab
if it's currently on the first tab. RIGHT ARROW should move the focus to
the first tab if it's currently on the last tab. Previously, LEFT ARROW
stopped moving focus once it hit the first tab and RIGHT ARROW stopped
moving focus once it hit the last tab.
=> fix(tabs): allow right and left arrows to cycle through tabs

src/components/dialog/dialog.js, src/components/dialog/dialog.spec.js
Edit:
change how dialogs hide background elements to avoid hiding live regions, ensuring that an autocomplete inside a dialog will not have its live region aria-hidden
Fixes #10804
***********
Out of date:
add moveLiveRegion fn that moves an autocomplete's live region off document.body
and makes it a child of md-autocomplete. this prevents dialogs from
mistakenly hiding an autocomplete's live region
Fixes #10804
=> 	fix(dialog):prevent dialogs from hiding live regions

src/components/virtualRepeat/virtual-repeater.js
@jelbourn: Screen readers need the list items to exist as direct children of the list container itself, and these divs only make up structural (not semantic) aspects of the resulting DOM.
=> fix(virtual-repeater): Add role="presentation" to structural divs to fix screen reader interactions with virtual-repeater created lists.

src/core/services/gesture/gesture.js
* Fixes not being able to move the text cursor within and input on mobile.
* Fixes not being able to blur an input by tapping away on mobile.
Both of the issues were due to the click hijacking from the gesture service being too aggressive and preventing focus from shifting.
Fixes #10301.
Fixes #5365.
=> fix(gesture): unable to move text cursor and tap away on mobile

src/components/select/select.js
Hopefully fixed https://github.com/angular/material/issues/10828.
=> Fixed a non-closed <select>

docs/README.md
docs:watch script exists in package.json, so `npm run docs:watch` vs `npm run watch`
=> Quick update to documentation `npm run docs:watch`

src/components/select/select.js, src/components/select/select.spec.js
Fixes #10584.
`ngModel.$setPristine()` was executed each time the selected options changed.
=> fix(select multiple): set the element dirty when the selected options change

docs/README.md
The commit https://github.com/angular/material/pull/10845 renamed some commands and the documentation about building the documentation is inaccurate.
=> docs(readme): update npm script name

src/components/gridList/demoBasicUsage/styles.css, src/components/gridList/demoDynamicTiles/style.scss
Tested Safari Version: 11.0.2
Machine: Macbook Pro
Left: Safari, grid not responsive to browser resizing
Right: Chrome, behave as expected
=> fix(gridList): demo example responsiveness broken on Safari

src/components/list/list.js
Clickable list items containing the `ng-href` attribute currently can't be downloaded on click.
=> fix(list): don't strip download attribute from list items

src/components/datepicker/calendar.scss, src/components/datepicker/demoBasicUsage/index.html, src/components/datepicker/js/calendar.js, src/components/datepicker/js/calendar.spec.js, src/components/datepicker/js/calendarMonth.js, src/components/datepicker/js/calendarMonthBody.js, src/components/datepicker/js/calendarYear.js, src/components/datepicker/js/datepickerDirective.js
- Adds the ability to restrict users to a calendar view. For example, it's now possible to let users only select a month, instead of having to pick out a date within the month. This can be useful for cases like a credit card form, where the day of the month doesn't necessarily make sense.
- Fixes an issue where the year view wouldn't highlight the proper cell, if the model was changed externally and the date was different from the first day of the month.
Fixes #9260.
=> feat(datepicker): add the ability to restrict users to a calendar view

src/core/services/gesture/gesture.js
This was removed as part of this commit : https://github.com/angular/material/pull/9803
I think it was observed that isAndroid and isIos is not used anywhere else in material, so it was removed.
But the normal usages of $mdGesture would be broken after this commit , I mean a developer can't simply inject `$mdGesture` and use it as :
```javascript
if($mdGesture.isAndroid):{
this.suggestDownloadOurAndroidApp()
}
```
in our use case, after updating from material 1.1.1 to 1.1.5, a part of our app broke.
=> fix($mdGesture):reAdd isAndroid & isIos to $get

docs/app/partials/getting-started.tmpl.html
```
[ ] Bugfix
[ ] Feature
```
The anchor in the link doesn't work as it was renamed from angular to angularjs.
Issue Number: 
N/A
The link goes to bower-material and then scrolls down to the section of the readme for installing AngularJS Material.
```
[ ] Yes
[x] No
```
N/A
=> docs(getting-started): fix anchor in installing AngularJS Material link

src/components/panel/panel.js
`getBoundingClientRect()` will return a width of 0 in certain scenarios.
Retrieving the width through `clientWidth` will hold the desired width for the position calculation.
As this can be reversed for other situations, we take the max of both values.
Closes #10543
=> fix(panel): loosen up bounds assessment

docs/guides/MERGE_REQUESTS.md
```
[ ] Bugfix
[ ] Feature
```
The header formatting is broken due to a change in GitHub Markdown formatting.
Issue Number: 
N/A
The headers are displayed properly.
```
[ ] Yes
[x] No
```
N/A
=> docs(merge): fix formatting

scripts/test-versions.sh
```
[ ] Bugfix
[ ] Feature
```
Test "should assign bindings by $onInit for ES6 classes" fails on AngularJS 1.4.
Jenkins output: https://207.254.73.19/job/angular-material1-quarterly-build-versions-testing/871/console
Issue Number: 
Relates to #10977
Tests are only run against AngularJS 1.5, 1.6, and snapshot which lines up with our current TravisCI configuration.
```
[ ] Yes
[x] No
```
"should assign bindings by $onInit for ES6 classes" …
=> test: remove AngularJS 1.4 from test-versions.sh

docs/app/js/codepen.js
```
[ ] Bugfix
[ ] Feature
```
CodePens are generated with `module('MyApp',['ngMaterial',`. It's a minor issue but it always annoys me.
Issue Number: 
N/A
CodePens are generated with `module('MyApp', ['ngMaterial',`
```
[ ] Yes
[x] No
```
was `module('MyApp',['ngMaterial',`
now `module('MyApp', ['ngMaterial',`
=> docs(codepen): add missing space in module declaration

.github/CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
```
The contributing page is poorly formatted due to changes in GitHub's Markdown.
Issue Number: 
N/A
The contributing page is properly formatted.
```
[ ] Yes
[x] No
```
N/A
=> docs(contributing): fix Markdown formatting issues

src/components/datepicker/js/datepickerDirective.js, src/components/datepicker/js/datepickerDirective.spec.js
Formatter of model was instantiating a new Date object even when the value was already a Date object.
This is a performance improvement and also a convenient fix when the Date object caries some custom attributes.
=> fix(datepicker): keep reference of Date object

src/components/swipe/demoBasicUsage/index.html, src/components/swipe/demoBasicUsage/script.js, src/components/swipe/swipe.js
When using the `md-swipe-xxxx` events, if you pass the `$event` and try to access `$event.currentTarget` you get `null`.
I am saving a reference to the original `currentTarget` and passing it on here, via `$target` object so we can use it.
**Why do we even need `currentTarget` ?**  
Let's say you add the `md-swipe-right` directive to a div, and that div has a few child nodes. When the user swipes, the `$event.target` is the 'div' element the user swiped on, and not the 'div' element that we placed the `md-swipe-right` attribute on.
With other angular events (like 'on-click') we can get the div we want with `$event.currentTarget`, but this does't work for 'swipe' events.
This is basically what is stated here (but not for swipe events) : …
=> feat(swipe): allow accessing the original currentTarget

src/components/tooltip/tooltip.js
Providing the initial origin through the `panelClass` of the panel is not the right approach. `mdPanel` remembers the original panel configuration and the provided `panelClass` and will restore it when the element is reused. This results in the new origin and the default (bottom) origin style to be placed on the element at the same time.
Fixes #10405
```
[X] Bugfix
[ ] Feature
```
When the direction of a tooltip is changed, the resulting …
=> fix(tooltip): changing direction causes invalid position

CHANGELOG.md
```
[ ] Bugfix
[ ] Feature
```
1.1.6 contributors got lost with 1.1.7 release.
Issue Number: 
N/A
1.1.6 contributors are added back in.
```
[ ] Yes
[x] No
```
N/A
=> docs(changelog): re-add contributors for 1.1.6 release

src/components/panel/panel.js, src/components/panel/panel.spec.js
Allows for numbers to be pass to the `withOffsetX` and `withOffsetY` methods, assuming that the units are pixels.
Fixes #9604.
CC @ErinCoughlan @bradrich
=> fix(panel): allow numbers in offset methods

src/components/button/button.scss
Webkit has a rendering bug with child elements whos parent uses a
rounded corner. In this case, this is a ripple on a rounded button.
To circumvent this issue, we applied a 1x1 PNG image mask on the
ripple element.
The image mask is causing issues with Chrome rendering opaque under
certain conditions. An image mask is only needed for Safari 8, which
is no longer supported. Instead we will just Safari and Chrome to
use a compositing layer by forcing an empty Z-axis translation.
* Inherit border radius from buttons
* Remove image mask CSS
* Use translateZ to force webkit to create a compositing layer
Fixes #9154, #10086
References:
https://bugs.webkit.org/show_bug.cgi?id=30475
=> fix(button): fix rendering issue with borders and webkit browsers

src/components/dialog/dialog.js, src/components/dialog/dialog.spec.js
When using the `required` method in `$mdDialog.prompt()` the user is able to hide the dialog by hitting the `ENTER` key even when the input is empty, defeating the implication of a required input. This PR adds a check on keypress to ensure if the dialog is prompt **and** is required that a value is present.
* Adds missing documentation for `required` method.
* Adds missing test for `required` method.
Fixes #10953 
codepen with issue reproducible https://codepen.io/eknowles/pen/JOpgrq
=> fix(dialog): fix prompt closing on ENTER key when input is required and empty

src/components/menu/js/menuServiceProvider.js, src/components/menu/menu.spec.js
```
[x] Bugfix
[ ] Feature
```
Pressing tab inside of a menu panel (`md-menu-content`) can cause the focus to escape the panel and move to other parts of the page (with the menu panel still open).
Issue Number: 
Fixes #11123
Use only arrow keys to navigate menus (not tabs).
Resolve issue where tab can escape the panel by closing the menu when the `TAB` keyCode is detected.
```
[ ] Yes
[x] No
```
N/A
=> fix(menu): close menu on tab

src/components/menu/js/menuDirective.js, src/components/menu/menu.spec.js
Fixes misbehavior from #10198
```
[x] Bugfix
[ ] Feature
```
Issue Number: #10540
```
[ ] Yes
[x] No
```
=> fix(md-menu): allow nested md-menu-content again

src/components/input/input.js, src/components/input/input.spec.js
Eliminate race condition that causes a blurred input with md-select-on-focus from being re-selected.
When there are two inputs with md-select-on-focus this can result in an infinite loop where focus
moves back and forth between the two elements.
```
[x] Bugfix
[ ] Feature
```
md-select-on-focus will re-focus an input, even if it is no longer the active element on the page in order to select the input text. The most bizarre behaviour that …
=> fix(input): prevent md-select-on-focus from refocusing blurred input

src/components/virtualRepeat/virtual-repeater.js
```
[ ] Bugfix
[ ] Feature
```
The rendered bullets are messed up with the text and bullets on different lines. Typo in a sentence.
Issue Number: 
N/A
Formatting and typos fixed.
```
[ ] Yes
[x] No
```
N/A
=> docs(virtualRepeat): bullet format issue, typo

src/components/datepicker/demoValidations/index.html
- [n/a] Tests for the changes have been added (for bug fixes / features)
- [n/a] Docs have been added / updated (for bug fixes / features)
Documentation changes 
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #11007 
```
[ ] Yes
[x] No
```
Closes #11007
=> docs(datepicker): follow Material Design guidelines for messages

src/components/panel/panel.js
```
[ ] Bugfix
[ ] Feature
```
The $mdPanel service docs include references to two functions that don't exist. The $mdPanel service docs aren't connected in any way to the Panel Type docs that they reference.
Issue Number: 
Closes #11146
The $mdPanel service docs reference the proper functions. The $mdPanel service docs link to the Panel Type docs that they reference.
```
[ ] Yes
[x] No
```
add links for the types used with $mdPanel
show …
=> docs(panel): fix invalid example. improve docs.

src/components/sidenav/sidenav.js
```
[ ] Bugfix
[ ] Feature
```
Using the example from the docs will always throw an exception.
Issue Number: 
Fixes #10863
The example in the docs will now properly register and execute the provided onClose() callback when the sidenav is about to be closed.
```
[ ] Yes
[x] No
```
N/A
=> docs(sidenav): fix onClose() example

src/components/panel/panel.js
```
[x] Bugfix
[ ] Feature
```
When destroying md-tooltip the callback `onDomAdded` remained attached and was causing a memory leak.
Issue Number: 
https://github.com/angular/material/issues/11133
Added 4 lines with setting all 4 callbacks to null in `MdPanelRef.prototype.destroy`.
From my tests this will clear the memory leak.
```
[ ] Yes
[x] No
```
=> fix(panel): memory leak on destroy

src/components/chips/chips.spec.js, src/components/chips/demoValidation/index.html, src/components/chips/demoValidation/script.js, src/components/chips/demoValidation/style.css, src/components/chips/js/chipsController.js, src/components/chips/js/chipsDirective.js
```
[ ] Bugfix
[x] Feature
[x] Other... Please describe: In my opinion it is more a bug than a feature because this should be a default behavior
```
ng-required not working with md-chips
Issue Number: #11124
ng-required works with md-chips
```
[ ] Yes
[x] No (I would say no)
```
Pull-Request is mainly a follow-up from #8034. I had the same idea in how to add this but found this not followed/merged pull-request by @Emeegeemee .
So nearly everything of the code got …
=> feat(md-chips): added validation for ng-required

src/components/input/input.js, src/components/input/input.spec.js
```
[x] Bugfix
[ ] Feature
```
When an input has an md-maxlength attribute and an initial value longer than this maxlength, no error is triggered until the input value is changed.
Issue Number: #10320 
When an input has an md-maxlength attribute and an initial value longer than this maxlength, an error is triggered at initialization. 
Note that the error message is not shown at initialization but only when the focus leave the input (without …
=> fix(input): make md-maxlength validation happen on initialization

src/components/chips/js/chipsController.js
```
[x] Bugfix
[ ] Feature
```
Using 0 for `md-chip-append-delay` causes the directive to convert 0 to 300ms due to a bad if check. This is a regression caused by the chips a11y updates in 1.1.2.
Issue Number: 
Fixes #10408
Setting `md-chip-append-delay` to 0 now removes the delay completely as expected.
```
[ ] Yes
[x] No
```
Thanks to @mgol for the report and corrected code snippet.
=> fix(chips): md-chip-append-delay of 0 does not get converted to 300

.jshintrc, src/components/autocomplete/demoInsideDialog/script.js, src/components/autocomplete/js/autocompleteDirective.js, src/components/chips/demoContactChips/script.js, src/components/chips/demoCustomInputs/script.js, src/components/chips/js/chipDirective.js, src/components/chips/js/chipsDirective.js, src/components/colors/demoBasicUsage/script.js, src/components/colors/demoThemePicker/script.js, src/components/gridList/grid-list.js, src/components/icon/demoLoadSvgIconsFromUrl/script.js, src/components/input/input.js, src/components/menu/js/menuServiceProvider.js, src/components/navBar/navBar.js, src/components/panel/demoGroups/script.js, src/components/panel/panel.js, src/components/tabs/js/tabsController.js, src/components/toast/toast.js, src/components/truncate/truncate.js, src/components/virtualRepeat/virtual-repeater.js, src/core/services/compiler/compiler.js, src/core/util/util.js
```
[x] Bugfix
[ ] Feature
```
Issue Number: 9153
```
[ ] Yes
[x] No
```
=> Fix jshint warnings

src/components/dialog/dialog.js
What kind of change does this PR introduce? 
Changes docs. Corrects and adds back resolve property doc in the $mdDialog.show() parameters list.
```
[ ] Bugfix
[ ] Feature
```
Currently the resolve property is not listed or described in the $mdDialog.show(optionsOrPreset) parameters documentation. Refer to issue #7400. But as suggested in [comments](https://github.com/angular/material/issues/7400#issuecomment-289870601), slight documentation correction was required for the property. …
=> docs(dialog): correct and add back resolve property

src/components/dialog/dialog.js, src/components/dialog/dialog.spec.js
```
[x] Bugfix
[ ] Feature
```
Currently when you display an mdDialog, the directive tries to see if an md-theme controller exists from where the mdDialog was propogated. The directive then adds an md-theme attrubute to a newly created div inside of md-dialog. The directive does this regardless of whether there is an inherited theme or not.
This is an issue because the md-theme gets set to an empty string and when attempting to use …
=> fix(dialog) md-colors breaking inside of  dialogs

src/components/navBar/demoBasicUsage/index.html, src/components/navBar/navBar.js, src/components/navBar/navBar.scss, src/components/navBar/navBar.spec.js
Resubmitting @maxjoehnk PR #10202 
* Originally developed by: @maxjoehnk - made a small change, not using $mdUtils which was used by @maxjoehnk in his version. I'm just resubmitting
* Add disabled attribute to navitem
* Update demo to showcase ng-disabled and disabled usage
* Add tests
My Additions: 
* disabled style (reduced opacity and not-allowed cursor) 
fixes #9667
=> feat(navBar): add disabled attribute

src/components/bottomSheet/bottom-sheet.js, src/components/bottomSheet/bottom-sheet.spec.js
- Adds the `isLockedOpen` option to the bottom sheet service, allowing users to disable all non-programmatic ways of closing a bottom sheet.
- Cleans up some redundant logic in the mdBottomSheet service.
- Cleans up the bottom sheet unit test setup.
Fixes #9084.
=> feat(bottom-sheet): add isLockedOpen option; general cleanup

docs/app/css/style.css, docs/config/template/index.template.html
```
[ ] Bugfix
[ ] Feature
```
The docs site uses the Angular (v2+) logo instead of the AngularJS (v1) logo. This may be confusing to developers. This could be part of the confusion that leads a lot of Angular Material issues to be misfiled in this repository.
Issue Number: 
Relates to #11173.
The docs site uses the AngularJS (v1) logo.
```
[ ] Yes
[x] No
```
Before:
After:
=> docs: use AngularJS logo instead of Angular logo

src/components/toast/toast.scss
In the component md-toast the property "direction" is set to "row". It seems like it's intended to use "flex-direction", as "row" is not a valid value for the property direction, which should indicate the direction of text. 
This doesn't change the behaviour of md-toast, just cleaning up a small typo :)
```
[x] Bugfix
[ ] Feature
```
The css property "direction" is set to the value of "row" in the md-toast component.
In the component md-toast the property "direction" is set to "row". It seems like it's …
=> fix(toast): update style direction to flex-direction

src/components/chips/chips.spec.js, src/components/chips/demoBasicUsage/index.html, src/components/chips/demoBasicUsage/script.js, src/components/chips/demoContactChips/index.html, src/components/chips/demoContactChips/script.js, src/components/chips/js/chipsController.js, src/components/chips/js/chipsDirective.js, src/components/chips/js/contactChipsDirective.js
```
[ ] Bugfix
[x] Feature
```
`ng-change` is not supported for `md-chips` or `md-contact-chips`.
Issue Number: 
#11161 #3857 
`ng-change` is supported on `md-chips`. It will be triggered on chip addition/removal.
```
[ ] Yes
[x] No
```
Closes #11161 and #3857
=> feat(chips): trigger ng-change on chip addition/removal

src/components/button/button.js, src/components/navBar/navBar.js, src/components/navBar/navBar.spec.js
```
[x] Bugfix
[ ] Feature
```
The initial value of the `disabled` attribute is not read or respected. It is only read when it changes via `MutationObserver` or `attrs.$observe`.
Issue Number: 
Closes #11172. Relates to #10688.
The initial value of the `disabled` attribute is now read and respected.
```
[ ] Yes
[x] No
```
remove issues with tests that hid this bug
improve docs for nav-bar and nav-item
add ng-blur to button docs as its used …
=> fix(nav-bar): initial disabled state is now respected

src/components/radioButton/radio-button.js
```
[ ] Bugfix
[ ] Feature
```
There are some duplicate entries, an out of date link, and confusing/inconsistent content.
Issue Number: 
Relates to #6225.
remove out of date reference and link to Material Design Spec
remove duplicate ng-model docs for md-radio-group
make it clear that only one of value and ng-value can be used
use consistent md-no-ink messaging
```
[ ] Yes
[x] No
```
N/A
=> docs(radio-button): update and clean up

src/components/bottomSheet/bottom-sheet.js
Since `$mdBottomSheet`, just like `$mdDialog`, is implemented through `$$interimElement`,
it supports the definition of presets as well.
Closes #10942
```
[ ] Bugfix
[ ] Feature
```
Issue Number: 
#10942
```
[ ] Yes
[x] No
```
=> docs(bottom-sheet): add documentation for `addPreset`

src/components/dialog/dialog.js
```
[x] Bugfix
[ ] Feature
```
From https://github.com/angular/material/issues/9627#issue-177509966:
> mdDialog causes thread blocking issues when traversing large DOM trees (in this case, SharePoint 2013) using the walkDOM(element) method. Thread is blocked for approximately 30-40 seconds while aria-hidden attributes are applied.
Issue Number: 
Closes #9627.
From https://github.com/angular/material/issues/9627#issue-177509966:
> mdDialog …
=> fix(dialog): thread blocks during large DOM traversals

src/components/sidenav/demoBasicUsage/script.js, src/components/sidenav/demoDisableCloseEvents/index.html, src/components/sidenav/demoDisableCloseEvents/script.js, src/components/sidenav/sidenav.js, src/components/sidenav/sidenav.spec.js
Add a property to disable the click and Escape button actions to prevent the user
from closing the sidenav but still showing the backdrop.
```
[ ] Bugfix
[x] Feature
```
Issue Number: 
#4699
Now it is possible to add a new attribute called `md-disable-click-escape-events` to prevent the sidenav from closing when clicking on the backdrop or pressing `ESC`. If you add it to a md-sidenav it will still show the backdrop but the user won't be …
=> feat(sidenav): add disable click and escape event

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/demoCustomTemplate/index.html, src/components/autocomplete/demoCustomTemplate/style.global.css, src/components/autocomplete/js/autocompleteDirective.js
```
[ ] Bugfix
[x] Feature
```
`md-menu-class` allows for customizing styling of the individual autocomplete options in the dropdown panel. However, it does not allow for customizing the parent container of the options. This means that things like changing the width of the panel is not possible without globally styling the width of all autocomplete dropdowns in the same way.
Issue Number: 
Fixes #8393. Closes #8397.
this allows control over …
=> feat(autocomplete): add md-menu-container-class for styling

src/core/services/theming/theming.js
```
[ ] Bugfix
[ ] Feature
```
The APIs were covered some in the guide, but not in the service docs.
The docs were inconsistent in descriptions and formatting.
Issue Number: 
Relates to #2965. Relates to #9475. Relates to #9476.
Relates to #10458. Relates to #10458.
Missing documentation exists.
Update existing docs for consistency.
```
[ ] Yes
[d] No
```
N/A
=> docs(mdThemingProvider): add missing documentation

src/components/slider/slider.js, src/components/slider/slider.spec.js
Implemented check for out of sync state between model and view value in Slider, which occurred when both model and either min and/or max values were updated within the same digest cycle. This is due to the $ngModelCtrl formatters kicking in and validating the view value before the Slider directive $observer on the min and max attributes could fire.
Fixes angular/material#9125
=> fix(slider): fixed incorrect update of model and min/max values in same digest cycle

src/components/datepicker/calendar-theme.scss, src/components/datepicker/datePicker-theme.scss
```
[x] Bugfix
[ ] Feature
```
The datepicker calendar panel is always using light mode hues even when the theme is dark mode.
Issue Number: 
#11200
The datepicker calendar panel use dark mode hues when the theme is set to dark mode.
```
[ ] Yes
[x] No
```
Before dark mode:
After dark mode:
After light mode:
=> fix(datepicker): calendar panel theme supports dark mode

src/components/slider/demoBasicUsage/index.html, src/components/slider/demoBasicUsage/script.js, src/components/slider/slider.js
```
[x] Bugfix
[ ] Feature
```
numeric inputs cut off on Firefox and Edge
empty docs for md-slider-container
needless flex attributes in md-slider-containers in demo
broken rating binding in demo
old material spec URL for md-slider
Issue Number: 
Fixes #9559. Fixes #10909.
numeric inputs no longer cut off on Firefox and Edge
fix empty docs for md-slider-container
remove needless flex attributes from md-slider-containers in demo
fix missing …
=> fix(slider-container): numeric inputs cut off on Firefox and Edge

src/components/autocomplete/autocomplete-theme.scss
```
[x] Bugfix
[ ] Feature
```
The autocomplete panel is always using light mode hues even when the theme is dark mode.
Issue Number: 
#11202
The autocomplete panel use dark mode hues when the theme is set to dark mode.
```
[ ] Yes
[x] No
```
Before:
After:
=> fix(autocomplete): autocomplete panel theme supports dark mode

src/components/panel/demoGroups/script.js, src/components/panel/demoPanelProvider/script.js, src/components/panel/panel.js
```
[x] Bugfix
[ ] Feature
```
Panel demos are using $event.srcElement which is not supported by Firefox browsers.
Issue Number: #11035
Panel demos are now using $event.target
```
[ ] Yes
[x] No
```
=> fix(panel): use $event.target instead of $event.srcElement for Firefox compatibility

src/components/autocomplete/js/autocompleteDirective.js
```
[ ] Bugfix
[ ] Feature
```
The link to the autocomplete spec was broken and the description of the clear button options was out of date or missing details.
Issue Number: 
Relates to #1710. Relates to #10603.
Fixed the link to the spec and added an additional link.
Clarified the clear button API and the change in 1.1.5 regarding disabled autocomplete components.
```
[ ] Yes
[x] No
```
N/A
=> docs(autocomplete): update and clarify the behavior of the clear button

src/core/services/layout/layout-attributes.scss, src/core/services/layout/layout.scss, src/core/style/layout.scss, src/core/style/structure.scss, src/core/style/typography.scss
```
[x] Bugfix
[ ] Feature
```
Some flex directives don't work when on a child of `layout="column"` or `layout="row"`. This includes `flex="0"`, `flex="33"`, `flex="66"`, `flex="100"`.
Issue Number: 
Fixes #9546
`flex="0"`, `flex="33"`, `flex="66"`, `flex="100"` now behave properly when applied to an element that is a child of an element with `layout="column"` or `layout="row"`.
```
[ ] Yes
[x] No
```
Relates to and includes contents of PR …
=> fix(layout): some flex directives don't work when on a child of layout="column" or layout="row"

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/autocompleteController.js
```
[x] Bugfix
[ ] Feature
```
Autocomplete menu opens and shows options when `readonly` is set to `true`. This could sometimes happen when no value was selected.
Issue Number: 
Fixes #11231
The menu is never shown when `readonly` is set to `true`.
```
[ ] Yes
[x] No
```
N/A
=> fix(autocomplete): don't show the menu panel when readonly

src/core/services/gesture/gesture.js
```
[ ] Bugfix
[x] Feature
```
There is currently no way to disable gestures across an entire application. This can be useful when memory leak (detached DOM nodes) or other performance issues related to gestures become a problem.
Issue Number: 
Fixes #10884. Relates to #10885.
It is now possible to disable all of the gesture detection in an AngularJS Material app.
```js
app
.module('myApp',['ngMaterial'])
.config(['$mdGestureProvider', …
```
=> feat(gestures): add ability to disable all gestures for perf

src/components/select/demoSelectedText/index.html, src/components/select/demoSelectedText/script.js, src/components/select/select-theme.scss
```
[x] Bugfix
[ ] Feature
```
The select's option panel is always using light mode hues even when the theme is dark mode.
Issue Number: 
Fixes #3379.
The select's option panel use dark mode hues when the theme is set to dark mode.
```
[ ] Yes
[x] No
```
I'm going to try and presubmit this for 1.1.9, but I understand that this might trigger some screenshot failures in Google apps. If that happens, we'll need to evaluate pushing this to …
=> fix(select): options panel theme supports dark mode

src/components/menu/menu-theme.scss
Closes #11199
```
[x] Bugfix
[ ] Feature
```
The `md-menu` panel is always using light mode hues even when the theme is dark mode.
Issue Number: 
Fixes #11199.
The `md-menu` panel use dark mode hues when the theme is set to dark mode.
```
[ ] Yes
[x] No
```
Dark before:
Dark after:
Light before:
Light after:
=> fix(menu): md-menu panel theme supports dark mode

src/components/autocomplete/autocomplete-theme.scss, src/components/autocomplete/autocomplete.scss
```
[x] Bugfix
[ ] Feature
```
There is an a11y issue where the difference between highlighted text is too small (unnoticeable to many people without perfect eyesight or high end monitors).
Additionally, the currently highlight styling does not align with the Material Design spec which was changed from lighter text to bold text for highlight in autocomplete/search.
Issue Number: 
Fixes #10060
Follow the updated spec by highlighting text in …
=> fix(autocomplete): align highlight style with spec

src/core/services/compiler/compiler.js
```
[ ] Bugfix
[ ] Feature
```
The docs site is missing the details about `$mdCompilerProvider.respectPreAssignBindingsEnabled`. The feature was added as part of https://github.com/angular/material/issues/10016 and PR https://github.com/angular/material/pull/10726. These docs can only be found in [the code comments](https://github.com/angular/material/blob/master/src/core/services/compiler/compiler.js#L84-L167) or …
=> docs(mdCompilerProvider): add respectPreAssignBindingsEnabled docs

src/components/menuBar/menu-bar-theme.scss
Closes #11238
```
[x] Bugfix
[ ] Feature
```
The `md-menu-bar` panel is partially using light mode hues in dark mode.
Issue Number:
Fixes #11238.
The `md-menu-bar` panel use dark mode hues when the theme is set to dark mode.
```
[ ] Yes
[x] No
```
dark mode before:
dark mode after:
light mode before:
light mode after:
=> fix(menuBar): md-menu-bar panel theme supports dark mode

src/components/navBar/navBar-theme.scss
Closes #11268
```
[x] Bugfix
```
https://material.angularjs.org/HEAD/demo/navBar
color of disabled `button._md-nav-button` is the same as normal enabled button: `button.md-unselected`
Issue Number: 
#11268
Color of `disabled` button should have value: `'{{foreground-3}}'`
```
[ ] Yes
[x] No
```
Before:
After:
=> fix(navBar): missing [disabled] scss selector

src/components/autocomplete/demoBasicUsage/script.js, src/components/autocomplete/demoCustomTemplate/script.js, src/components/autocomplete/demoFloatingLabel/script.js, src/components/autocomplete/demoInsideDialog/script.js, src/components/chips/chips.spec.js, src/components/chips/contact-chips.spec.js, src/components/chips/demoContactChips/index.html, src/components/chips/demoContactChips/script.js, src/components/chips/demoCustomInputs/script.js, src/components/chips/js/chipsController.js, src/components/chips/js/chipsDirective.js, src/components/chips/js/contactChipsController.js, src/components/chips/js/contactChipsDirective.js
```
[x] Bugfix
```
There was a breaking change in 1.1.9 related to the enhancement to support `ng-change` on `md-chips`. This was introduced in #11166 where the passed in model and the `items` Array is replaced via `Array.slice`. This appears to have led to the issues listed below and may be related to https://github.com/angular/material/issues/11218 as well.
Issue Number: 
Fixes #11304. Fixes #11301.
- fix issue where view …
=> fix(chips): regression where chips model gets out of sync with view

docs/app/css/style.css, docs/app/partials/layout-children.tmpl.html, src/core/style/layout.scss
```
[x] Bugfix
```
Layout CSS size increased by 78 KB in 1.1.9.
Issue Number: 
Fixes #11000. Relates to #9546.
Reduces unminified layout CSS size by ~77KB by reverting some of #11247.
Adds support for `flex="33"` and `flex="66"` outside of a `layout` attribute just like all of the other flex directives like 0, 5, ... 100.
```
[ ] Yes
[x] No
```
Reducing this size is critical for syncing the latest master into Google.
=> fix(layout): reduce layout size and fix flex 33/66 outside of layout containers

src/components/select/select.js, src/components/select/select.spec.js
```
[ ] Bugfix
```
The docs are misleading and cause developers to think that something like `multiple="ctrl.isMultiple`" can be used. In fact, only the existence of the attribute matters. This follows a common pattern used in AngularJS Material APIs.
Issue Number: 
Closes #3068
- Align the `multiple` docs with the actual behavior of the API
- fix syntax ordering error with `md-no-asterisk` docs
- remove instances of …
=> docs(select): clarify behavior of multiple attribute

src/components/select/select.js, src/components/select/select.spec.js
Fixes #11294.
```
[x] Bugfix
```
Issue Number: #11294 
KeyboardEvent.key is used instead of KeyboardEvent.keyCode when getting the key pressed, for auto-completion.
```
[ ] Yes
[x] No
```
=> fix(select): use KeyboardEvent.key instead of KeyboardEvent.keyCode for auto-completion

src/components/chips/demoBasicUsage/index.html, src/components/chips/demoBasicUsage/readme.html, src/components/chips/demoBasicUsage/script.js, src/components/chips/js/chipsController.js
```
[x] Bugfix
```
As described by @caseyjhol, "With `md-add-on-blur` enabled, clicking outside `mdChips` or selecting another input element results in the previously focused `mdChips` being highlighted again. This is especially jarring on a mobile device (e.g. type in some text for the chip, scroll down to the next form element, select it, and then the chip is added but `mdChips` is then scrolled back into position and …
=> fix(chips): unwanted re-focus of last chip after blur

src/components/chips/js/chipsController.js, src/components/chips/js/chipsDirective.js, src/core/services/interimElement/interimElement.js
```
[x] Bugfix
[ ] Feature
```
Clicking at the end of `md-chips` or between `md-chip`s no longer focuses the chips input after 1.1.2. Many developers have complained that this creates poor UX and that their users have complained.
Issue Number: 
#10344
Clicking at the end of `md-chips` or between `md-chip`s focuses the chips input.
```
[ ] Yes
[x] No
```
This solves a regression introduced in 1.1.2.
Fixes #10344
=> fix(chips): improve ability to receive focus on click

README.md, docs/app/css/style.css, docs/app/partials/home.tmpl.html, package-lock.json, package.json, scripts/gulp-utils.js
```
[x] Bugfix
```
We've long claimed support for n-1 browser versions, but that hasn't been kept up to date. As a result, we've got our autoprefixer settings generating CSS for Safari 8, 9, 10.0, and some dead browsers like Blackberry, Opera Mobile 12.1, and IE 10. This significantly bloats our CSS.
With our old settings we only supported 86.6% of the global browser market.
Issue Number: 
Fixes #9396
- Unminified CSS …
=> fix(css): remove bloat from autoprefixing of unsupported browsers

src/components/input/input.js, src/components/input/input.spec.js
Closes #11329
```
[x] Bugfix
```
Using md-maxlength="MAX" on an input field that initializes to some value of length > "MAX", the md-maxlength validation does not happen, and the input field is considered valid.
Issue Number: #11329 
The validation now happens with specified value and error is detected
```
[ ] Yes
[x] No
```
=> fix(input): make md-maxlength validation happen on initialization with interpolated value

src/components/select/select.scss
Closes #11312
```
[x] Bugfix
```
If a `md-select` control has a custom validation on it using `$setValidity(false)`, the required * will show on the chosen value even though the value is populated.
Issue Number: 11312
The required * will show on the value only if no value is chosen. It will still display on placeholder.
```
[ ] Yes
[x] No
```
=> fix(select): display asterisk on label only if empty

src/components/chips/js/chipsController.js, src/components/navBar/navBar.js, src/components/sidenav/sidenav.js
```
[ ] Bugfix
```
Issue Number: 
Relates to https://github.com/babel/minify/issues/878
Relates to https://github.com/angular/material/pull/11165
- avoid creating variables in a block when they are used outside
- instead create them directly in the function block they are hoisted to
- fix typos
- fix lint issues and whitespace
```
[ ] Yes
[x] No
```
=> fix(sidenav): refactor syntax to work around issue in babel-minify

gulp/util.js
```
[ ] Bugfix
```
The `gulp-uglify` update broke the `build-js` task due to a breaking change to the `gulp-uglify` API.
Issue Number: 
N/A
Fixed build broken by `gulp-uglify` update.
```
[ ] Yes
[x] No
```
Example of a broken build: https://travis-ci.org/angular/material/jobs/401935217
=> build(gulp-uglify): use new syntax for preserving some comments

src/components/chips/contact-chips.spec.js, src/components/chips/demoContactChips/index.html, src/components/chips/demoContactChips/script.js, src/components/chips/js/contactChipsController.js, src/components/chips/js/contactChipsDirective.js
Add basic support for md-separator-keys. The ENTER and TAB keys trigger
separation by default through md-autocomplete regardless of what
additional key codes are user defined.
Implements #6097, continuation of #6127 with the addition of unit tests requested.
=> feat(contactChips): add basic support for md-separator-keys

src/components/chips/js/chipController.js, src/components/chips/js/chipDirective.js, src/components/chips/js/chipsDirective.js, src/core/util/util.js
```
[x] Bugfix
```
Pressing the arrow keys, clicking the mouse, or pressing the backspace key in edit mode would cause the chips to become unresponsive or leave an empty chip behind.
Issue Number: 
Fixes #11322. Relates to #11323.
- Navigation through the chip content text with arrow keys and the mouse is now supported.
- Clearing the chip content text and writing new text now works as expected.
- Backspace key works as …
=> fix(chips): editing chips works again

LICENSE, docs/app/js/codepen.js, docs/app/partials/license.tmpl.html
```
[ ] Bugfix
```
Copyright and licenses use out of date Google Inc.
Issue Number: 
Relates to #11367
- Use new Google LLC name
- change to https as well
- update years in licenses
```
[ ] Yes
[x] No
```
=> docs: change to LLC instead of Inc. in Copyright and licenses

src/components/bottomSheet/bottom-sheet-theme.scss, src/components/bottomSheet/demoBasicUsage/bottom-sheet-list-template.html, src/components/bottomSheet/demoBasicUsage/style.css
```
[x] Bugfix
```
See Before screenshots below.
Issue Number: 
N/A
See After screenshots below.
```
[ ] Yes
[x] No
```
=> fix(bottom-sheet): component theme now supports dark mode

docs/app/css/style.css, docs/app/js/app.js, docs/config/template/index.template.html, src/components/button/demoBasicUsage/index.html, src/components/button/demoBasicUsage/script.js, src/components/button/demoBasicUsage/style.css, src/components/chips/demoCustomInputs/style.css, src/components/tabs/demoDynamicHeight/style.scss, src/components/tabs/demoDynamicTabs/style.scss, src/components/tabs/demoStaticTabs/index.html, src/components/tabs/demoStaticTabs/style.scss, src/components/whiteframe/demoBasicClassUsage/style.css, src/components/whiteframe/demoDirectiveAttributeUsage/style.css, src/components/whiteframe/demoDirectiveInterpolation/style.css
```
[ ] Bugfix
```
Button, chips, whiteframe, and tabs demos are significantly broken in dark mode.
This makes testing theme or component changes in dark mode more difficult.
Issue Number: 
Relates to https://github.com/angular/material/pull/11376
- better support for dark mode in docs and demos
- style anchors to be more readable in dark mode
- fix site-toolbar in dark mode and remove unused styles
- fix supported browsers …
=> docs: better support for dark mode in docs and demos

src/components/input/input-animations.spec.js, src/components/input/input.js
There is no requirement to include the messages in case of an error.
Highlighting the field can be enough.
Fixes #10461
```
[x] Bugfix
```
At the moment warning are displayed in the console when ng-messages are not specified for the input field.
Issue Number:
Relates to #10461 
Relates to #9468
The warnings are not generated as it is not required to include the error messages.
The original fix for #9468 is still in place. …
=> fix(input): remove unnecessary warnings when ng-messages not provided

src/components/tabs/js/tabsController.js
```
[ ] Bugfix
```
The `MdTabsController` initializes `var elements = getElements()` at the top of the controller and again in `setupTabsController ()` but that `elements` variable is no longer referenced as all of the code has been updated to call `getElements()` each time instead.
Issue Number: 
Fixes #11377 
Remove this unused and unreferenced variable to avoid extra DOM lookups.
```
[ ] Yes
[x] No
```
=> perf(tabs): remove unreferenced elements variable from TabsController

src/components/select/select-theme.scss
Closes #9592
```
[x] Bugfix
```
`mdSelect` inside an `md-input-container` does not respect theming classes (md-accent for example)
Issue Number: 
#9592
`mdSelect` will behave like `input`, `mdDatepicker` and `textarea` inside an input container and use the theme class set on the input container.
```
[ ] Yes
[x] No
```
=> fix(select): theming issues with md-select-value

src/components/tabs/js/tabDirective.js, src/components/tabs/js/tabsController.js, src/components/tabs/js/tabsDirective.js
```
[x] Bugfix
```
`md-center-tabs` causes constant 30-50% CPU usage due to indefinite execution of `updateInkBarStyles()`;
Issue Number: 
Fixes #9690. Fixes #6375.
- make updateInkBarStyles() a noop if md-no-ink-bar is set
- remove md-no-ink docs as the feature does not exist
- clean up md-tab docs
- add JSDoc and improve comments in TabsController
- add TODOs for min/max widths that no longer match the latest MD spec
- …
=> fix(tabs): md-center-tabs causes in high CPU usage

src/components/list/list.scss
when using an md-3-line list item, use the mixin workaround for ie11 flexbug https://github.com/philipwalton/flexbugs#flexbug-3
Fixes #11177
```
[x] Bugfix
```
Currently in IE11, md-list-item content vertical alignment can break if the md-list-item has a click event applied to it.
Issue Number: #11177
Now the alignment will be correct in IE11. This is accomplished by wrapping the applied min-height in the …
=> fix(list): account for IE11 bug with flexbox and min-height

src/components/tabs/js/tabsDirective.js
the visual highlighting of focused tabs was not functioning
Fixes #11384
```
[x] Bugfix
```
Currently when tabbing to an md-tab, there is no visual indication of focus.
This was happening because the md-dummy tab used to track has-focus on $mdTabsCtrl with ng-focus, but this was removed in [this](https://github.com/angular/material/commit/072f8328391c884b7ebc1ef49f4dc3e6c02e636c) commit
Issue Number: #11384
Now when tabbing …
=> fix(tabs): show a visual indication of tab focus

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/demoBasicUsage/index.html, src/components/autocomplete/js/autocompleteController.js, src/components/autocomplete/js/autocompleteDirective.js
```
[x] Bugfix
```
When selecting an item from the dropdown, screen readers do not notify the user that a selection was made.
Issue Number: 
Fixes #10837
- announce when an item is selected from the dropdown
- make sure that this message can be overridden in non-English locales
- fix some lint warnings and style issues
- add and fix JSDoc
```
[ ] Yes
[x] No
```
=> fix(autocomplete): announce when an item is selected from the dropdown

src/components/tabs/js/tabsController.js, src/components/tabs/js/tabsDirective.js
```
[ ] Bugfix
```
No guidance is given by AngularJS Material or screen readers on how users should navigate between tabs. It is documented in [WAI-ARIA Authoring Practices for Tab Panel](https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel) but many users are not familiar with this.
Issue Number: 
Fixes #10895
provide guidance on how to navigate between tabs
make sure that this message can be overridden in non-English …
=> fix(tabs): provide guidance on how to navigate between tabs

src/components/input/input.js
```
[x] Bugfix
```
Input placeholders appeared in screen reader button accessibility trees as interactive elements due to ng-aria.
Issue Number: 
Fixes #11293
Input placeholders no longer appear in screen reader button accessibility trees as interactive elements.
```
[ ] Yes
[x] No
```
Verified fix in this [CodePen](https://codepen.io/Splaktar/pen/ZjwjOv?editors=1010#0)
=> fix(input): remove placeholder from button accessibility tree

src/components/autocomplete/demoBasicUsage/index.html, src/components/autocomplete/demoFloatingLabel/index.html, src/components/autocomplete/js/autocompleteController.js, src/components/autocomplete/js/autocompleteDirective.js
```
[ ] Bugfix
```
Applying `aria-describedby` to an `md-autocomplete` would not cause the attribute to be forwarded down to the native `input` element. Thus it would have no effect.
Issue Number: 
Fixes #11004
Applying `aria-describedby` to an `md-autocomplete` causes the attribute to be forwarded down to the native `input` element. This causes the contents of all elements with IDs in the list to be read after the …
=> feat(autocomplete): add support for aria-describedby

src/components/autocomplete/js/autocompleteController.js, src/components/autocomplete/js/autocompleteDirective.js
```
[ ] Bugfix
```
applying `aria-labelledby` to `md-autocomplete` has no effect because the attribute is not forwarded on to the `input`.
Issue Number: 
Fixes #10815
add support for `aria-labelledby`
```
[ ] Yes
[x] No
```
=> feat(autocomplete): add support for aria-labelledby

gulp/tasks/build-contributors.js
```
[ ] Bugfix
```
`gulp watch site --dev` fails on Windows if the Linux `rm` command isn't available.
Issue Number: 
N/A
The contributors script now uses the `del` command on Windows instead of `rm`.
```
[ ] Yes
[x] No
```
=> build(contributors): don't assume rm command exists on Windows

src/core/services/theming/theming.js, src/core/services/theming/theming.spec.js
* extend test of `$mdTheming` to include one palette with and one without hue.
* add docs regarding new `paletteHues` options for `defineTheme` method of `$mdTheming`.
Fixes #10335
```
[ ] Bugfix
```
Currently, there is no possibility to apply hue-options to palettes when using `defineTheme`. This is described thoroughly in the following issue and Google Group.
https://groups.google.com/forum/#!topic/ngmaterial/d-D3MNFl6wg …
=> feat(theming): add ability to specify hues as options to defineTheme

src/components/select/select.js
```
[ ] Bugfix
```
- missing docs for md-option and md-optgroup
- the docs warning about using the `value` attribute with non-string values are confusing and unclear
Issue Number: 
Fixes #10264
- add missing docs for md-option and md-optgroup
- add links between md-select, md-option, and md-optgroup docs
- clarify the md-select-header docs
- add a note about not supporting AngularJS' ng-options track by syntax
- …
=> docs(select): add missing docs for md-option and md-optgroup

src/components/toast/demoBasicUsage/script.js, src/components/toast/demoCustomUsage/index.html, src/components/toast/demoCustomUsage/script.js, src/components/toast/demoCustomUsage/style.scss, src/components/toast/demoCustomUsage/toast-template.html, src/components/toast/toast.js, src/components/toast/toast.spec.js
```
[x] Bugfix
```
Actions within toasts are not announced at all for screen readers.
It's almost impossible to activate an action in a toast from a screen reader.
There are no instructions for screen reader users on how to dismiss a toast.
Issue Number: 
Fixes #349
move the role="alert" up a level
- makes action button visible to screen readers
add support for defining an actionKey to assign a hot key to an action
- this …
=> fix(toast): improve a11y support for $mdToast.simple(). improve docs

CHANGELOG.md
```
[ ] Bugfix
```
https://github.com/angular/material/issues/10912#issuecomment-341900283
Issue Number: 
Fixes #10912.
We document this API change as a breaking change in 1.1.2 and provide guidance on code migration.
```
[ ] Yes
[x] No
```
=> docs(changelog): add breaking change to md-selected-text for 1.1.2

src/components/datepicker/js/datepickerDirective.js
```
[x] Bugfix
```
- md-open-on-focus constantly re-opens on close w/ IE11
- we don't want `$mdUtil.nextTick`'s batching features in this case
- especially on a low performance or heavily loaded device
Issue Number: 
Fixes #10999
- Use `$timeout` instead of  `$mdUtil.nextTick`.
- Datepicker is no longer re-opened constantly when closed on IE11.
```
[ ] Yes
[x] No
```
=> fix(datepicker): md-open-on-focus constantly re-opens on close w/ IE11

src/components/input/input.js, src/components/input/input.spec.js
```
[x] Bugfix
```
If a `md-input-container` has an `md-icon` that has an `ng-if` that resolves to false (the icon should be removed), the `md-icon-left` or `md-icon-right` class is applied to the `md-input-container` incorrectly.
This regression was introduced in 1.1.1.
Issue Number: 
Fixes #9529
Relates to https://github.com/angular/material/pull/9155
Relates to https://github.com/angular/material/issues/9151
If a …
=> fix(input-container): handle initialization of md-icon with ng-if

src/core/services/interimElement/interimElement.js
Check if the interim element is valid before proceeding.
Fixes #10715
```
[x] Bugfix
```
At the moment the interim element is being removed from the list after new hideAction promise is created for it. In addition no extra check is made for the interim object before it is used.
This is causing an error as undefined object is trying be accessed. 
Issue Number: #10715 
The interim element is removed from the list before the …
=> fix(toast): remove the interim element from the list before closing element

src/components/icon/demoLoadSvgIconsFromUrl/script.js, src/components/icon/demoSvgIconSets/script.js, src/components/icon/demoUsingTemplateRequest/script.js, src/components/icon/icon.spec.js, src/components/icon/js/iconDirective.js, src/components/icon/js/iconService.js
```
[x] Bugfix
```
SVGs with embedded `id`s can be broken when they are read out of the icon cache.
Issue Number: 
Fixes #8689
SVGs with embedded `id`s can be read out of the icon cache without breaking because the `id` references are now updated in addition to the `id`s themselves.
```
[ ] Yes
[x] No
```
Thanks to @ystreibel for starting this work in https://github.com/angular/material/pull/11315!
=> fix(icon): stop breaking id references when caching icon ids

config/karma-sauce.conf.js, config/karma-travis.conf.js, config/karma.conf.js, package-lock.json, package.json, src/components/navBar/navBar.js, src/components/navBar/navBar.spec.js
```
[x] Bugfix
```
- A new `npm i` may pick up `jasmine-core@2.99.1` which will cause many test failures since we don't currently support that version.
- Setting `md-nav-href=""` on an `md-nav-item` doesn't apply the proper `ng-href=""` because of a bad `if` check.
- The docs indicate that a navigation attribute **must** be defined on each `md-nav-item`, but the code doesn't throw an exception if this occurs. This can lead …
=> fix(nav-bar): set ng-href on nav-item even if md-nav-href is empty

src/components/navBar/navBar.js, src/components/navBar/navBar.spec.js
… reader users
* make the nav-bar component a tablist.
* make the nav-item's li element presentational and the button a tab.
* apply the aria-label, if provided, to the button directly, not the li element.
Fixes #11485
```
[x] Bugfix
```
Issue Number: #11485 
Currently, the nav-bar element is exposed as a listbox accessible to screen reader users. Its nav-item child consists of a li element which currently has role "option" …
=> fix(nav-bar): improve screen reader support

docs/guides/PULL_REQUESTS.md
```
[ ] Bugfix
[X] Documentation content changes
```
Issue Number: fixes #11473 
Going through the current steps requires contributors to deal with Git Interactive Rebase which is confusing and may be error prone for first time contributors.
- Added link to [Github's Amending guide](https://help.github.com/articles/changing-a-commit-message/#amending-older-or-multiple-commit-messages)
- Replaced `git rebase` command with `git commit -a --amend`
- Corrected …
=> docs(pull-requests): add link to Github's Amending guide

src/components/virtualRepeat/virtual-repeater.js
```
[x] Bugfix
```
In some cases, like resizing the page, updateSize incorrectly sets the size to zero.
This can break the ability to show the dropdown on focus.
Issue Number: 
Fixes #10834
Check that the size value isn't zero before setting the size.
```
[ ] Yes
[x] No
```
Manually tested as I wasn't sure how to resize the browser in a unit test.
=> fix(autocomplete): updateSize incorrectly sets the size to zero

src/core/services/theming/theming.js, src/core/services/theming/theming.spec.js
```
[X] Bugfix
```
Issue Number: fixes #11259
`enableBrowserColor` fails silently if a hex code does not have a `#` at the start.
`enableBrowserColor` now checks for a leading `#` and prepends it if not already there.
```
[ ] Yes
[X] No
```
I updated other test plans to expect the leading `#`, the `testPalette` in the test plans did not have a `#` in their hex values. Originally I tried updating the palette to have a `#`, …
=>  fix(theme): prepend # to hex codes enableBrowserColor

src/components/switch/switch-theme.scss, src/components/switch/switch.scss
```
[x] Bugfix
```
Using the keyboard to focus on a switch in dark mode shows dark ink on a dark background.
Issue Number: 
#8518
Using the keyboard to focus on a switch in dark mode shows light ink on a dark background as defined by [the spec](https://material.io/archive/guidelines/components/selection-controls.html#selection-controls-switch).
```
[ ] Yes
[x] No
```
This builds upon @rudzikdawid's work in …
=> fix(switch): theming issues with focus in dark theme

src/components/select/select.js, src/components/select/select.spec.js
* Remove code which causes side effect on form elements
* Add a delay to the initial render of a multiple select so that it doesn't set the element to dirty on initialization.
Fixes #11490
```
[x] Bugfix
```
Issue Number: #11490
The select/multiple has code it in which causes a side-effect on the containing form by explicitly setting the form state to pristine anytime one is added with a set model value.  This errant code …
=> fix(select): don't change form state when adding to a form

src/components/autocomplete/js/autocompleteController.js, src/components/autocomplete/js/autocompleteDirective.js
```
[x] Bugfix
```
When selecting a value from an auto-complete, Chromevox reads it out as "{md-autocomplete aria-label} {Value} collapsed combo box". It's unclear to the user which part of the text read is the combo-box-name, and which is the value.
Issue Number: 
Fixes #10838
With the updates Chromevox will announce the following:
"{md-autocomplete aria-label} {Value} selected Collapsed Combo box"
If required: …
=> fix(autocomplete): Chromevox indicates selected option on focus

src/components/toast/demoCustomUsage/script.js, src/components/toast/toast.js, src/core/services/aria/aria.js
```
[x] Bugfix
```
- Simple toasts with actions will auto set actionKeys which can cause conflicts with user shortcuts.
- The custom toast example does not call removeActionKeyListener() when the toast is dismissed
Issue Number: 
Fixes #11474
- do not auto set any actionKeys
- provide warning if an action is defined without an actionKey
- fix custom toast example to call removeActionKeyListener()
```
[ ] Yes
[x] No
```
=> fix(toast): do not auto set any actionKeys

src/core/services/interimElement/interimElement.js
Reverting part of the previous commit as it introduced breaking changes
to the nested menu.
Fixes #11507 Relates to #10715
```
[x] Bugfix
```
The previous change introduced a breaking change with a nested menu. More in the linked issue.
Issue Number: #11507 #10715
The nested menu is working as expected again.
```
[ ] Yes
[x] No
```
=> fix(interim): validate the interim element while closing it

src/components/tabs/js/tabsController.js, src/components/tabs/tabs.scss
```
[x] Bugfix
```
- Tab items have right and left padding of `24px` which is `12px` more on each side than specified by [the MD spec](https://material.io/archive/guidelines/components/tabs.html#tabs-specs).
- Tabs on IE11 are truncated by pagination due to a calculated width of `0px` and the only width being the `48px` of padding.
- There are 2 functions in the code that are not used anymore.
- Many of the tab styles use …
=> fix(tabs): min-width not respected on IE11. fix right/left padding

package-lock.json, src/components/toast/demoBasicUsage/index.html, src/components/toast/demoBasicUsage/script.js, src/components/toast/demoBasicUsage/style.scss, src/components/toast/demoCustomUsage/script.js, src/components/toast/demoCustomUsage/toast-template.html, src/components/toast/toast.js
```
[ ] Bugfix
```
There are some pretty egregious errors and typos in the toast docs and demos.
There has also been confusion from developers on how to handle Promises and use `locals` with `bindToController`.
The basic usage demo uses `$scope` 🤮
Issue Number: 
Fixes #11499
- add use of locals to custom toast demo
- remove $scope from basic demo
- show proper Promise handling in basic demo
- clean up demo and doc typos and …
=> docs(toast): add use of locals to custom toast demo

src/components/virtualRepeat/virtual-repeater.js
```
[x] Bugfix
```
Calling `this.setSize_(size)` results in the containers width/height being changed which is undesirable and causes tests to fail inside of g3.
Issue Number: 
Relates to #11500
Just set `this.size` and avoid resizing the container in `updateSize()`.
```
[ ] Yes
[x] No
```
=> fix(autocomplete): don't resize the container in updateSize()

src/components/chips/demoBasicUsage/index.html, src/components/chips/js/chipRemoveDirective.js, src/components/chips/js/chipsController.js, src/components/chips/js/chipsDirective.js
```
[x] Bugfix
```
If the model objects passed to `md-chips` include recursive structures (i.e. they include something like `{value: 'Orange', parent: chipList}`, then parsing them for announcements or displaying them in `aria-labels` throws an exception.
Issue Number: 
N/A
- improve basic demo and md-chip-remove directive docs
- no longer parse JSON object
in order to try to provide some useful identifier in messages
```
[ …
```
=> fix(chips): don't throw when chip models are recursive, complex objects

package-lock.json, package.json
```
[ ] Bugfix
```
Running gulp on Chrome OS / Linux causes `ReferenceError: internalBinding is not defined`.
Issue Number: 
Relates to https://github.com/isaacs/natives/issues/14
Running gulp on Chrome OS / Linux is successful.
```
[ ] Yes
[x] No
```
=> build: fix error with NodeJS on Linux/Chrome OS

docs/app/partials/layout-children.tmpl.html, src/components/tabs/demoCenterTabs/index.html, src/components/tabs/demoCenterTabs/script.js, src/components/tabs/demoCenterTabs/style.scss, src/components/tabs/demoDynamicHeight/index.html, src/components/tabs/demoDynamicTabs/index.html, src/components/tabs/demoDynamicTabs/script.js, src/components/tabs/js/tabsController.js, src/components/tabs/js/tabsDirective.js, src/components/tabs/tabs.scss
```
[x] Bugfix
```
`md-center-tabs` is broken and doesn't render without clicking on the tab bar. Even then it renders partially off screen on Firefox and in some other cases.
Note that only one of center tabs or pagination can be activate at a time.
Issue Number: 
Fixes #11566. Relates to #11432.
Only apply the `width = 999999p`x work around when pagination is enabled.
`md-center-tabs` works properly on Firefox, IE11, Edge, …
=> fix(tabs): md-center-tabs causes tabs to not render

src/components/select/select.js, src/components/select/select.spec.js
this needs to happen after $render which is now evaluated on next tick
Fixes #11571
```
[x] Bugfix
```
Currently select labels are mashed into the values of a multi-selector.
This is the result of https://github.com/angular/material/commit/97e2d004523d2ca5ac9b54e567d8eddc7246aae7
Now multi-selectors $render is delayed to fix an incompatibility with forms.
Issue Number: #11571
Now the label is in the correct place.
To fix …
=> fix(select): evaluate md-input-has-value on next tick

src/components/autocomplete/js/autocompleteController.js
Don't use the bounding rectangles of a document body to determine
the position of the dropdown.
Top and bottom values of the snap element are relative to the viewport,
which is enough to decide about the position of the dropdown.
Fixes #10859
```
[x] Bugfix
```
Dropdown is shown on top even if there is not enough space for it.
Issue Number: #10859
A proper checks are made to determine if the dropdown should be shown on top …
=> fix(autocomplete): show dropdown on top only when there is room

src/components/radioButton/radio-button-theme.scss, src/components/radioButton/radio-button.scss
```
[x] Bugfix
```
Based on the MD spec (image below), we fail to provide a decoration for focused but unselected radio buttons (whether disabled or enabled).
Issue Number: 
Fixes #11563. Fixes #8339. Fixes #3643.
Better align with the MD spec by decorating the focused but unselected radio buttons (whether disabled or enabled).
```
[ ] Yes
[x] No
```
=> fix(radio-group): style focused but unchecked radio buttons

src/components/autocomplete/autocomplete-theme.scss, src/components/autocomplete/js/autocompleteDirective.js
```
[x] Bugfix
```
The second time and beyond when a chips autocomplete dropdown panel is opened, there will be a background on some of the matches to indicate that they are selected, even when they are not selected. It's very confusing UX.
Using `ng-class` within `md-virtual-repeat` doesn't seem to be working
it was evaluating the following to `true`: `-1 === 0`, `-1 === 1`, etc.
Issue Number: 
Fixes #10573.
We no longer …
=> fix(autocomplete): suggestions can be highlighted incorrectly

src/components/select/select.scss
```
[x] Bugfix
```
Carrots in `md-select`s are not aligned to the end in IE11 as explained in the issue.
Issue Number: 
Fixes #10714. Relates to #3840.
Carrots are properly positioned in IE11, Edge, Chrome, and Firefox.
```
[ ] Yes
[x] No
```
Thank you to @prestonvanloon for the original fix here in #3840.
=> fix(select): carrot not aligned to end in IE11

src/components/list/list.scss
```
[x] Bugfix
```
If the secondary actions' template was provided by a directive, then the actions would be behind the primary button. This meant that tooltips and clicks were not activated.
Issue Number: 
Fixes #9676
Secondary action tooltips and clicks were are activated when the template is provided by a directive.
```
[ ] Yes
[x] No
```
#9676 proposed adding a `z-index` to the `md-secondary-container`, but the container …
=> fix(list): case where user is unable to interact w/ secondary actions

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/autocompleteController.js
```
[x] Bugfix
```
Pressing enter to add a chip can cause two chips to be created in certain cases on IE11.
Issue Number: 
Fixes #10640. Closes #10667.
Pressing enter to add a chip no longer can cause two chips to be created in certain cases on IE11.
```
[ ] Yes
[x] No
```
Many thanks to @RudolfFrederiksen for helping debug this and come up with a solution.
=> fix(autocomplete): two chips added on enter w/ IE11

src/components/datepicker/demoValidations/index.html, src/components/datepicker/demoValidations/script.js, src/components/datepicker/js/calendar.js, src/components/datepicker/js/calendarYearBody.js
```
[ ] Bugfix
```
Using `md-date-filter` with `md-mode="month"` results in unexpected results as none of the months are disabled when `md-date-filter` returns `false`.
Issue Number: 
Closes #11525
md-date-filter is checked and can disable months in month mode if it returns `false`
added demo
only the first day of the month is checked to disable the month
fix typos in docs
fix JSDoc
```
[ ] Yes
[x] No
```
=> feat(datepicker,calendar): md-date-filter disables months in month mode

src/components/datepicker/js/datepickerDirective.js
```
[x] Bugfix
```
`md-open-on-focus` does not work on Firefox. The panel is shown and then immediately dismissed.
Issue Number: 
Fixes #10619
`md-open-on-focus` works on Firefox.
```
[ ] Yes
[x] No
```
=> fix(datepicker): does not open on focus in Firefox

src/components/tabs/js/tabsController.js
```
[x] Bugfix
```
Setting `md-selected` to `-1` causes a click on the header to throw an exception.
Issue Number: 
Fixes #10042
No exception.
```
[ ] Yes
[x] No
```
=> fix(tabs): exception when no selection and header clicked

.eslintrc.json, docs/app/js/app.js, docs/app/js/codepen.js, docs/app/js/demo.js, scripts/gulp-utils.js, src/components/datepicker/js/datepickerDirective.js, src/components/gridList/demoDynamicTiles/script.js, src/components/gridList/grid-list.js, src/components/icon/icon.spec.js, src/components/input/input.js, src/components/menu/js/menuServiceProvider.js, src/components/panel/demoPanelAnimations/script.js, src/components/panel/panel.js, src/components/progressCircular/js/progressCircularDirective.js, src/components/progressLinear/progress-linear.js, src/components/radioButton/radio-button.js, src/components/select/select.js, src/components/tabs/js/tabsDummyWrapperDirective.js, src/components/virtualRepeat/demoScrollTo/script.js, src/components/virtualRepeat/virtual-repeater.js, src/core/services/aria/aria.js, src/core/services/gesture/gesture.js, src/core/services/layout/layout.js, src/core/services/registry/componentRegistry.js
```
[ ] Bugfix
```
Our rules allow inconsistent spacing around keywords. We try to enforce this some through code reviews, but it leads to extra work by reviewers and contributors.
Issue Number: 
N/A
Enforce consistent spacing and all quick fixing.
This will cause an error: `if(myVar){`
This will pass linting: `if (myVar) {`
```
[ ] Yes
[x] No
```
=> style(eslint): enable keyword-spacing rule

scripts/bower-material-release.sh, scripts/snapshot-docs-site.sh
```
[ ] Bugfix
```
CircleCI forces the use of SSH which breaks our use of personal access tokens to push code to other repos.
Issue Number: 
Relates to #11592.
Remove the CircleCI global git override to force SSH.
```
[ ] Yes
[x] No
```
Related discussions:
- https://discuss.circleci.com/t/github-forced-through-ssh-protocol/5332/2
- https://discuss.circleci.com/t/is-it-ok-for-me-to-delete-gitconfig-in-the-box/5566
=> chore(ci): disable CircleCI's forcing of SSH with GitHub

src/components/navBar/navBar.js, src/components/navBar/navBar.scss, src/components/navBar/navBar.spec.js
```
[x] Bugfix
```
Clicking on nav items with a mouse causes the focus to move to the previously clicked nav item instead of the newly clicked nav item.
Issue Number: 
Fixes #11591. Relates to #11494. Closes #11598.
- Focus is moved to the new nav item after it is clicked.
- remove hover style that is inconsistent with spec
- add test from @codymikol 
```
[ ] Yes
[x] No
```
Thank you to @codymikol for doing the initial …
=> fix(nav-bar): improve focus behavior for click events

src/components/tabs/js/tabsController.js
```
[x] Bugfix
```
It takes an extra tab key press to get into the component so that you can change tab selection.
Issue Number: 
Fixes #11632
It only takes 1 tab to get into and interact with the tabs component.
```
[ ] Yes
[x] No
```
Tested on Chrome for macOS and Windows 10.
=> fix(tabs): tabbing into tabs component requires an extra tab key press

src/components/menu/demoMenuDensity/index.html, src/components/menu/demoMenuDensity/script.js, src/components/menu/demoMenuDensity/style.css, src/components/menu/demoMenuWidth/index.html, src/components/menu/js/menuDirective.js, src/components/menu/menu.scss
```
[x] Bugfix
```
When using `md-dense` class with `md-menu-content` and there are enough options to cause scrolling, the items are overlapping and jammed together.
Issue Number: 
Fixes #11278. Closes #11279.
When using `md-dense` class with `md-menu-content` and there are enough options to cause scrolling, the items are properly spaced vertically with a `min-height` of `32px` instead of `0`.
There are new docs and a demo …
=> menu(dense): add demo and docs. fix min-height when scrollable

docs/app/css/style.css, docs/app/js/anchor.js, docs/app/js/app.js
```
[ ] Bugfix
```
The header links often bring the user to the wrong part of the correct docs page or they just take the user to the AngularJS Material home page instead of the specific part of the docs that was intended.
Additionally, copying the links from the anchors results in a bad URL.
Issue Number: 
Fixes #11285
- anchor URLs now are relative to `base` defined in `<head>`.
- anchor links can now be copied and shared …
=> docs: links from header directives are not compatible with base URL

docs/app/css/style.css, src/components/input/input.js
```
[ ] Bugfix
```
There is an extra margin on the left of the docs nav menu.
Issue Number: 
N/A
- No more extra margin on the left of the docs nav menu.
- fix a typo in a comment
```
[ ] Yes
[x] No
```
=> docs(menu): fix docs nav menu margin

src/components/icon/js/iconService.js, src/core/util/util.js
```
[x] Bugfix
```
SVG elements are not loaded from the cache properly on IE11. The outer `<svg>` tag is lost.
Issue Number: 
Fixes #11603. Relates to #11545. Closes #11604.
SVG elements are loaded from the cache properly on IE11 including the `<svg>` tag and the element's attributes.
```
[ ] Yes
[x] No
```
We can't just use `outerHTML` here either due to that [not being supported for SVG elements in …
=> fix(icon): SVG elements are not loaded from the cache properly on IE11

src/components/checkbox/checkbox.js, src/components/checkbox/checkbox.spec.js, src/core/util/util.js
```
[x] Bugfix
```
Checkbox emits a native `submit` event when the `ENTER` key is pressed.
Issue Number: 
Fixes #11639
- match the behavior of the native input type checkbox
- When the `ENTER` key is pressed, `md-checkbox` searches the `form` for all submit `button`s and `input`s and send a `MouseClick` event to the first one that is enabled.
```
[ ] Yes
[x] No
```
I created tests for all of the following use cases
=> fix(checkbox): enter submits form when submit button is disabled

CHANGELOG.md
add additional details for checkbox fix
```
[ ] Bugfix
```
The date of the release in the changelog is 7 days early and the checkbox fix is missing one PR/commit reference.
Issue Number: 
N/A
Fixed date and added references.
```
[ ] Yes
[x] No
```
=> docs(changelog): update date of 1.1.13 release

docs/app/js/anchor.js, docs/app/js/app.js
```
[ ] Bugfix
```
- Anchor names include a `#` or path which breaks them
- Anchor `href`s don't include the `baseURL` which sends them to `404` pages
Issue Number: 
Fixes #11644. Relates to #11634. Relates to #11285.
- anchor `name`s do not include any path info
- `href`s include the baseURL in addition to the path
```
[ ] Yes
[x] No
```
=> docs: properly format anchor names and hrefs

src/components/dialog/dialog.js, src/components/dialog/dialog.spec.js
use stopImmediatePropagation instead of stopPropogation to ensure only
one dialog is closed when pressing esc.
Fixes #11308 
```
[x] Bugfix
```
Opening more than three dialogs on top of one another and closing two will cause the remaining dialogs to close at once.
This is happening because initially focus is on the outermost dialog and so hitting escape will close the first dialog as normal. This works the first time because …
=> fix:(dialog): prevent multiple dialogs closing on esc

src/components/panel/panel.js
```
[x] Bugfix
```
`trackedPanels` caching works for tooltips but not panels. [See more](https://github.com/angular/material/issues/10894#issuecomment-464122958).
Issue Number: 
Fixes #10894
`trackedPanels` caching works for tooltips and panels.
```
[ ] Yes
[x] No
```
=> fix(panel): caching of panels by id is not working

src/components/virtualRepeat/virtual-repeater.js
Issue #11461 : md-virtual-repeat-container: Scrolling to lasts elements do not render elements
```
[X] Bugfix
```
Issue Number: #11461
Correct redering of last elements.
CodePen Demo added in issue for testing
```
[ ] Yes
[X] No
```
=> fix(virtual-repeat-container): support horizontal scrollbar in vertical orientation

src/components/progressCircular/js/progressCircularDirective.js
show correct circle arc when changing from in determinate to determinate mode
Fix the broken behavior with the circle arc
Fixes: #11334
```
[x] Bugfix
```
A wrong circle arc is shown when changing from indeterminate to determinate mode.
Issue Number: #11334
A proper circle arc is shown when changing between different modes.
```
[ ] Yes
[x] No
```
=> fix(progress-circular): show correct circle arc

src/components/icon/js/iconService.js
```
[x] Bugfix
```
Large SVGs (170KB+) can cause the current caching RegEx code to hang and use 100% CPU for a long amount of time, freezing the app.
Issue Number:
Fixes #11651. Relates to #8689. Relates to #11342. Relates to #11635.
No more hangs processing large cached SVGs
- use querySelectorAll as much as possible
- reduce the use of RegEx on large chunks of DOM
```
[ ] Yes
[x] No
```
The reporter added a demo full of …
=> fix(icon): large SVG files can cause icon caching to hang

src/components/input/input.scss
```
[x] Bugfix
```
If a `md-input` has both a `placeholder` and a `label`, the placeholder is invisible on IE11.
Issue Number: 
Fixes #11668
If a `md-input` has both a `placeholder` and a `label`, the placeholder is visible on IE11.
```
[ ] Yes
[x] No
```
Verified manually in IE11 on Windows 10. No unit tests added as we don't run them against IE11.
Also verified by the reporter in …
=> fix(input): placeholder hidden when there is also a label on IE11

docs/gulpfile.js, gulp/config.js, gulp/tasks/build-demo.js, gulp/tasks/build-js.js, gulp/tasks/build-module-demo.js, gulp/tasks/build-scss.js, gulp/tasks/jshint.js, gulp/util.js, scripts/gulp-utils.js, src/components/icon/icon.scss, src/core/style/variables.scss
```
[ ] Bugfix
```
Consecutive builds, without any changes, result in bundle content with different ordering. This is even true in a single build where the `dist/angular-material.js` isn't identical to the `dist/docs/angular-material.js`. This makes comparing releases harder and it makes syncing into g3 more time consuming.
- passing globs to `gulp.src` can cause ordering to not be preserved.
this is because `gulp.src` is …
=> build: make the build output deterministic and reproducible

src/core/services/interaction/interaction.js, src/core/services/interaction/interaction.spec.js
this prevents unit tests from leaking memory
Fixes: #11493
```
[x] Bugfix
```
Currently the $mdInteraction service registers when invoked. This causes a memory leak in unit tests because nothing is in place to clean up the events.
Issue Number: #11493
Now on the $destroy event of rootScope the events registered will be unregistered.
```
[ ] Yes
[x] No
```
=> fix($mdInteraction): clean up events on $rootScope destroy

src/components/colors/colors.js, src/core/util/color.js
```
[ ] Bugfix
```
The Closure types / JSDoc in `md-colors` and `util/colors` is very inconsistent and/or missing. There are quite a few typos.
Issue Number: 
Relates to #11673
- Clean up typos.
- The Closure types / JSDoc in `md-colors` and `util/colors` are much more helpful and organized.
```
[ ] Yes
[x] No
```
=> refactor(colors): clean up Closure / JSDoc comments and types

src/components/dialog/dialog.spec.js, src/core/services/interimElement/interimElement.js
prevent interimElements from being tracked as showingInterimElements
when they fail to be compiled
Fixes: #11460
```
[x] Bugfix
```
If an interimElement fails to compile it will still be added as a "showingInterimElement"
Issue Number: #11460
Now interimElements will only be tracked in the showingInterimElements list if they successfully compile. 
```
[ ] Yes
[x] No
```
Unfortunately the showingInterimElements var is private …
=> fix(interimElement): don't track elements that fail compilation

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/autocompleteController.js, src/core/util/util.js
```
[x] Bugfix
```
- The fix for https://github.com/angular/material/issues/10859 has caused issues with the autocomplete dropdowns defaulting to `position="top"` instead of `bottom`.
- In some edge cases, dropdowns may be misaligned with their autocomplete input.
Issue Number: 
Fixes #11656. Relates to #10859, #11629, #11575.
- clean up and simplify the calculations for determining if the dropdown should use `top` or …
=> fix(autocomplete): default dropdown to position bottom as default

src/components/slider/demoBasicUsage/index.html, src/components/slider/demoBasicUsage/script.js, src/components/slider/demoVertical/index.html, src/components/slider/demoVertical/script.js, src/components/slider/slider.js, src/components/slider/slider.spec.js
```
[x] Bugfix
```
aria attributes are not announced when tabbing in screen readers
Issue Number: 
Fixes #11685
- aria attributes are announced when tabbing in screen readers
- revert changes from #10731
- move a number of aria attributes from `md-slider` to `md-slider-wrapper`
- fix inconsistencies, typos, and mistakes in the demos
```
[ ] Yes
[x] No
```
=> fix(slider): aria attrs are not announced when tabbing in screen readers

src/components/tabs/js/tabScroll.js, src/components/tabs/js/tabsController.js, src/core/util/util.js
```
[x] Bugfix
```
Mousewheel scrolling of paginated tabs works on all browsers other than Firefox. This is because Firefox did not implement the non-standard [`mousewheel`](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousewheel_event) and `MouseWheelEvent` features that other browsers did.
Issue Number: 
Fixes #11654
- use the standard [`wheel`](https://developer.mozilla.org/en-US/docs/Web/Events/wheel) event …
=> fix(tabs): use standard wheel event instead of non-standard mousewheel

docs/app/js/app.js, docs/config/template/index.template.html
scroll to top on every route/location change. Previously, for some of
the route changes when clicking on the side bar menu, the scroll stayed in place.
Fixes #11669
Bugfix/Enhancement for docs.
Issue Number: #11669 
Content pane scrolls to top on clicking a link from sidebar menu item
=> docs(scroll): scroll to top on route change

release.js
```
[ ] Bugfix
```
`npm publish` publishes the `.git/` directory in our release directory (`./bower-material/`) during the release process.
Issue Number: 
Fixes #11684
The `./bower-material/.git/` directory is removed before doing `npm publish`.
```
[ ] Yes
[x] No
```
This needs to be merged before the next release (`1.1.18`).
=> chore(release): workaround npm issue where .git/ dir is published

src/components/icon/icon.spec.js, src/components/icon/js/iconService.js
```
[X] Bugfix
```
When the same icon is used multiple times, they all have the same id.
Issue Number: 
Fixes #11395.
This fixes the issue found by @coennijhuis in PR #11342. 
When the same icon is used multiple times, they all have a different id. `_cache` followed by a number is appended to the id.
```
[ ] Yes
[X] No
```
=> fix(icon): stop breaking SVGs that have id references

docs/app/css/style.css, docs/app/js/anchor.js, docs/app/js/app.js, docs/config/template/index.template.html
```
[ ] Bugfix
```
1. When focused on the main content area the up/down/page up/page down buttons do not scroll the content. In addition to annoying users who primarily use the mouse, it makes things really bad for keyboard-only users who aren't using a screen reader.
1. The docs anchor directive converts `menu-heading` elements into anchors, but they have no associated content and clicking them creates invalid links like …
=> docs: allow up/down/page up/page down to scroll docs content

test/angular-material-spec.js
this is no longer needed as phantomJS is not used
Fixes: N/A
```
[ ] Bugfix
[x] Other... Please describe:
```
There is a bit of functionality that was at one point useful for working around phantomJS not implementing click() on HTML elements, this is no longer required as phantomJS is not used.
Issue Number: N/A
This workaround has been removed.
```
[ ] Yes
[x] No
```
This was a change that was made while investigating …
=> chore(tests): remove unused phantomJS workaround

docs/content/performance/internet-explorer.md
```
[ ] Bugfix
```
The link to the theming guide from the IE Performance guide is broken.
Issue Number: 
Fixes #11713
The link to the theming guide from the IE Performance guide is working.
```
[ ] Yes
[x] No
```
=> docs(ie): fix bad link to theming guide

src/components/datepicker/js/datepickerDirective.js
```
[x] Bugfix
```
A [regression](https://bugs.chromium.org/p/chromium/issues/detail?id=941910) in Chromium has caused date and time pickers around the Internet to instantly close when opened via a focus event due to a change in the timing of events. `md-datepicker` works better than most after going to the `100ms` delay to fix Firefox, but it isn't always enough, especially when changing focus from one input to another. …
=> fix(datepicker): auto closes in Chrome when md-open-on-focus is used

package-lock.json, src/components/menuBar/js/menuBarDirective.js, src/components/menuBar/js/menuItemDirective.js
```
[ ] Bugfix
```
`md-prevent-menu-close` on `md-menu-item` with type `checkbox` or `radio` does not get forwarded to the generated `button` and thus it is not possible to disable closing the menu on toggling a checkbox or radio button.
Issue Number: 
Fixes #11707
`md-prevent-menu-close` on `md-menu-item` with type `checkbox` or `radio` gets forwarded to the generated `button` and thus it is possible to disable closing the …
=> feat(menu-bar): support md-prevent-menu-close on checkbox/radio items

src/components/tabs/demoDynamicTabs/script.js, src/core/services/gesture/gesture.js
```
[x] Bugfix
```
- Ever since https://github.com/angular/material/commit/eecc5410dbfcdc59e2cba3f4255f03b58783ae27 in `1.1.4`, tapping a submit button fires two submit events on mobile. This causes the dynamic tabs demo w/ pagination to often add two tabs for each 'Add Tab' button click on iOS and Android.
- when click hijacking is enabled (default)
- isKeyClick check did not work on iOS since clientX/Y are set
- Our …
=> fix(gesture): tapping a submit button fires two submit events on mobile

release.js
```
[ ] Bugfix
```
If the person doing the release does not have `gulp` installed globally, they see something like this
```sh
Adding new version of the docs site...                                      fs.js:114
throw err;
^
Error: ENOENT: no such file or directory, open '/usr/local/google/home/username/git/material/dist/docs/docs.js'
at Object.openSync (fs.js:438:3)
at Object.readFileSync (fs.js:343:35)
at replaceFilePaths …
```
=> build(release): detect that gulp is not installed globally

src/components/datepicker/js/datepickerDirective.js, src/components/datepicker/js/datepickerDirective.spec.js
```
[x] Bugfix
```
- Lighthouse complains due to the datepicker's `input` having `aria-expanded="false"`. This properly isn't valid for `role="input"` in [ARIA 1.0](https://www.w3.org/TR/wai-aria-1.0/complete#input) or [ARIA 1.1](https://www.w3.org/TR/wai-aria-1.1/#input).
- `aria-haspopup="true"` uses the [ARIA 1.0](https://www.w3.org/TR/wai-aria-1.0/complete#aria-haspopup) value.
Issue Number: 
Relates to #11475
- remove …
=> fix(datepicker): remove invalid aria-expanded

src/components/panel/panel.js, src/components/panel/panel.spec.js
append the transform for panel animations after any existing transforms.  Previously, the animation
transform was appened first, resulting in the destination location being incorrect.
```
[x] Bugfix
```
When a panel has a centered location (or other transform applied) combined with an OpenFrom/CloseTo, the panel animates to/from the wrong location
Issue Number:
N/A
The panel animates to/from the correct location
```
[ ] Yes …
```
=> fix(panel): append panel animation transforms after existing transforms

src/components/autocomplete/js/autocompleteController.js, src/components/bottomSheet/bottom-sheet.js, src/core/util/util.js
```
[x] Bugfix
```
Clicking outside of the options dropdown panel for `md-autocomplete` does not dismiss the panel on iOS.
Issue Number: 
Fixes #9581.
Clicking outside of the options dropdown panel for `md-autocomplete` dismisses the panel on iOS. It is a similar approach to what the `md-datepicker` uses.
```
[ ] Yes
[x] No
```
=> fix(autocomplete): tap outside options panel on iOS does not close panel

package.json
```
[ ] Bugfix
```
Running `gulp` commands on Linux fails with 
```js
ReferenceError: primordials is not defined
```
Gulp 3 does not and will not support NodeJS 12
- https://stackoverflow.com/q/55921442/633107
We do not currently plan to upgrade to Gulp 4 due to the wide range of breaking changes that they introduced.
Issue Number: 
Relates to https://github.com/gulpjs/gulp/issues/2324
It's clearly defined what versions of …
=> build: set engines to disable NodeJS 12 due to Gulp 3

src/components/autocomplete/js/autocompleteController.js, src/components/autocomplete/js/autocompleteDirective.js, src/core/util/util.js
```
[x] Bugfix
```
After opening an autocomplete options panel by clicking the input with the mouse, when the mouse first moves over the edge of the panel, the panel flickers (hides and then reappears).
Issue Number: 
Relates to #11625
- stop propagation of input's click events up to the document
- similar to what we already do with the clear button (X)
- Closure/JSDoc typing improvements
```
[ ] Yes
[x] No
```
=> fix(autocomplete): options panel flickers on hover after clicking input

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/autocompleteDirective.js
```
[x] Bugfix
```
`click` events are not bubbling up to the `md-autocomplete` from the `input` or `placeholder` resulting in `ng-click` on `md-autocomplete` not being triggered.
Issue Number: 
Relates to #11625. Relates to #11757.
`click` events are bubbling up to the `md-autocomplete` from the `input` or `placeholder` resulting in `ng-click` on `md-autocomplete` being triggered. This happens while also stopping the `click` …
=> fix(autocomplete): support ng-click on md-autocomplete

src/core/services/compiler/compiler.js, src/core/services/gesture/gesture.js, src/core/util/util.js
```
[x] Bugfix
```
Hovering over a `md-tooltip` throws only when `$mdGestureProvider.disableAll()` was called in `config()`.
This is because `document.contains` is not defined on IE11 and the polyfill in `$mdGestureProvider` was only registered if gestures were enabled.
Issue Number: 
Fixes #11745
We polyfill `document.contains` when `$mdUtil` loads and it does not depend on gestures being enabled.
No more exceptions and …
=> fix(tooltip, compiler): document.contains is not defined in IE11

src/core/services/gesture/gesture.js
```
[x] Bugfix
```
PR https://github.com/angular/material/pull/11729 in `1.1.19` moved the check for `navigator` outside of code that depends on gestures being enabled. Since it doesn't check the existence of `window.navigator` first, this could throw an error when built via `angular/material-tools`.
Issue Number: 
Fixes #11751
Fixes a build error when using `angular/material-tools` by checking that `window.navigator` is …
=> fix(gesture): check if navigator is defined before accessing userAgent

src/components/gridList/grid-list.js, src/components/menu/js/menuServiceProvider.js, src/components/panel/panel.js, src/components/slider/slider.js, src/components/tabs/js/tabsController.js, src/components/virtualRepeat/virtual-repeater.js, src/core/util/util.js
Create a single function to check text direction based on dir attribute on DOM element or document.
Fixes #11016 Fixes #9754
```
[x] Bugfix
```
A whole document is expected to be set as RTL even when a `dir` attribute is set properly on an individual element.
Issue Number: #11016, #9754
It is possible to use `dir` attribute on an element to override a document's `dir` value.
```
[ ] Yes
[x] No
```
=> fix(rtl): support applying dir="rtl" on DOM elements other than the body

src/components/select/select.js
```
[x] Bugfix
```
On iOS
1. changing between two selects can lead to a situation where the floating label for both selects is colored due to both `md-input-containers` of the selects having `class="md-input-focused"` which should not happen.
1. with a `md-select` open, clicking on an `input` in a `md-input-container` causes the input to get focused (floating label and ink) but then the focus gets stolen back by the …
=> fix(select): improve focus/blur handling on iOS

src/core/services/gesture/gesture.js
```
[x] Bugfix
```
Click hijacking enters an infinite event loop when TalkBack is enabled and a `mouseup` event is fired.
Issue Number: 
Fixes #11768
Stop click hijacking from entering an infinite event loop when TalkBack is enabled and a `mouseup` event is fired.
```
[ ] Yes
[x] No
```
We currently have no way to automate testing of touch events or TalkBack on Android.
=> fix(gesture): maximum call stack size exceeded on click w/ TalkBack

src/components/input/demoBasicUsage/index.html, src/components/input/demoErrorsAdvanced/style.css, src/components/input/demoIcons/index.html, src/components/input/input-theme.scss, src/core/style/mixins.scss
```
[x] Bugfix
```
Floating labels use `color: rgba(0,0,0,0.38);` which doesn't align with the spec and fails Lighthouse contrast audits. This is the color we use for "disabled" text, which isn't right.
Currently our Input demo page gets a Lighthouse score of `77`.
Issue Number: 
Relates to #11475
Floating labels use `rgba(0, 0, 0, 0.54);` which passes Lighthouse contrast audits. This is the color we use for "secondary" …
=> fix(input): floating label text fails a11y contrast audit

src/components/autocomplete/autocomplete-theme.scss, src/components/autocomplete/autocomplete.scss, src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/demoBasicUsage/index.html, src/components/autocomplete/demoCustomTemplate/index.html, src/components/autocomplete/demoCustomTemplate/style.global.css, src/components/autocomplete/demoFloatingLabel/index.html, src/components/autocomplete/demoInsideDialog/dialog.tmpl.html, src/components/autocomplete/demoRepeatMode/index.html, src/components/autocomplete/demoRepeatMode/style.global.css, src/components/autocomplete/js/autocompleteController.js, src/components/autocomplete/js/autocompleteDirective.js, src/core/util/util.js, test/angular-material-mocks.js
```
[x] Bugfix
```
ChromeVox announces the following when the user changes to the `Alaska` option
> 'Alaska, Status'
When it should announce something like
> 'Alaska, List item, 2 of 50. ... List box with 8 items.'
Issue Number: 
Fixes #11742
- allow screen readers to do more and us to do less
- remove extra calls to announce the item that is visually focused
- remove tests for these extra live announcements
- give every …
=> fix(autocomplete): improve implementation of aria-activedescendant

.editorconfig, .gitignore
Any .editorconfig was set to be ignored in cf92799314ff5483fbc588241dbaf72ba0a7a97d.
This change introduces such a configuration file to allow contributors to use the correct code style more easily.
I'm not sure why the file was set to be ignored. IMHO it appears to be beneficial to place it in the repository to make it clear which indentation style is expected.
When I open the project in VS Code, it always attempts to indent using tabs, which is very frustrating. Obviously, I can just place my `.editorconfig` file from this PR into the project and resolve the issue for myself, but having the style defined right from the beginning for all developers would decrease onboarding friction.
What kind of change does this PR …
=> chore: Introduce Editorconfig

docs/guides/COMMIT_LEVELS.md
```
[ ] Bugfix
```
- inactive Caretakers are listed
- The process and responsibilities are not fully and accurately defined
- Some guidance is out of date
Issue Number: 
N/A
- remove inactive Caretakers
- better describe the process and responsibilities
- remove out of date guidance
```
[ ] Yes
[x] No
```
=> docs: update COMMIT_LEVELS.md

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/autocompleteController.js
At the moment the drop down stays at the same position.
Fixes #10479
```
[x] Bugfix
```
After reopening the drop down of the autocomplete the scroll starts from the same position when it was closed.
Issue Number: #10479
After reopening the drop down the scroll starts from the top.
```
[ ] Yes
[x] No
```
=> fix(autocomplete): scroll to top of the list each time dropdown open

src/components/navBar/navBar.js
```
[x] Bugfix
```
If the user needs to scroll to display the nav item, when they click it, the focus and horizontal scroll jumps back to the previously selected nav item. The clicked nav item is not selected or focused.
Issue Number: 
Fixes #11747
- reduce unnecessary calls to onFocus() and setFocused()
- in some cases, instead of focusing a nav item that was clicked on
we would focus the selected nav item
```
[ ] Yes
[x] …
```
=> fix(nav-bar): clicked nav item not focused or selected in some cases

src/components/autocomplete/js/autocompleteDirective.js
```
[x] Bugfix
```
Clicking on the scrollbar of the results in the autocomplete will immediately close the results.
Issue Number: #11776
Clicking the scrollbar of the results will allow the user to scroll and not close the results.
```
[ ] Yes
[x] No
```
=> fix(autocomplete): clicking options pop-up scrollbar on IE closes pop-up

src/components/bottomSheet/bottom-sheet.js, src/core/services/gesture/gesture.js, src/core/services/gesture/gesture.spec.js, src/core/util/util.js
```
[x] Bugfix
```
Touch action styles are applied by `$mdGesture.register(x, 'drag');` but they are not cleaned up on deregister if there was no touch action style previously on the element.
Before bottom sheet opened
```html
<div class="ng-scope">
```
After bottom sheet opened
```html
<div class="ng-scope" style="touch-action: pan-x;">
```
After bottom sheet closed
```html
<div class="ng-scope" style="touch-action: …
```
=> fix(gesture): 'drag' gestures don't clean up touch action styles on parent

src/components/list/demoListControls/script.js, src/components/list/demoListControls/style.css, src/components/list/list.js, src/core/util/util.js
```
[x] Bugfix
```
`isEventFromControl()` uses `MouseEvent.path` which is a Chrome only API.
This means that list items with a single proxy component (checkbox, switch, or menu) will not proxy clicks from the list item to the proxy component. I.e. the checkbox/switch will not toggle and the menu will not open on Safari, Firefox, Edge, and IE11.
Issue Number: 
Fixes #7937
`isEventFromControl()` uses a new `$mdUtil. …
=> fix(list): isEventFromControl() works on all browsers now

src/components/list/list.js, src/components/list/list.spec.js
```
[x] Bugfix
```
`aria-labels` are not applied to secondary actions if the `md-list-item` contains text in a `span` instead of a `p`.
Issue Number: 
Fixes #6152
- an `md-list-item`'s text should be in a `<span>` or `<p>`
but currently the `setupToggleAria()` function only handles `<p>`
this adds support for `<span>`
- add JSDoc
- fix typos in comments
- add docs for localizing aria labels on secondary actions
```
[ ] Yes …
```
=> fix(list): secondary actions give aria warning if text is in a span

src/components/select/demoTrackBy/index.html, src/components/select/demoTrackBy/script.js, src/components/select/demoTrackBy/style.css, src/components/select/select.js, src/components/select/select.spec.js
```
[x] Bugfix
[ ] Feature
```
When using `ng-model-options="{ 'trackBy': '$value.someProperty' }"` on md-select, `ng-change` is triggered when the selected option's object is not equal to the one of the model (the comparison is done with `angular.equals` which compares recursively all the properties of the object).  
Issue Number: #11108
`ng-change` is triggered when the tracked property of the model is different from the selected option. …
=> fix(select): when using trackBy, trigger ng-change only when tracked property is different

src/components/datepicker/js/datepickerDirective.js
After an update on Jul 30 2016 @crisbeto add a flag: `inputFocusedOnWindowBlur` to prevent opening a datepicker when the focus is active and user change a browser tab. 
The problem is that if the focus is active user can't open it again now. I add flag reset function and trigger it at the first time when the user backs to page with datepicker.
Fixes: #9186
```
[x] Bugfix
```
User set focus in calendar input, calendar picker …
=> fix(datepicker): reset inputFocusedOnWindowBlur flag

src/components/menu/js/menuController.js, src/components/menu/js/menuDirective.js, src/components/menuBar/js/menuBarController.js, src/components/menuBar/menu-bar.spec.js
When an mdMenuBar contains a menu and that menu is opened, the menu bar will receives a CSS class that ultimately affects its z-order. When the menu is closed, the CSS class is supposed to be removed from the menu bar.
When the menu has multiple levels, the menu hierarchy can not be correctly resolved upon menu closure. This results in the CSS class not being removed from the menu bar.
I assumed that this failure is mostly due to the attempt to detect menu structure through DOM traversal, which will not work in this case as the menu hierarchy is not directly reflected in the DOM structure (menus are attached to the body instead).
Fixes #11235
```
[X] Bugfix
[ ] …
```
=> fix(menu-bar): z-index not restored on menu close

src/components/autocomplete/js/highlightController.js, src/components/select/select.js, src/core/util/util.js, src/core/util/util.spec.js
```
[x] Bugfix
```
Issue Number: 
https://github.com/angular/material/issues/11854
```
[ ] Yes
[x] No
```
=> fix(select): sanitize user input before searching options

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/js/autocompleteController.js
allow the user cycling through the options list
Fixes #11766
```
[x] Bugfix
```
The list scrolling with up/down arrow keys does not wrap from the end to the first element (on down) or the first to the last element (on up).
Issue Number: #11766 
The list scrolling with up/down arrow keys should wrap.
```
[ ] Yes
[x] No
```
=> fix(autocomplete): loop options list when moving past first/last option with arrow keys

src/components/chips/contact-chips.spec.js, src/components/chips/js/contactChipsController.js
```
[x] Bugfix
```
Exceptions are thrown when using Contact Chips when an app is configured for production mode (`$compileProvider.debugInfoEnabled(false)`). This is a regression in `1.1.11`.
Issue Number: 
Fixes #11699
- fix exception when `debugInfoEnabled(false)` is set
- remove unused variables in tests
- remove commented out and unused code in tests
```
[ ] Yes
[x] No
```
I didn't add a test since we don't run our tests …
=> fix(contact-chips): don't rely on debug info to get access to controller scope

docs/app/css/style.css, src/components/select/demoBasicUsage/index.html, src/components/select/demoOptionGroups/index.html, src/components/select/select-theme.scss, src/components/select/select.js, src/components/select/select.spec.js, src/core/util/util.js
```
[x] Bugfix
```
- `md-select` does not work well with VoiceOver on iOS or macOS
- When using `md-select` with the `multiple` attribute, options are always "checked" because of ngAria.
Issue Number: 
Fixes #10748. Fixes #10967.
- move to [WAI-ARIA's Collapsible Dropdown Listbox practice](https://www.w3.org/TR/2019/NOTE-wai-aria-practices-1.1-20190207/examples/listbox/listbox-collapsible.html)
- don't apply aria-required to …
=> fix(select): overhaul screen reader support

release.js
```
[ ] Bugfix
```
All releases, even RCs, are published to NPM as 'latest'
Issue Number: 
Fixes #11873
- default to 'latest'
- allow 'next' to support RC releases
```
[ ] Yes
[x] No
```
N/A
=> chore(release): support publishing to NPM with tags other than latest

src/components/list/list.js
```
[x] Bugfix
```
`md-list-item`s with an `ng-click` cause the handler to be fired twice on keydown of space/enter keys when using AngularJS `1.6.0+`.
Issue Number: 
Fixes #11756
- disable keydown handler added by ng-aria
- fix doc and comment typos
- fix md-menu example not rendering
- rename `copyAttributes` to `moveAttributes` as the attribute are removed from the source
```
[ ] Yes
[x] No
```
This …
=> fix(list): primary action is fired twice on space/enter keydown

docs/app/css/style.css, src/components/autocomplete/js/autocompleteDirective.js
```
[x] Bugfix
```
The `md-not-found` template is not styled properly.
Issue Number: 
Fixes #11852
The `md-not-found` template is styled properly.
- also fix some styling issues with the docs-menu sidenav
caused by CSS specificity changes
```
[ ] Yes
[x] No
```
This minor styling issue doesn't seem like something that should be covered by unit testing.
=> fix(autocomplete): md-not-found template is not styled properly

.vscode/README.md, .vscode/extensions.json, .vscode/settings.json
```
[ ] Bugfix
```
We have no default config for VSCode and no guide for VSCode users.
Issue Number: 
Relates to https://github.com/angular/material/pull/11844.
- add VSCode configuration and guide
```
[ ] Yes
[x] No
```
=> chore: add VSCode configuration and guide

src/components/dialog/dialog.js
```
[ ] Bugfix
```
- Only the promise resolution behavior is described in the prompt and confirm dialog descriptions
Issue Number: 
Fixes #10130
- improves prompt and confirm dialog descriptions to clarify promise rejection behavior
```
[ ] Yes
[x] No
```
=> docs(dialog): clarify promise rejection behavior in descriptions

src/components/select/demoBasicUsage/script.js, src/components/select/select.js
```
[x] Bugfix
```
As reported in #11885, `SelectProvider.focusOptionNode()` can throw an exception when trying to call `SelectMenuController.setActiveDescendant()` in edge cases where the `SelectMenuController` is no longer defined or its lookup failed.
Issue Number: 
Fixes #11885
- Handle edge cases where the `selectMenuController` has been destroyed or is an `{}` rather than a Controller
- remove unused `selectController` …
=> fix(select): menuController not defined edge case in focusOptionNode

.github/ISSUE_TEMPLATE.md, docs/app/css/style.css, docs/app/partials/getting-started.tmpl.html, docs/app/partials/home.tmpl.html, docs/app/partials/layout-tips.tmpl.html
```
[ ] Bugfix
```
- The CodePen blank demo is out of date and we can no longer update it after stopping payment for the Pro plan.
- The "bucket" links on the home page have excess margins that break their layout flow.
- We link to some out of date versions of material-start.
- We don't link to our StackOverflow tag.
- CodePen embeds on the layout troubleshooting page have extra space at the bottom of the white frame.
Issue …
=> docs: updates to landing page and getting started

src/components/select/select.js
```
[x] Bugfix
```
Position of the select is not calculated properly when rtl is on.
Issue Number: 
#10395
Position of the select is calculated properly when rtl is on as well.
```
[ ] Yes
[x] No
```
=> fix(select): perform correct position calculation in rtl for long labels

src/components/select/select.scss
```
[x] Bugfix
```
- `md-select`'s height changes when disabled
Issue Number: 
Fixes #11812
- `md-select`'s height no longer changes when disabled
- use the same approach for `md-select`'s disabled border background-position as `md-input`
- `md-select` inside of an `md-input-container` uses more `md-input` SCSS variables
- this allows it to better match the layout and dimensions of other `md-input-container` elements
- add …
=> fix(select): height changes when disabled

src/components/panel/demoReuse/index.html, src/components/panel/demoReuse/panel.tmpl.html, src/components/panel/demoReuse/script.js, src/components/panel/demoReuse/style.global.css, src/components/panel/panel.js
```
[X] Bugfix
[X] Documentation content changes
```
When a panel is hidden once, it will not be displayed on screen when it is requested to be shown a second time. This is due to CSS classes still being applied to the panel after the animation finished.
Issue Number: #11291
The classes are correctly maintained and the panels can be reused many times.
```
[ ] Yes
[X] No
```
=> fix(panel): can't be reopened after being hidden

src/core/services/compiler/compiler.js, src/core/services/compiler/compiler.spec.js
```
[X] Bugfix
[X] Enhancement
```
Even though the `$onInit` lifecycle hook is fully supported, the `$onDestroy` hook isn't. This is unexpected for developers.
This change introduces a listener for the `$destroy` event on the linked scope. See https://docs.angularjs.org/api/ng/type/$rootScope.Scope#event-$destroy
This implementation closely resembles the AngularJS internal implementation of the lifecycle hook invokation behavior: …
=> fix(compiler): $onDestroy hook not called

src/components/progressCircular/progress-circular.scss, src/components/progressLinear/progress-linear.scss
```
[x] Bugfix
```
Progress indicator is not mirrored when rtl is on.
Issue Number: 
#10814 
Progress indicator is mirrored when rtl is on.
```
[ ] Yes
[x] No
```
=> fix(progress-linear,progress-circular): mirror indicator when rtl is on

src/components/progressCircular/js/progressCircularDirective.js
```
[x] Bugfix
```
When the diameter of the spinner is bigger than 60px, the rendering is not correct due to the problem with the precision of floating point calculations.
Issue Number: 
#10376 
Calculations were simplified to avoid the issue with the precision and to fix the rendering issue.
```
[ ] Yes
[x] No
```
=> fix(progress-circular): correct rendering for diameter bigger than 60

src/components/navBar/navBar.js, src/components/navBar/navBar.scss, src/components/navBar/navBar.spec.js
```
[x] Bugfix
```
The ink bar below the tab buttons does not update it's position if an item with `flex` exists besides `md-nav-items`.
Issue Number: 
Fixes #10121
Closes #11042
- update inkbar on screen resize
- changed how inkbar is moved
- use transform to scale and translate the inkbar
- also add debounced update to window resize
```
[ ] Yes
[x] No
```
This PR takes over PR https://github.com/angular/material/pull/11042 …
=> fix(navBar): update inkbar on screen resize

src/core/util/util.js, src/core/util/util.spec.js
```
[x] Bugfix
```
There was a minor `RegExp` change when moving the `sanitize()` function from `md-autocomplete` to `$mdUtil`. This caused a regression where `md-autocomplete` would throw an exception when `(` was typed into the input.
Issue Number: 
Fixes #11908
No more exception. Sanitize `RegExp` updated. Tests fixed.
```
[ ] Yes
[x] No
```
=> fix(util): sanitize function used by select and autocomplete throws

src/components/select/demoOptionGroups/index.html, src/components/select/demoOptionGroups/script.js, src/components/select/select.js, src/components/select/select.spec.js
```
[x] Bugfix
```
Option groups are not read by screen readers.
Issue Number: 
https://github.com/angular/material/issues/11240
Option groups are read by screen readers without breaking the reading of indexes.
- add single selection optgroup demo
- add tests for optgroup `aria-label`
- add tests for optgroup options' `aria-setsize` and `aria-posinset`
```
[ ] Yes
[x] No
```
On VoiceOver for macOS, indexes are no longer …
=> fix(select): optgroups are not visible to screen readers

package-lock.json, src/components/datepicker/js/calendar.js, src/components/datepicker/js/calendarMonth.js, src/components/datepicker/js/calendarMonthBody.js, src/components/datepicker/js/calendarYear.js, src/components/datepicker/js/calendarYearBody.js, src/components/datepicker/js/dateLocaleProvider.js, src/components/datepicker/js/dateUtil.js, src/components/datepicker/js/datepickerDirective.js, src/core/util/util.js
```
[ ] Bugfix
```
For a case like
```html
<md-calendar ng-model="calendarDate" ng-model-options="{timezone: 'UTC'}"></md-calendar>
```
A binding like `{{calendarDate|date:"dd/MMMM/yyyy HH:mm Z":"UTC"}}` should give you a midnight-aligned date in the UTC timezone. However, it does not. This is inconsistent with the `md-datepicker`.
Issue Number: 
Fixes #10431
- support specifying timezone in `ng-model-options`
- remove calls …
=> feat(calendar): support specifying timezone in ng-model-options

src/components/select/select.js, src/components/select/select.spec.js
```
[x] Bugfix
```
In `1.1.22`, we accidentally removed support for the undocumented `ng-selected` API on `md-option`.
Issue Number: 
Fixes #11914
- revert removal of support for `ng-selected` on `md-options`
- add unit test to ensure `ng-selected` support continues to work
- add docs for `ng-selected` on `md-option`
```
[ ] Yes
[x] No
```
=> fix(select): revert removal of support for ng-selected on md-options

package-lock.json, package.json, src/components/toast/toast.js
```
[x] Bugfix
```
- onRemove doesn't return a Promise in some cases
- this results in an exception
Issue Number: 
Fixes #10379
- onRemove always returns a Promise
- add types for `$q`
```
[ ] Yes
[x] No
```
This has been reported by many different users over the errors, but we were never able to track it down with a solid reproduction until now.
=> fix(toast): onRemove doesn't return a Promise in some cases

src/components/datepicker/demoValidations/index.html, src/components/datepicker/demoValidations/script.js, src/components/datepicker/js/calendar.js, src/components/datepicker/js/calendarYearBody.js, src/components/datepicker/js/datepickerDirective.js, src/components/datepicker/js/datepickerDirective.spec.js
```
[x] Bugfix
```
- in year view, `md-date-filter` only evaluates first day of month causing many months to be disabled incorrectly
Issue Number: 
Fixes #11703
- add `md-month-filter` API
- no longer apply `md-date-filter` to year view
- fix JSDoc typos
- add JSDoc, tests, and demos
```
[x] Yes
[ ] No
```
But this is fixing a regression, so it will actually revert a breaking change in `1.1.10`.
Design discussion can be …
=> fix(calendar, datepicker): in year view, md-date-filter only evaluates first day of month

src/components/datepicker/js/datepickerDirective.js, src/components/datepicker/js/datepickerDirective.spec.js
```
[x] Bugfix
```
- error state is updated in the `$formatters` section of the `$validators` pipeline, before `$validate` has run. So the checks for `ngModelCtrl.$valid` are not accurate.
Issue Number: 
Fixes #10360
- update error state only after `$validate` has run
- only decorate with `md-datepicker-invalid` class (red underline)
- if the control has been `$touched` or `$submitted`
- this improves the behavior when the …
=> fix(datepicker): update error state only after $validate has run

src/components/tabs/js/tabsController.js, src/components/tabs/js/tabsDirective.js
```
[x] Bugfix
```
- tabs API docs and types have issues
- `md-no-disconnect` API docs
- missing parameters
- invalid parameters
Issue Number: 
Fixes #10407
- improve correctness of API docs and types
- re-add missing `md-no-disconnect` API docs, but mark the API deprecated
- add missing parameters
- remove invalid parameters
```
[ ] Yes
[x] No
```
=> docs(tabs): improve correctness of API docs and types

src/components/list/list.scss
```
[x] Bugfix
```
- we allow overriding list-item padding for non-clickable items only
Issue Number: 
Fixes #10384
- we allow overriding list-item padding for clickable and non-clickable items
```
[ ] Yes
[x] No
```
=> fix(list): allow overriding list-item padding for clickable items

src/components/toolbar/toolbar.js, src/core/util/util.js, src/core/util/util.spec.js
```
[x] Bugfix
```
- On a `md-select` nested within a `md-toolbar` which has `md-scroll-shrink` activated,
when `onChangeScrollShrink` is called, `closestContent` contains the `md-select`'s `md-content`, which is later moved to the body, but it's already too late, scroll listeners have already been applied.
- `md-scroll-shrink` does not work if content is scrolled too soon after page load
Issue Number: 
Fixes #10413. Closes …
=> fix(toolbar): md-scroll-shrink conflicts with md-select in toolbar

src/components/select/select.js, src/components/select/select.spec.js, src/core/services/interimElement/interimElement.js
```
[x] Bugfix
```
- The focused option's `md-focused` class is not removed when the menu is closed. When the menu is opened again, another option may be auto focused resulting in two options being decorated with `md-focused`. Repeating this can lead to many options with `md-focused`.
- There are no tests for select menu options' focus decoration.
Issue Number: 
Fixes #11927
- remove the focused option's `md-focused` class …
=> fix(select): md-focused not removed from options on panel close

src/components/menu/js/menuServiceProvider.js, src/components/menuBar/menu-bar.spec.js
focus stays with the parent menu when nested one is closed instead of closing all the menus
Fixes #11678
```
[x] Bugfix
```
At the moment when the user presses escape key while the nested menu is open, it causes all the menus to become closed and the focus is lost.
Issue Number: #11678
When the escape key is pressed, only the current nested menu is closed and the focus goes to the parent menu.
```
[ ] Yes
[x] No
```
=> fix(menu-bar): close just nested menu when escape key is pressed

src/components/datepicker/js/calendar.js, src/components/datepicker/js/calendarMonthBody.js, src/components/datepicker/js/calendarYearBody.js
```
[x] Bugfix
```
`md-calendar` when used outside of `md-datepicker` doesn't scroll to the current month and stays on January 1880.
Issue Number: 
Fixes #11919
- revert removal of workaround for virtual repeat issue
- #8585 turned out to not be a bug
- this restored code is not actually a workaround for a bug but actually part of the implementation needed for `md-calendar`
- improve some types and JSDoc
```
[ ] Yes
[x] No …
```
=> fix(calendar): revert removal of workaround for virtual repeat issue

src/components/panel/panel.js, src/components/panel/panel.scss, src/components/panel/panel.spec.js, src/components/tooltip/tooltip.scss
```
[x] Bugfix
```
Previously, if a panel had a position with an offset (e.g. `$mdPanel.newPanelPosition().center()`), the positioning would break any `transform` animations on the panel. This was due to the fact that `mdPanel` uses inline `transform` styles to do the offsetting. 
Issue Number: 
Relates to #9641.
Fixes #9905.
These changes introduce a wrapper around the panel (`.md-panel-inner-wrapper`), which will handle …
=> feat(panel): allow transform to be animated on an offset panel

src/core/services/layout/layout.js, src/core/services/layout/layout.spec.js
```
[x] Bugfix
```
- `origValue` is not defined, thus it always checks the `value` against `undefined`
Issue Number: 
Fixes #10935
- revert change to not set `origValue` so that `value` is actually checked against the original value
```
[ ] Yes
[x] No
```
This issue was caused by PR https://github.com/angular/material/pull/10462 which was trying to deal with [this change](https://github.com/angular/angular.js/commit/97bbf86) …
=> fix(layout): Syntax Error: Token '&&' not a primary expression

docs/content/Theming/01_introduction.md, docs/content/performance/internet-explorer.md, src/components/datepicker/js/dateLocaleProvider.js, src/components/datepicker/js/datepickerDirective.js, src/components/panel/panel.js, src/components/panel/panel.spec.js, src/core/services/compiler/compiler.js, src/core/services/theming/theming.js
```
[x] Bugfix
```
- The new `md-panel` code to support animation of offset panels in PR https://github.com/angular/material/pull/11390 caused some extra CSP violations of unsafe inlined styles.
Issue Number: 
Fixes #11941
- use existing `_md-panel-offscreen` class instead of inline styles
- fix some invalid or inaccurate types, JSDoc, and comments
- improve type safety and IDE support by using `@types/angular` more
- fix …
=> fix(panel): use existing _md-panel-offscreen class instead of inline styles

package-lock.json, src/components/panel/panel.js, src/core/util/animation/animate.js, src/core/util/constant.js
```
[x] Bugfix
```
1. panels that animate in aren't shown on screen
1. panels that are reused, accumulate `transform`s causing strange, compounding issues
Issue Number: 
FIxes #11946
1. remove `md-panel-offscreen` from `innerWrapper` in `_updatePosition()` if `init` is true
1. remove the inline transforms after the close animation runs so that reused panels don't accumulate `transform`s
```
[ ] Yes
[x] No
```
I'll merge this …
=> fix(panel): resolve animation issues

src/components/checkbox/checkbox.scss, src/components/checkbox/demoBasicUsage/index.html, src/core/style/_variables.scss
```
[x] Bugfix
```
- Checkbox did not support a11y minimum touch target and the box was larger than spec.
Issue Number: 
Fixes #9351. Fixes #9927. Closes #8713.
- Change checkbox size from 20px to 18px
- Keep horizontal size flush when text is blank
- Add `md-dense` support for checkbox
- Add inline alignment math to SCSS
- Increase size of `md-checkbox` to properly support touch
```
[x] Yes
[ ] No
```
I'm not sure why, but …
=> fix(checkbox) update CSS to match spec

src/components/input/_input-variables.scss, src/components/input/input.scss, src/components/select/select.scss
```
[x] Bugfix
```
- `md-input` and `md-select` inside of `md-input-containers` have excess left padding (in LTR) and right padding (in RTL)
- `label`s don't match the width of their inputs when `md-icon-left` or `md-icon-right` are used
Issue Number: 
Fixes #10105. Closes #11421.
- `md-input` and `md-select` inside of `md-input-containers` have indentation that matches the spec
- `label`s match the width of their inputs …
=> fix(input-container): align indentation with spec

src/components/checkbox/checkbox.js, src/components/checkbox/checkbox.scss, src/components/checkbox/checkbox.spec.js, src/components/checkbox/demoLabels/index.html, src/components/checkbox/demoLabels/script.js, src/components/checkbox/demoLabels/style.css
```
[x] Bugfix
[ ] Feature
```
JAWS and Voiceover can't get to links in `md-checkbox` labels.
Issue Number: 
Fixes #11134
- JAWS and Voiceover should properly handle links in `md-checkbox` labels.
- Wrapping the checkbox in `md-input-container` is required for using links in checkbox labels due to layout considerations.
- Add new demos for different types of a11y checkbox labels.
- don't toggle the checkbox on link actions
- don't output …
=> fix(checkbox): handle links in transcluded label in an a11y-friendly way

src/components/chips/chips.scss
fix(chips): md-chips remove icon not inheriting class size
This fix will allow the chip remove icon to inherit the proper size from the css class.
This addresses issue #9619
=> fix(md-chips): change md-icon class to inherit size

src/components/tabs/tabs.scss
```
[x] Bugfix
```
Previous commits removed use of `getMinTabWidth()` but never updated the CSS to apply the proper `min-width`.
- Tabs always had a min width of `72px` even though they should have a min width of `160px` "on larger devices" according to [the MD spec](https://material.io/archive/guidelines/components/tabs.html#tabs-specs).
Issue Number: 
Relates to #10406. Relates to #11432.
- This applies the proper …
=> fix(tabs): update min-width to follow the spec

docs/guides/THEMES_IMPL_NOTES.md, src/components/colors/demoBasicUsage/index.html, src/components/colors/demoBasicUsage/regularCard.tmpl.html, src/components/colors/demoBasicUsage/script.js, src/components/colors/demoBasicUsage/style.css, src/components/colors/demoBasicUsage/userCard.tmpl.html, src/components/colors/demoThemePicker/index.html, src/components/colors/demoThemePicker/script.js, src/components/colors/demoThemePicker/style.css, src/core/services/theming/theming.js, src/core/services/theming/theming.spec.js
```
[ ] Bugfix
```
Issue Number: 
N/A
- Add opacity keyword support (`secondary`, `icon`, `disabled`, `hint`, `divider`)
- Deprecate documentation of `foreground-*` in favor of `background-default-contrast-*`
- Allow `foregroundPalette` to override colors on default background and hues of equal contrast type
```
[ ] Yes
[x] No
```
This is based on @clshortfuse's PR https://github.com/angular/material/pull/8872.
=> feat(theme): add contrast opacity values for all color types and hues

src/components/input/input-theme.scss, src/components/toolbar/demoInputsInToolbar/index.html, src/components/toolbar/demoInputsInToolbar/script.js, src/components/toolbar/demoInputsInToolbar/style.scss, src/components/toolbar/toolbar-theme.scss
```
[x] Bugfix
```
Inputs in toolbars aren't themed properly and don't meet a11y guidelines for contrast.
Issue Number: 
Fixes #7987. This depends on #11376 being merged first.
Inputs in toolbars are themed properly and have contrast to make them readable.
```
[ ] Yes
[x] No
```
Before
After
=> fix(toolbar): input placeholders and ink need more contrast 

docs/app/css/style.css, docs/app/js/app.js, docs/content/Theming/03_configuring_a_theme.md, src/components/button/button-theme.scss, src/components/button/demoBasicUsage/index.html, src/components/button/demoBasicUsage/script.js, src/components/button/demoBasicUsage/style.css, src/components/card/demoCardActionButtons/index.html, src/components/card/demoInCardActions/index.html, src/components/checkbox/checkbox-theme.scss, src/components/colors/colors.js, src/components/colors/demoBasicUsage/index.html, src/components/colors/demoThemePicker/index.html, src/components/input/input-theme.scss, src/components/subheader/subheader-theme.scss, src/components/toolbar/demoInputsInToolbar/index.html, src/components/toolbar/toolbar-theme.scss, src/core/core.js, src/core/services/theming/theme.palette.js, src/core/services/theming/theming.js
```
[x] Bugfix
```
- The contrasts of our color palettes do not meet AA standards (4.5+ ratio).
- `md-toolbar`s with the `md-warn` class don't properly theme `md-icons`
- There are a number of a11y issues with the demos.
- `md-subheader` text does not meet AA standards (4.5+ ratio) due to low opacity.
- `md-input` labels and placeholders do not meet AA standards (4.5+ ratio) due to low opacity.
Issue Number: 
Fixes #8992. …
=> fix(theming, toolbar, subheader, input): align color palettes and contrasts with AA standards

src/components/panel/panel.js
```
[x] Bugfix
```
- `$mdPanel` throws exceptions when the `groupName` is a string instead of an Array.
Issue Number: 
N/A
- don't throw exceptions when the groupName is a string
- the APIs take a string or Array, we need to handle that w/o exceptions
- fix invalid JSDoc/Closure syntax
- remove duplicate header comments
```
[ ] Yes
[x] No
```
=> fix(panel): don't throw exceptions when the groupName is a string

src/components/navBar/navBar.js
```
[x] Bugfix
```
Issue Number: 
Relates to #11964
- `MdNavBarController._getTabs()` returns an empty array instead of `null`
to match existing return type
- rename `MdNavItemController._focused` to `MdNavItemController.isFocused`
- make it non-private since it is accessed by `MdNavBarController.onFocus()`
- fix/improve types
- remove unused variables
- add JSDoc
```
[ ] Yes
[x] No
```
The test will be added via PR #11964.
=> fix(nav-bar): throws exception when indexing null tabs variable

src/components/checkbox/checkbox.js
```
[x] Bugfix
```
The new a11y support for links in checkbox labels introduced an exception in IE11 due to using [the unsupported](https://caniuse.com/#feat=childnode-remove) `ChildNode.remove()` API.
Issue Number: 
N/A
Wrap the element in jQLite before calling `.remove()` on it to avoid exceptions on IE11.
```
[ ] Yes
[x] No
```
=> fix(checkbox): labels with links throw exception in IE11

src/components/chips/js/chipsController.js, src/components/select/select.js, src/components/toast/toast.js, src/components/toast/toast.spec.js, src/core/services/compiler/compiler.js, src/core/services/compiler/compiler.spec.js
```
[ ] Bugfix
[x] Other... Please describe: removal of deprecated code and APIs
```
- deprecated code and APIs
Issue Number: 
N/A
- refactor(chips): remove deprecated `MdChipsCtrl.selectAndFocusChip()`
- refactor(select): rename `ngMultiple` to `mdMultiple`
- refactor(toast): remove deprecated `content()` method and option and `updateContent()` method
- refactor($mdCompilerProvider): remove deprecated …
=> 1.2.0 deprecation removals, Part 1

src/components/button/button.scss, src/components/button/demoBasicUsage/index.html, src/components/button/demoDense/index.html, src/components/button/demoDense/script.js, src/components/button/demoDense/style.css, src/core/style/_variables.scss
```
[x] Bugfix
```
Issue Number: 
Fixes #10535
- left and right padding changed from `6px` to `8px`
- add a demo for dense buttons
```
[x] Yes
[ ] No
```
BREAKING CHANGE: `md-button`'s internal horizontal padding has changed from `6px` to `8px` to match the Material Design spec. This may affect the layout of portions of your application where `md-button`, `md-datepicker`, or `md-toast` with actions are used.
If you are using …
=> fix(button): horizontal padding should match the spec

src/components/select/demoBasicUsage/style.css, src/components/select/demoSelectHeader/index.html, src/components/select/demoSelectHeader/script.js, src/components/select/demoSelectHeader/style.css, src/components/select/select.js
```
[x] Bugfix
```
- select with `md-select-header` closes on mouse click of the header's `input` when not using multiple
Issue Number: 
Fixes #11969
- if the click event came from within a `md-select-header`, `stopImmediatePropagation()`
to keep the menu from closing
- fix demo's input being too short to display label when 'Kale' is selected
- rename some events and add types
- update select header input's placeholder and …
=> fix(select): md-select-header closes on mouse click when not using multiple

src/components/button/button.scss, src/components/list/list.scss, src/core/style/_variables.scss
```
[x] Bugfix
```
- As described in #11966, checkboxes are not vertically aligned with icon buttons
- `.md-dense-disabled` is not supported with lists
- `.md-dense` list item heights don't match the spec
Issue Number: 
Fixes #11966
- match the spec update where `md-dense` list items are `40px` in height by default
- was `48px` in height
- support `.md-dense-disabled`
- for `.md-dense` lists: align heights with spec for list …
=> fix(list): fix checkbox alignment and match dense heights to spec

release.js
```
[ ] Bugfix
```
```sh
From github.com:angular/material
* branch                master     -> FETCH_HEAD
Could not find merge strategy 'theirs'.
Available strategies are: octopus ours recursive resolve subtree.
```
Issue Number: 
N/A
`--strategy=recursive --strategy-option==theirs`
This isn't the same as the old `--strategy=theirs`, but that hasn't existed in a while and it's already been defaulting to …
=> chore: merge --strategy=theirs no longer exists

src/components/dialog/dialog.js, src/components/toast/toast.js, src/core/services/compiler/compiler.js, src/core/services/interimElement/interimElement.js
```
[ ] Bugfix
[x] Other... Please describe: removal of undocumented, unused parameter in internal API
```
Issue Number: 
- no longer pass controller to `options.onShow()`
- it does not appear to be used by any components that depend on interimElement
- panel, bottom sheet, tooltip, dialog, toast
- improve docs, comments and JSDoc types
- for `$mdDialog`, `$mdCompiler`, `$mdToast`, and `$$interimElement`
```
[ ] Yes
[x] No
```
=> refactor(interimElement): no longer pass controller to options.onShow()

src/components/checkbox/checkbox.js, src/components/checkbox/checkbox.scss, src/components/divider/divider-theme.scss, src/components/divider/divider.scss, src/components/input/input.js, src/components/radioButton/radio-button.js, src/components/radioButton/radio-button.scss, src/components/select/demoBasicUsage/style.css, src/components/select/select.js, src/core/style/_mixins.scss, src/core/style/_variables.scss, src/core/style/structure.scss
```
[ ] Bugfix
```
Dividers don't render properly when inside of an element with `layout="column"`
Issue Number: 
Fixes #9112. Closes #9220.
Creates `@mixin` that only triggers when in row configuration.
- Dividers now properly display in dynamic layout directions.
- Radio Buttons bottom margins are now properly removed when
in row configuration.
- Input, Select, Radio Buttons and Checkboxes automatically
add 16px horizontal …
=> feat(layouts): add @mixin for responsive support for rows

package-lock.json, src/components/checkbox/checkbox.scss, src/components/datepicker/datePicker.scss, src/components/input/_input-variables.scss, src/components/input/demoErrors/index.html, src/components/input/demoInlineForm/index.html, src/components/input/demoInlineForm/script.js, src/components/input/demoInlineForm/style.scss, src/components/input/input.js, src/components/input/input.scss, src/components/input/input.spec.js, src/components/radioButton/demoBasicUsage/index.html, src/components/radioButton/radio-button.scss, src/components/select/select.js, src/components/select/select.scss, src/components/switch/switch.scss
```
[x] Bugfix
```
- `md-inline-form` support is undocumented (no demo, no docs)
- there are some duplicate Sass variables
- there are some styles that users need to adjust, but they aren't associated with Sass variables
- `ng-messages` top padding is too small to meet the Material Design spec
- `textarea`s in inline forms are misaligned
- radio buttons in inline forms have some layout issues
Issue Number: 
Fixes #8712. …
=> fix: inline form support

gulp/util.js
```
[ ] Bugfix
```
- The 'checkbox', 'datepicker', 'radioButton', and 'switch' modules aren't set up to build their Sass with the input variables.
Issue Number: 
https://app.circleci.com/pipelines/github/angular/material/818/workflows/41319e2b-ac01-4f00-8190-e8a2ccf6224b/jobs/4800
- The 'checkbox', 'datepicker', 'radioButton', and 'switch' modules are set up to build their Sass with the input variables.
```
[ ] Yes
[x] No …
```
=> build(modules): configure more components to depend on input variables

src/components/dialog/demoBasicUsage/script.js, src/components/radioButton/demoBasicUsage/index.html, src/components/radioButton/demoBasicUsage/script.js, src/components/radioButton/demoBasicUsage/style.css, src/components/radioButton/demoMultiColumn/index.html, src/components/radioButton/demoMultiColumn/script.js, src/components/radioButton/demoMultiColumn/style.css, src/components/radioButton/radio-button.js, src/core/util/iterator.js
```
[x] Bugfix
```
- Screen readers don't work properly (in different ways, see issues) with `md-radion-group` and `md-radio-button`.
- The radio button demos are not accessible.
- There is a lot of extra stuff in the radio button demos that makes them more complex than needed, including unused styles, extra elements and attributes, etc.
Issue Number: 
Fixes #11973. Fixes #11923. Fixes #11974.
Screen reader behavior is …
=> fix(radio-button): when no value selected, first button not announced on focus

src/components/autocomplete/autocomplete.spec.js, src/components/autocomplete/demoBasicUsage/index.html, src/components/autocomplete/js/autocompleteController.js, src/components/autocomplete/js/autocompleteDirective.js
```
[x] Bugfix
```
- the default is `'blur clear'`
- this causes some a11y challenges as users get sent to the `<body>` in Chrome after Escape is pressed while having an `md-autocomplete` options panel open. Most screen reader users just want the panel to dismiss, they don't want their focus to be sent to the body as that may cause them to need to re-navigate the whole page again.
Issue Number: 
Fixes #11767
- …
=> fix(autocomplete): change md-escape-options default to 'clear'

src/components/chips/chips-theme.scss, src/components/chips/chips.scss, src/components/chips/demoBasicUsage/index.html, src/components/chips/demoBasicUsage/style.scss, src/components/chips/js/chipRemoveDirective.js, src/components/chips/js/chipsDirective.js
```
[x] Bugfix
```
See the issue for some of the ways that `md-chips` is out of date with the latest version of the [2017 MD chips spec](https://material.io/archive/guidelines/components/chips.html#).
Issue Number: 
Fixes #9883
- use the `md-cancel` button instead of the `md-close` button
- `$chip-font-size` reduced to `13px` from `16px`
- `$chip-remove-padding-right` increased to `28px` from `22px`
- in light mode, remove …
=> fix(chips): update to latest Material Design spec (2017) updates

src/components/chips/chips.scss, src/components/chips/demoBasicUsage/index.html, src/components/chips/demoBasicUsage/style.scss, src/components/chips/js/chipsController.js, src/components/chips/js/chipsDirective.js, src/components/chips/js/contactChipsController.js, src/components/chips/js/contactChipsDirective.js
```
[x] Bugfix
```
Long placeholders get truncated, even when there is room for them to be displayed:
Issue Number: 
Fixes #10630
- add a new `md-input-class` to `md-chips`
to `md-chips` and `md-contact-chips`
- allows custom styling like adding a `min-width` for supporting
very long placeholders
- this is the same API as `<md-autocomplete>` already has
- add demo of long `placeholder` and `md-input-class`
```
[ ] Yes
[x] No …
```
=> fix(chips): placeholder is truncated even though there is room

src/components/select/select.scss
```
[x] Bugfix
```
When a md-select instance is focused, the bottom border do not use the primary color; it appears black.
The md-select instance will now inherit from the colors defined in [select-theme.scss](https://github.com/angular/material/blob/master/src/components/select/select-theme.scss#L99-L100).
```
[ ] Yes
[x] No
```
Issue can be observed on the [demo page of md-select](https://material.angularjs.org/latest/demo/select).
The problem was introduced by commit …
=> fix(select): respect theme color when select has a value and focus

src/components/datepicker/js/calendar.js, src/components/datepicker/js/dateUtil.js, src/components/datepicker/js/datepickerDirective.js
```
[x] Bugfix
```
When local timezone is GMT+X, (i.e. `+5:00`) using `ng-model-options` to specify the timezone causes the previous day to be selected.
Issue Number: 
Fixes #12000
- fix issues with GMT+X timezones by avoiding timezone conversions when local timezone is GMT+x. We let the existing utilities for converting dates to midnight handle things since the date doesn't need to change in those cases, just the hours.
- …
=> fix(calendar, datepicker): fix issues with GMT+X timezones

config/karma-docs.conf.js, config/karma.conf.js, src/components/datepicker/js/dateLocale.spec.js, src/components/datepicker/js/dateUtil.js, src/components/datepicker/js/datepickerDirective.spec.js
```
[x] Bugfix
```
- `$$mdDateUtil.removeLocalTzAndReparseDate()` was simplified, but it breaks MomentJS support
Issue Number: 
Relates to #12003. Relates to #11949.
- revert simplification of `$$mdDateUtil.removeLocalTzAndReparseDate()`
- enable unit testing of MomentJS
- add test suites for MomentJS custom formatting in `dateLocale.spec.js`
and `datepickerDirective.spec.js`
```
[ ] Yes
[x] No
```
=> fix(calendar, datepicker): fix MomentJS custom format support

src/components/radioButton/radio-button.js
```
[x] Bugfix
```
Some users see `TypeError: Cannot read property 'nodeName' of null` when on a page with a `md-radio-button` after they hit the browser's reload button, since AngularJS Material 1.1.1.
Issue Number: 
Fixes #10546
There is a null check before accessing the `parentNode` field.
```
[ ] Yes
[x] No
```
No test added as no reproduction was provided.
=> fix(radio-button): Cannot read property 'nodeName' of null

.github/ISSUE_TEMPLATE.md, README.md, docs/app/partials/home.tmpl.html
```
[ ] Bugfix
```
Our docs say that we build "accessible UI components" but we don't specify any further details.
Issue Number: 
Fixes #11449
- add a list of supported screen readers to docs site
- add screen reader field to issue template
- update browser support table
- update README.md
- require AngularJS 1.7.2+
- remove out of date http://browserl.ist link and image since their site is down
- link to screen reader …
=> docs(a11y): add a list of supported screen readers

package-lock.json, src/components/dialog/demoBasicUsage/script.js, src/components/dialog/dialog.js, src/core/util/animation/animate.js
```
[x] Bugfix
```
In `MdDialogProvider.onRemove()`, we currently call `removeChild()` on the `topFocusTrap` and `bottomFocusTrap` for the dialog and we let the browser handle GC'ing those detached Nodes. But we don't remove the `'focus'` event listeners for each of these Nodes.
Issue Number: 
Relates to #11207. Closes #12010.
- remove focus trap `focus` event listeners in `MdDialogProvider.onRemove()`
- improve JSDoc and …
=> fix(dialog): remove focus trap focus listeners onRemove

src/components/radioButton/radio-button.js
```
[x] Bugfix
```
We don't currently select the current radio button when the space bar is clicked. This doesn't align with the WAI-ARIA recommendations for accessibility.
Issue Number: 
Fixes #11960
- support selection using the space key
- add an incrementSelection enum
- add JSDoc and improve types
- fix typos
```
[ ] Yes
[x] No
```
=> fix(radio-button): support selection using the space key

src/components/select/select-theme.scss
```
[x] Bugfix
```
- In the `md-select` popup, hover and focus background colors are the same. This can cause confusion when navigating with both keyboard and mouse on desktop.
Issue Number: 
Fixes #9851
- use a similar approach to the one used by MDC. I.e. hover is 8% less opaque than focus.
- the opacity values are slightly different because
they use `#000` and we use `rgba(0, 0, 0, 0.87)`
```
[ ] Yes
[x] No
```
No tests …
=> fix(select): in popup, hover and focus background colors are the same

src/core/style/typography.scss
```
[x] Bugfix
```
- long pressing a link doesn't open the context menu on iOS
Issue Number: 
Fixes #10622
- enable iOS long-press context menus
- for links, this allows a range of options to be selected
- for apps that want to disable this to pretend that they are
native mobile apps, they can set the `-webkit-touch-callout: none;`
style on their app's `html, body`
```
[ ] Yes
[x] No
```
=> fix(typography): enable iOS long-press context menus

src/components/icon/demoFontIconsWithClassnames/index.html, src/components/icon/demoFontIconsWithClassnames/script.js, src/components/icon/js/iconDirective.js, src/core/services/aria/aria.js
```
[x] Bugfix
```
- providing empty alt or aria-label attributes do not hide them from a11y as documented
Issue Number: 
Fixes #10721
- change behavior around how `aria-label` and `aria-hidden` is applied
to match documentation
- clarify documentation around `alt` and `aria-label` behavior
- fix/improve Closure types
- remove unused variable and out of date comments
- replace blacklist with block-list in comments
```
[ ] …
```
=> fix(icon): providing empty alt or aria-label attributes do not hide them from a11y

src/components/list/list.js, src/components/list/list.spec.js, src/core/services/aria/aria.js
```
[x] Bugfix
```
When a clickable / linkable `md-list-item` is provided without an `aria-label`, the directive creates a button/link with an `aria-label`. Because this element and the original inner contents are siblings, asking a screen reader to read through the document results in both the created link and the content to be read, which is awkward for screen reader users.
Issue Number: 
Fixes #11582
- if we create an …
=> fix(list): case where list items are read twice by screen readers

src/components/datepicker/js/calendar.js
```
[x] Bugfix
```
- Using the `md-calendar` outside of the `md-datepicker` breaks the page's tab order.
Issue Number: 
Fixes #9794
- using the `md-calendar` outside of the `md-datepicker` no longer breaks the page's tab order
- change one access of the global `document` to use `$document`
- improve Closure types
- update JSDoc for `CalendarCtrl.handleKeyEvent()`
```
[ ] Yes
[x] No
```
=> fix(calendar): allow tabbing out when in standalone mode

src/components/datepicker/js/datepickerDirective.js, src/components/datepicker/js/datepickerDirective.spec.js
```
[x] Bugfix
```
- we don't verify that the model value is not null or undefined before accessing
`.getTimezoneOffset()` and this causes an exception to be thrown in those cases
Issue Number: 
Fixes #12025
- verify that the model value is not null or undefined before accessing
`.getTimezoneOffset()`
```
[ ] Yes
[x] No
```
=> fix(datepicker): null model with timezone throws exception

src/components/dialog/dialog.js
```
[ ] Bugfix
```
Invalid, outdated example code references the ability to hide a specific dialog given a dialog reference.
Issue Number: 
Closes #10562
- remove invalid, outdated example code
- minor refinements to $mdDialog example formatting
```
[ ] Yes
[x] No
```
=> docs(dialog): remove invalid, outdated example code

src/components/input/input.js
```
[x] Bugfix
```
```
TypeError: Cannot read property 'toggleClass' of null
```
Issue Number: 
Fixes #10831
No exception as we check that `containerCtrl.label` is defined before calling `containerCtrl.label.toggleClass('md-required', value && !mdNoAsterisk);`.
```
[ ] Yes
[x] No
```
=> fix(input): check that containerCtrl.label is defined before accessing it

src/components/dialog/dialog.js
```
[ ] Bugfix
```
- "Angular's" is used instead of "AngularJS'"
- There is a typo of `// Mo specific dialog instance reference is needed.`
- rename "Angular's" to "AngularJS'"
- fix 'Mo' typo to be 'No'
```
[ ] Yes
[x] No
```
Relates to #10562
=> docs(dialog): rename "Angular's" to "AngularJS'"

src/components/chips/js/chipsController.js, src/components/chips/js/contactChipsDirective.js
```
[ ] Bugfix
```
- `md-max-chips` is not supported for `md-contact-chips`
Closes #10827
- `md-max-chips` is supported for `md-contact-chips`
```
[ ] Yes
[x] No
```
This continues the work by @kylekatarnls in PR https://github.com/angular/material/pull/10827. It fixes an issue with the value of `md-max-chips` not being properly bound to the template of `md-chips` and cleans up the commit message.
=> feat(chips): md-max-chips support for md-contact-chips

src/components/menu/js/menuServiceProvider.js
```
[x] Bugfix
```
- menu focus is lost when menu-item has custom content and the first child of the `md-menu-item` is a disabled custom element
Fixes #12054
- check that the `firstElementChild` doesn't have the `disabled` attribute set as well
- this supports `ng-disabled` and `disabled` on a custom element
```
[ ] Yes
[x] No
```
=> fix(menu): menu focus is lost when menu-item has custom content

src/components/autocomplete/js/autocompleteController.js, src/components/autocomplete/js/autocompleteDirective.js
```
[ ] Bugfix
```
- Even in apps that are localized to another language, i.e. Spanish, the screen reader announces messages in English like
- 'There are no matches available.'
- 'There is 1 match available.'
- etc.
Fixes #11789
- add 4 APIs for supporting localization of query result announcements
- add docs for new APIs
```
[ ] Yes
[x] No
```
=> feat(autocomplete): allow localization of query result announcements

src/components/datepicker/demoBasicUsage/index.html, src/components/datepicker/demoValidations/index.html, src/components/datepicker/js/datepickerDirective.js
```
[ ] Bugfix
```
- There is no accessible way to associate `ng-messages` with an `md-datepicker`
- There is no accessible way to associate a `<label>` in an `md-input-container` with a `md-datepicker` (also in that same input container)
Fixes #11762
- add input-aria-describedby and input-aria-labelledby
- add docs and demos for new APIs
- change String to string in datepicker param JSDoc
- make the `md-input-container` example …
=> feat(datepicker): add input-aria-describedby and input-aria-labelledby

src/components/select/demoValidations/index.html, src/components/select/select.js
```
[x] Bugfix
```
- md-select's `$isEmpty()` implementation is a naive falsy check of a hashed `Object` and does not check the actual value
Fixes #10005
- change md-select's `$isEmpty()` implementation from a naive falsy check on an `Object`
to a more robust check of the `Object`'s value that is similar to AngularJS' default
- add empty option to validations demo
```
[ ] Yes
[x] No
```
=> fix(select): form remains valid after empty option is selected

src/components/select/select.js, src/components/select/select.scss
```
[x] Bugfix
```
- floating `label` is not displayed when `placeholder` is specified and no selection has been made in a `md-input-container`
Fixes #10116
- don't hide the floating `label` in an `md-input-container` with a `md-select`
that has a `placeholder` attribute specified
```
[ ] Yes
[x] No
```
Given the following:
```html
<md-input-container>
<label>State</label>
<md-select placeholder="Please select" …
```
=> fix(select): floating label hidden w/ placeholder and no value

src/components/dialog/dialog.js, src/core/util/util.js
```
[x] Bugfix
```
-shift+tab gets stuck on the `.md-dialog-container` element and does not cycle back through the tabbable elements
Fixes #10963
- don't let shift+tab get stuck on the `.md-dialog-container` element
- the new behavior of shift+tab matches Angular Material and the CDK
- the old behavior, of tab stopping on the `.md-dialog-container` element as part of
the tabindex cycle of a dialog, remains
- this differs from …
=> fix(dialog): shift+tab does not cycle through tabbable elements

src/components/autocomplete/js/autocompleteController.js
```
[X] Bugfix
```
When user click on suggestion item, input element lost focus, and then programmatically get focused again, in between these moments invalid state flashes
Also described in https://github.com/angular/material/issues/10975
Fixes #10975
Invalid state doesn't flash
```
[ ] Yes
[X] No
```
Perhaps you can help me, my branch fails the test in autocomplete.spec.js "shows the md-not-found template even if we have lost …
=> fix(autocomplete): prevent flashing of invalid state

src/components/fabActions/fabActions.js, src/components/fabActions/fabActions.spec.js
```
[x] Bugfix
```
- action item buttons in a closed `md-fab-speed-dial` are part of the tab order
- this can also cause tooltips to appear (if the buttons have tooltips) that aren't connected to anything
Fixes #10101
- apply `tabindex="-1"` to all `md-button`s in the `md-fab-actions`
```
[ ] Yes
[x] No
```
=> fix(fab-speed-dial): action items are in tab order when closed

src/components/button/button.scss, src/components/fabSpeedDial/demoBasicUsage/style.scss, src/components/fabSpeedDial/fabController.js, src/components/fabSpeedDial/fabSpeedDial-theme.scss, src/components/fabSpeedDial/fabSpeedDial.js, src/components/fabSpeedDial/fabSpeedDial.spec.js, src/components/fabToolbar/fabToolbar.scss, src/core/util/util.js
```
[x] Bugfix
```
- `md-fab-speed-dial` still triggers action when button inside of `md-fab-trigger` is `disabled`
- `md-fab` buttons have `box-shadow` when `disabled`
Fixes #9467
- when the trigger is clicked, verify that the trigger button isn't disabled
before toggling the open state
- style the disabled speed dial trigger fab button using the current theme
to support both light and dark themes
- fix issue where the disabled …
=> fix(fab-speed-dial): opens when trigger button is disabled

src/components/button/demoBasicUsage/index.html, src/components/fabSpeedDial/demoBasicUsage/index.html, src/components/fabSpeedDial/fabController.js, src/components/fabSpeedDial/fabSpeedDial-theme.scss, src/components/fabSpeedDial/fabSpeedDial.js, src/components/fabToolbar/fabToolbar.js
```
[x] Bugfix
```
- If you switch between navigating through the speed dial actions from arrow buttons to tabs, the ordering is messed up and some options become impossible to reach with tab navigation.
- It's not possible to visually see which action item has focus when using a dark theme
Fixes #12043
- add code to handle Tab and Shift+Tab keyboard interactions
- rip out old an inaccessible `tabindex` shifting code
- use a more …
=> fix(fab-speed-dial): keyboard navigation issues with tab and shift+tab

src/components/menu/js/menuServiceProvider.js, src/components/menu/menu.spec.js
- attach the backdrop in menu to `options.backdropParent`
backdrop in menu now attaches to `options.backdropParent` if passed, previously it was always attached to `document.body`
```
[ ] Bugfix
```
Backdrop is always rendered to `document.body`.
Backdrop now renders to `options.backdropParent` if provided.
```
[] Yes
[x] No
```
Menu backdrop was always rendered to `document.body` even if we pass `options.parent`(which is used to …
=> feat(menu): render backdrop to parent

src/components/datepicker/js/datepickerDirective.js, src/components/datepicker/js/datepickerDirective.spec.js
```
[x] Bugfix
```
- valid ISO 8601 dates are decorated as invalid in forms
Fixes #12075
- when in `updateErrorState()`, we make sure that ISO 8601 strings are parsed to dates
- valid ISO 8601 dates are decorated as valid in forms
```
[ ] Yes
[x] …
```
=> fix(datepicker): ISO 8601 dates decorated as invalid in forms

package-lock.json, package.json
```
[ ] Bugfix
```
- before: found 64 vulnerabilities (1 low, 43 moderate, 17 high, 3 critical)
Relates to https://github.com/angular/angular.js/issues/17163. Relates to #11881. Relates to #12111.
- Use a resolution override for `marked` to be …
=> docs(api): fix API docs rendering

gulp/config.js, src/components/bottomSheet/bottom-sheet.scss, src/components/button/button.scss, src/components/card/card.scss, src/components/chips/chips.scss, src/components/datepicker/datePicker.scss, src/components/fabSpeedDial/fabSpeedDial.scss, src/components/fabToolbar/fabToolbar.scss, src/components/input/_input-variables.scss, src/components/input/input.scss, src/components/list/list.scss, src/components/menu/menu.scss, src/components/progressLinear/progress-linear.scss, src/components/select/select.scss, src/components/slider/slider.scss, src/components/switch/switch.scss, src/core/services/layout/layout-attributes.scss, src/core/style/_mixins.scss, src/core/style/_variables.scss, src/core/style/layout.scss
```
[ ] Bugfix
[x] Other... Please describe: Fixing the output for scss builds
```
When building with newer SASS version we get this deprecation message and many others :
```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0. …
```
=> build: fix SCSS division deprecation

.circleci/config.yml, gulp/config.js, gulp/util.js, package-lock.json, scripts/gulp-utils.js, src/core/style/_modules.scss, src/core/style/_variables.scss
```
[ ] Bugfix
```
- module builds were broken by PR https://github.com/angular/material/pull/12112
- fixes module builds broken by PR https://github.com/angular/material/pull/12112
- break module imports out into a separate file since it behaves …
=> chore(sass): fix module builds

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/docs.md, .github/PULL_REQUEST_TEMPLATE.md, LICENSE, README.md, docs/app/partials/getting-started.tmpl.html
```
[ ] Bugfix
```
- The README 
- lists LTS details that have expired
- doesn't mention the EOL status
- has docs for contributing, but we aren't accepting any contributions
- links to the forums and Gitter for official support, which is no longer available
- change LTS section of README to an End-of-Life section
- remove LTS details
- add link to AngularJS EOL blog post
- remove release and contributing docs from README
- …
=> docs(eol): updates for End-of-Life

SECURITY.md, docs/app/css/style.css, docs/app/partials/getting-started.tmpl.html, docs/app/partials/home.tmpl.html, docs/config/template/index.template.html, package-lock.json, package.json
```
[ ] Bugfix
```
- Many parts of the site and the `SECURITY.md` file are out of date due to the end of the LTS period.
- There are some issues running `npm i` in the project with npm v8
- https://github.com/angular/material/pull/12146
- fix alignment of text in banner
- update home page for EOL
- update banner messaging for EOL
- update `SECURITY.md` for EOL
- update `package-lock.json` to v2
- add `path-type` devDependency …
=> docs(eol): update docs website for End-of-Life
