angular/material

- src/components/virtualRepeat/virtualRepeater.js
- src/components/virtualRepeat/virtualRepeater.spec.js
maximum element size.
@kseamon
> feat(virtualRepeat): allow for scrolling areas larger than the browser's

- src/components/input/input.js
- src/components/input/input.spec.js
> fix(input): fix bad label initialization when using static value. Fixes #3599

- src/components/datepicker/calendar.js
- src/components/datepicker/calendar.spec.js
- src/components/datepicker/calendarMonth.js
- src/components/datepicker/dateLocaleProvider.js
@ThomasBurleson @robertmesserle Please sanity check the way I'm doing this.
> feat(datepicker): allow changing first day of the week. Fixes #4316.

- src/components/datepicker/datePicker.js
- src/components/datepicker/datePicker.scss
- src/components/datepicker/datePicker.spec.js
@robertmesserle @rschmukler for review
Approach is pretty basic, it's possible I'm not thinking of something.
> feat(datepicker): prevent calendar from going off-screen. Fixes #4333.

- src/components/datepicker/dateUtil.js
- src/components/datepicker/dateUtil.spec.js
> fix(dateLocale): guard for setting midnight to null. Fixes #4780

- src/components/datepicker/datePicker.js
- src/components/datepicker/datePicker.spec.js
> fix(datepicker): prevent calendar clipping on small screens. For #4558

- src/components/datepicker/datePicker.js
- src/components/datepicker/datePicker.spec.js
> fix(datepicker): stop calendar going off-screen if body is scrollable.  Fixes #4781

- src/components/checkbox/checkbox.js
- src/components/checkbox/checkbox.spec.js
Also did some clean-up on checkbox tests where I couldn't help myself.
> fix(checkbox): prevent ng-click firing on didabled checkboxes. Fixes #4879

- src/components/input/input.js
- src/components/input/input.spec.js
Also did some cleanup on the unit tests.
> fix(input): fix bad char counter when value is a number. Fixes #4635.

- src/components/autocomplete/autocomplete-theme.scss
- src/components/datepicker/datePicker.js
- src/components/datepicker/datePicker.spec.js
> fix(datepicker): properly set ngModel validity. Fixes #4926

- src/components/datepicker/datePicker.js
- src/components/datepicker/datePicker.spec.js
> fix(datepicker): throw error if inside md-input-container. For #5055

- src/components/datepicker/datePicker.js
- src/components/datepicker/datePicker.spec.js
> fix(datepicker): throw error if model is not a Date. For #5266

- src/components/datepicker/datePicker.js
- src/components/datepicker/datePicker.spec.js
> fix(datepicker): correctly position datepicker inside dialogs.

- src/components/datepicker/datePicker.js
- src/components/datepicker/datePicker.spec.js
- src/components/datepicker/demoBasicUsage/index.html
Fixes #5315
@mhchen or @robertmesserle for review.
> fix(datepicker): improve error state updating. Fixes #5315

- src/components/datepicker/datePicker.js
> fix(datepicker): fix not closing on body-click on iOS Safari. Fixes #5914

- src/components/dialog/dialog.js
- src/components/dialog/dialog.spec.js
> fix(dialog): trap focus within dialog. Fixes #4105.

- src/components/virtualRepeat/virtual-repeater.js
Thanks to @tonyawad88 for finding this fix!
cc @kseamon
> fix(virtualRepeat): update deps to include showHide. Fixes #4435.

- src/components/datepicker/datePicker.js
- src/components/datepicker/datePicker.spec.js
@mhchen for review
Fixes #6622
> fix(datepicker): use time-insensitive comparison for min/max.

- src/components/datepicker/datePicker.js
- src/components/datepicker/datePicker.spec.js
> fix(datepicker): fix input always being required.

- src/components/chips/chips-theme.scss
- src/components/chips/chips.scss
- src/components/chips/demoBasicUsage/index.html
- src/components/chips/demoBasicUsage/script.js
- src/components/chips/js/chipController.js
- src/components/chips/js/chipDirective.js
- src/components/chips/js/chipsController.js
- src/components/chips/js/chipsDirective.js
> feat(chips): Make chips editable

- src/components/panel/panel.js
- src/components/panel/panel.scss
- src/components/panel/panel.spec.js
@gmoothart @ErinCoughlan @jelbourn @DerekLouie 
Please review.
Fixes issue #7116
> update(panel): Add show and hide to mdPanelRef. Cleaned up open and close.

- src/components/panel/panel.js
- src/components/panel/panel.spec.js
@gmoothart @ErinCoughlan @jelbourn @DerekLouie
Please review.
Fixes issues #7195 and #7194.
> feat(panel): Add clickOutsideToClose and escapeToClose config options to the panel.

- src/components/panel/demoBasicUsage/panel.tmpl.html
- src/components/panel/panel.js
- src/components/panel/panel.spec.js
@gmoothart @DerekLouie @jelbourn @ErinCoughlan 
Please review.
Fixes issue #7465
> feat(panel): Add focusOnOpen config option to the panel.

- src/components/panel/demoBasicUsage/script.js
- src/components/panel/panel.js
- src/components/panel/panel.scss
- src/components/panel/panel.spec.js
@ErinCoughlan @gmoothart @DerekLouie @jelbourn 
Please review.
Fixes issue #7684.
> feat(panel): Add fullscreen config option to the panel.

- src/components/panel/panel.js
- src/components/panel/panel.spec.js
@jelbourn @DerekLouie @gmoothart @KarenParker Please review.
Fixes #7466
> update(panel): Adds relative positioning config.

- src/components/panel/panel.js
@ErinCoughlan @gmoothart @DerekLouie @jelbourn 
Please review.
Fixes #7701, #7702, and #7703
> feat(panel): Add default slide/scale/fade/none animations and custom animations and withAnimation API method.

- src/components/panel/demoPanelAnimations/script.js
- src/components/panel/panel.js
> update(panel): Fix the broken merge.

- src/components/panel/demoBasicUsage/script.js
- src/components/panel/panel.js
- src/components/panel/panel.spec.js
Fixes #7794, #7877 
@jelbourn @KarenParker @gmoothart @DerekLouie Please review.
> update(panel): Adds absolute positioning with center.

- src/components/panel/panel.js
- src/components/panel/panel.spec.js
@jelbourn @KarenParker Please review. This follows the Angular 2 method of setting absolute positioning.
> update(panel): Clear previously set positions.

- src/components/panel/demoBasicUsage/script.js
- src/components/panel/demoPanelAnimations/script.js
- src/components/panel/panel.js
- src/components/panel/panel.spec.js
@KarenParker @gmoothart @DerekLouie @jelbourn Please review.
Offsets can be used in combination with any of the other positioning options, including centering.
Fixes #7193
> feat(panel): Add offsetX and offsetY.

- src/components/panel/panel.js
Fixes: #7874.
@ErinCoughlan @jelbourn @gmoothart @DerekLouie Please review.
> feat(panel): Add $animate.pin to the panel.

- src/components/panel/panel.js
- src/components/panel/panel.spec.js
Fixes the problem of not resetting the defaults when there are multiple panels.
@ErinCoughlan @jelbourn @gmoothart @DerekLouie @ThomasBurleson  Please review.
> update(panel): Support multiple panels and clean up some code.

- src/components/panel/demoBasicUsage/index.html
- src/components/panel/demoBasicUsage/script.js
- src/components/panel/demoBasicUsage/style.css
- src/components/panel/panel.js
- src/components/panel/panel.spec.js
Also changes tests to compare actual position values instead of blindly checking for whatever was set in CSS.
Fixes #7681
@ThomasBurleson @jelbourn @KarenParker @gmoothart @DerekLouie Please review.
> update(panel): Add a demo for a menu using the panel.

- src/components/backdrop/backdrop.scss
- src/components/panel/demoBasicUsage/script.js
- src/components/panel/demoPanelAnimations/script.js
- src/components/panel/panel-theme.scss
- src/components/panel/panel.js
- src/components/panel/panel.scss
- src/components/panel/panel.spec.js
- src/core/style/variables.scss
Fixes #7682.
@gmoothart @ErinCoughlan @DerekLouie @jelbourn Please review.
> feat(panel): Add hasBackdrop config to the panel.

- src/components/panel/panel.js
@ThomasBurleson I merged PR #8123 before I addressed your comment. Please review this and feel free to leave any other comments on the files. I can address them here.
The promise stuff is being changed as we speak, but everything else should be stable.
> docs(panel): Update class name in docs.

- src/components/panel/demoBasicUsage/index.html
- src/components/panel/demoBasicUsage/script.js
- src/components/panel/panel.js
- src/components/panel/panel.spec.js
- src/core/util/util.js
This adds a config to the panel which disables scrolling of the panel's
parent (attachTo) element, if set.
Part of #7683
> update(panel): Adding disableParentScroll

- src/components/panel/demoPanelAnimations/panel.tmpl.html
- src/components/panel/demoPanelAnimations/script.js
> feat(panel): fix dialog close button in animation demo

- src/components/panel/panel.js
- src/components/panel/panel.spec.js
@ErinCoughlan @gmoothart @jelbourn @DerekLouie @ThomasBurleson  Please review.
> feat(panel): Clean up promises

- src/components/panel/demoPanelAnimations/script.js
- src/components/panel/demoPanelAnimations/style.css
- src/components/panel/panel.js
> fix(panel): Fixes custom animations in the demo to account for opacity.

- src/components/panel/panel.js
- src/components/panel/panel.spec.js
- test/angular-material-spec.js
Hello,
@gmoothart @ErinCoughlan @KarenParker @ThomasBurleson 
Here is a small PR to update the panels close functionality.
The user can also now specify an element / selector to focus on after the panel closes.
Minor bug fixes as well.
Closes #7902
Please Review.
>  update(panel): Updates the detach / close code to focus on close.

- src/components/panel/demoBasicUsage/script.js
- src/components/panel/panel.js
- src/components/panel/panel.spec.js
Fixes #7897
@KarenParker @gmoothart @DerekLouie @ThomasBurleson @jelbourn Please review.
> feat(panel): Update the panel position on scroll.

- src/components/panel/demoBasicUsage/panel.tmpl.html
- src/components/panel/demoBasicUsage/script.js
- src/components/panel/demoPanelAnimations/panel.tmpl.html
- src/components/panel/panel.js
- src/components/panel/panel.spec.js
- test/angular-material-spec.js
Looks through all positions supplied by the user, and picks the first one which is on-screen. If none are on-screen, the last one will be chosen. Part of #7878
@ErinCoughlan @KarenParker @ThomasBurleson @jelbourn @DerekLouie
> update(panel): choose first positioning that is on-screen.

- src/components/panel/panel.js
- src/components/panel/panel.scss
> fix(panel): Remove overflow: auto from panel.

- src/components/panel/panel.js
Closure compiler was angry. This makes it happy again.
@KarenParker @gmoothart Please review.
> fix(panel): Fix type annotations.

- release.js
> update(release): release candidates will be published to npm and docs site

- src/components/colors/colors.js
- src/components/dialog/dialog.js
- src/components/subheader/subheader.js
- src/core/services/layout/layout.js
- src/core/services/theming/theming.js
- src/core/util/animation/animate.js
Fixes the linter warnings in: colors, dialog, subheader, layout, theming, animate.
Referencing #9153.
> chore(colors, dialog, subheader, layout, theming, animate): fix linter warnings

- src/components/navBar/navBar.js
* Register theming service on navbar directive linking
Fixes #9137
> fix(navbar): add theming support

- src/components/autocomplete/autocomplete.spec.js
- src/components/autocomplete/js/autocompleteController.js
> fix(autoComplete): don't use $mdUtil.nextTick in handleHiddenChange

- src/core/services/theming/theming.js
- src/core/services/theming/theming.spec.js
This reverts commit 0d2386c7b446707078572fd7acf2b1b8ada58099.
> Revert "feat(themes): register theme on the fly (#9413)"

- src/components/panel/panel.js
> Fix documentation for MdPanelAnimation.

- src/components/list/list.js
- src/components/list/list.spec.js
* This allows developers to disable proxy elements inside of an list item.
Closes #9423,
> feat(list): add class to disable proxy elements.

- src/components/fabToolbar/fabToolbar.js
made the description more grammatically correct.
> docs(fabToolbar): edited the description

- src/components/bottomSheet/bottom-sheet.spec.js
Nit: fixing test description for clickOutSideToClose=true
> Fix test description for bottom-sheet.spec.js

- src/core/services/compiler/compiler.js
This is a left-over from 0397e29.
> refactor($mdCompiler): remove redundant code

- src/components/autocomplete/js/autocompleteDirective.js
* There was no explicit mentioning of how the way async queries are working inside of the autocomplete (only a demo)
Closes #9501
> docs(autocomplete): more details on async queries

- package.json
**Note**: #9742 also includes this fix, but this is something which is important and this should be fixed ASAP.
> See for example #9774
> chore: add karma chrome launcher

- src/components/card/card.js
This looks like this bullet was unintentionally nested.
> Ordering for `md-media-xl`

- docs/config/template/index.template.html
> docs(): add tooltip to back to top fab

- src/components/panel/panel.spec.js
Fixes a failing unit test that is currently breaking the CI.
> chore(panel): fix failing unit test

- src/core/services/theming/theming.js
Change default primary palette to blue.
> Correct documentation

- src/components/panel/demoGroups/index.html
- src/components/panel/demoGroups/script.js
- src/components/panel/panel.js
- src/components/panel/panel.spec.js
The groupName parameter has been changed from allowing only a string to allowing a string or an array of strings. All of the necessary functionality has been changed to accompany the array.
Fixes #9565
Ping @ErinCoughlan @crisbeto and @DerekLouie for review.
> feat(panel): Allow panels to be part of multiple groups.

- scripts/sauce/setup-tunnel.sh
* Updates the sauce connector binaries to the latest version
> chore: update sauce connector version

- src/components/menu/js/menuDirective.js
* remove an unnecessary character
> docs(menu): fix spelling error

- src/components/switch/demoBasicUsage/index.html
- src/components/switch/switch.js
- src/components/switch/switch.scss
- src/components/switch/switch.spec.js
- Adds an attribute which invertes the switch when set to true
Fixes #7889
> feat(switch): add attribute to invert the switch

- src/components/autocomplete/autocomplete.spec.js
- src/components/autocomplete/js/autocompleteController.js
- The autocomplete right now always re-positions the virtual repeat containers while the autocomplete is hidden.
- This is unecessary because the autocomplete will automatically position itself upon open.
> ﻿fix(autocomplete): reduce unecessary re-positioning calls

- src/core/services/interimElement/interimElement.js
> update(interimElement): added missing scope dispose to fix memory leak

- src/components/progressCircular/js/progressCircularDirective.js
SVG arc was not properly sized which caused it to bleed through it's container.
In some configurations, the circle would be cropped
* Account for strokeWidth when measuring dash length
* Set offset in arc path equal to half of stroke width
Fixes #10107
> fix(progressCircular): fix arc bleeding through container

- .travis.yml
- config/karma-sauce.conf.js
- scripts/fetch-angular-version.sh
- scripts/sauce/setup-tunnel.sh
- scripts/test-versions.sh
- scripts/travis-run-script.sh
- src/components/input/input.spec.js
* Now runs unit tests against Angular snapshot
* Exported the version download script from the `test-versions.sh` script from Jenkins (allows us to test against snapshot)
> chore: run tests against angular snapshot

- scripts/test-versions.sh
> chore(test-versions): run tests against Angular v1.6

- src/components/panel/panel.js
@jelbourn @tinayuangao I think this should fix the positioning bug. Will run the presubmit and verify.
> [MdPanel] Fix offscreen positioning bug

- src/components/select/select.js
Fixed https://github.com/angular/material/issues/9894.
I added $mdTheming in OptionDirective.
> mdSelect: Fix theming of mdOption element 

- src/components/navBar/navBar-theme.scss
* Add support for md-accent, md-warn and md-primary classes
fixes #8827
> feat(navBar): Add missing styling for md-primary and md-accent

- src/components/chips/js/chipsDirective.js
> corrected "hilighting"to "highlighting"

- src/components/navBar/demoBasicUsage/index.html
- src/components/navBar/demoBasicUsage/script.js
Fixes https://github.com/angular/material/issues/10422
> fix(demo): fix Goto()

- scripts/sauce/setup-tunnel.sh
* Updates the Saucelabs Tunnel connector to the latest version
> chore: update saucelabs tunnel connector

- src/components/menu/demoCustomTrigger/index.html
> docs(menu): add  `md-menu-content` closing tag at demoCustomTrigger

- src/components/menu/menu.scss
> fix(menu): prevent menu from being larger than the viewport

- src/components/input/input.js
- src/components/input/input.spec.js
> fix(input): Fix placeholder text being read twice by screen readers.

- package-lock.json
- package.json
- upgrade gulp-sass
- added package-lock
- added `npm run dev`
> chore(build): support node 8

- src/components/icon/icon.spec.js
> fix(icon): fix malformed HTML in tests

- package-lock.json
- package.json
- scripts/write-presubmit-scheduler.js
This will make it easier for us to schedule presubmit runs during off-peak hours
> chore: add script to generate a script to schedule presubmit runs

- src/components/slider/slider.js
- src/components/slider/slider.spec.js
> fix(slider): role was applied to inner element instead of the directive itself

- src/components/truncate/truncate.js
See https://github.com/angular/material/issues/10356#issuecomment-306720799 for details
Fixes #10356
> fix(truncate): remove controllerAs/bindToController directive attributes

- src/components/icon/js/iconDirective.js
> docs(icon): fix typo

- docs/app/js/app.js
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
Currently the docs site spams the console with useless messages about navigation and more.
Issue Number: 
N/A
Docs site no longer spams the console with navigation or event logs.
```
[ ] Yes
[x] No
```
N/A
> docs(angularytics): disable console logging

- package-lock.json
```
[ ] Bugfix
[ ] Feature
```
We found a potential security vulnerability in a repository which you have been granted security alert access.
@angular    angular/material
Known moderate severity security vulnerability detected in marked < 0.3.9 defined in package-lock.json.
package-lock.json update suggested: marked ~> 0.3.9.
Always verify the validity and compatibility of suggestions with your codebase.
Issue Number: 
Relates to #11049.
No …
> build: fix security warning from using old version of marked library

- README.md
- docs/app/partials/home.tmpl.html
```
[ ] Bugfix
[ ] Feature
```
Out of date documentation.
Issue Number: 
N/A
Rewrite of primary project readme to be accurate and reflect the current state of the project
add links to docs home
improve clarity of docs home
fix AngularJS vs Angular mistake in docs home
remove the reference to the "recent" v1 release in docs home
```
[ ] Yes
[x] No
```
N/A
> docs(readme,home): major update to the readme

- src/components/menuBar/demoBasicUsage/index.html
- src/components/menuBar/demoBasicUsage/script.js
- src/components/menuBar/demoBasicUsage/style.scss
- src/components/menuBar/demoDynamicNestedMenus/index.html
- src/components/menuBar/demoDynamicNestedMenus/script.js
- src/components/menuBar/demoDynamicNestedMenus/style.scss
```
[ ] Bugfix
[ ] Feature
```
There have been reports of issues with dynamic menus, but users have not been able to submit demos with their reports. There is no demo that demonstrates dynamic nested menus in a menuBar.
Issue Number: 
#10595
I needed to build this demo to try to reproduce various issues. I want to make this demo available now so that it can be used as a basis for future CodePen's related to dynamic menus in menuBars.
```
[ …
```
> docs(menuBar): add dynamic nested menus example

- config/build.config.js
```
[ ] Bugfix
[ ] Feature
```
Documentation site is running Angular 1.5.5. This is partially due to full AngularJS 1.6.x support not being ready until AngularJS Material 1.1.4.
Issue Number: 
N/A
Documentation site is running Angular 1.6.7. All AngularJS 1.6.x issues are closed. Nice to jump up to this version before AngularJS 1.7.x is released as well. If there are any undiscovered AngularJS 1.6.x related issues, hopefully they will be …
> docs: update to Angular 1.6.7

- docs/guides/CODING.md
```
[ ] Bugfix
[ ] Feature
```
Formatting was broken by a change in GitHub's Markdown engine.
Issue Number: 
N/A
Formatting works properly.
```
[ ] Yes
[x] No
```
N/A
> docs(coding): fix formatting

- CHANGELOG.md
```
[ ] Bugfix
[ ] Feature
```
No contributors list for 1.1.7 release.
Issue Number: 
N/A
Contributors list exists for 1.1.7 release.
```
[ ] Yes
[x] No
```
N/A
> docs(changelog): add contributors for 1.1.7 release

- src/components/autocomplete/js/autocompleteDirective.js
```
[ ] Bugfix
[ ] Feature
```
There are confusing typos and inconsistent formatting.
Issue Number: 
N/A
Typos and inconsistencies resolved.
```
[ ] Yes
[x] No
```
N/A
> docs(autocomplete): fix typos and inconsistencies

- README.md
fixes #11141
```
[ ] Bugfix
[ ] Feature
```
The links point to a site that gives "Forbidden - This repo/gist is on the blacklist. If you wish to appeal, please open an issue here: https://github.com/schme16/gitcdn.xyz/issues, with why you feel this repo should not be on the blacklist."
Issue Number: 
#11141
The links point to GitCDN URLs that work.
```
[ ] Yes
[x] No
```
N/A
> docs(readme): update GitCDN links

- src/components/checkbox/checkbox.js
- src/components/select/select.js
- src/components/switch/switch.js
```
[ ] Bugfix
[ ] Feature
```
md-select docs do not include `ng-change`
Issue Number: 
Requested in https://github.com/angular/material/issues/1576#issuecomment-82947957.
Relates to #1576
md-select docs include `ng-change`.
```
[ ] Yes
[x] No
```
update ng-model and ng-change types and descriptions
update checkbox and switch for consistency as well
> docs(select): add docs for ng-change

- src/components/dialog/dialog.js
```
[ ] Bugfix
[ ] Feature
```
Missing "with"
Issue Number: 
Closes #11157
Added missing word.
```
[ ] Yes
[x] No
```
N/A
> docs(dialog): fix typo

- docs/app/partials/getting-started.tmpl.html
```
[ ] Bugfix
[ ] Feature
```
Getting Started Guide is out of date and includes links to broken blog posts, etc.
Issue Number: 
Relates to #11187.
replace links to broken blog posts and old URLs
add link to free AngularJS Material course on Egghead.io
add more CodePen links and change out of date image to an iframe
add a note about ngMessages being required by md-input and others
update link and info about Ionic
make it more clear that …
> docs(getting-started): update links and information

- src/core/services/gesture/gesture.js
```
[ ] Bugfix
[ ] Feature
```
missing Gesture service and method docs
typos
weak comparisons
type definition errors
Issue Number: 
Closes #11196. Closes #1546.
add missing Gesture service and method docs
fix typos and comparisons
fix type definition
```
[ ] Yes
[x] No
```
N/A
> docs(gesture): add missing service and method docs

- docs/app/partials/getting-started.tmpl.html
```
[ ] Bugfix
[ ] Feature
```
The iframe doesn't load and throws a security exception in the console.
Issue Number: 
N/A
The iframe loads properly.
```
[ ] Yes
[x] No
```
use HTTPS URLs
> docs(getting-started): fix blocked iframes

- src/components/chips/chips.spec.js
- src/components/chips/demoValidation/index.html
- src/components/chips/demoValidation/script.js
- src/components/chips/demoValidation/style.css
- src/components/chips/js/chipsController.js
- src/components/chips/js/chipsDirective.js
```
[x] Bugfix
[x] Feature
```
#11125 had to be reverted due to regression #11217.
Issue Number: 
#11217
This includes #11125 plus the regression fix for #11217.
```
[ ] Yes
[x] No
```
N/A
> feat(md-chips): re-added validation for ng-required

- src/core/services/compiler/compiler.js
```
[ ] Bugfix
[ ] Feature
```
Some typos and unclear guidance.
Issue Number: 
Relates to #11255.
Address these issues identified in the code review of https://github.com/angular/material/pull/11255. Thanks to @mgol and @gkalpak for the review!
```
[ ] Yes
[x] No
```
N/A
> docs(mdCompilerProvider): refinements for clarity

- docs/content/performance/internet-explorer.md
- package-lock.json
- package.json
- src/components/datepicker/js/dateLocaleProvider.js
- src/components/datepicker/js/datepickerDirective.js
```
[ ] Bugfix
```
There are a number of typos in the comments and documentation.
The datepicker mentions the `$mdDateLocaleProvider` but doesn't link to it.
The `$mdDateLocaleProvider` docs use a lot of invalid type descriptions for properties.
There are out of date TODOs in the datepicker code.
Issue Number: 
N/A
- add link from $mdDateLocaleProvider to mdDatepicker
- add link from mdDatepicker to $mdDateLocaleProvider
- …
> docs(datepicker): fix invalid property types, typos

- src/components/autocomplete/js/autocompleteDirective.js
- src/components/virtualRepeat/virtual-repeater.js
```
[ ] Bugfix
```
Typos, missing explanations, out of date comments, etc.
Issue Number: 
Closes #11280.
- fix typos
- fix invalid types
- remove out of date TODO
- fix invalid comments
- add missing JSDoc
- add link to CSP
```
[ ] Yes
[x] No
```
N/A
> docs(virtualRepeat): clean up and clarify

- src/components/tabs/js/tabsDirective.js
```
[ ] Bugfix
```
md-tabs docs don't link to md-tab docs.
Some typos and other issues.
Issue Number: 
Closes #10947
- add link to md-tab
- fix typos
- clarify text
```
[ ] Yes
[x] No
```
> docs(tabs): clean up and refinements

- .travis.yml
```
[ ] Bugfix
```
We test against AngularJS 1.5 and 1.6.
Issue Number: 
N/A
We test against AngularJS 1.6 and 1.7.
```
[ ] Yes
[x] No
```
> build(travis): run tests against AngularJS 1.7

- src/core/services/ripple/ripple.js
Issue Number:  #11069
http://streaka.testing.videos.s3.amazonaws.com/screencast_2018-05-29_14-38-08.mp4
Issue doesn't occur anymore, seems fine
> fix(ripple): cleanup ripple even when the touch is very quick on iOS

- src/components/datepicker/calendar-theme.scss
Closes #11265
example of issue: https://codepen.io/anon/pen/GdrKPp?editors=1010
```
[x] Bugfix
```
https://codepen.io/anon/pen/GdrKPp?editors=1010
In dynamic multi theme scenario we have light background of `datepicker` in dark theme.
This issue only appear in multi theme scenario. With single default dark theme doesn't appear.
Issue Number: 
#11265 
In multi theme scenario we should have dark background of `datepicker` in …
> fix(datepicker): calendar panel supports multi theme scenario

- src/core/services/theming/theming.js
```
[x] Bugfix
```
Issue Number: 
Fixes #11325
- Only register a theme name watcher if we are watching for theme changes or it is an async theme.
- Use element's scope to listen for $destroy events instead of the element.
- Move the `$destroy` event handler outside of the watcher.
```
[ ] Yes
[x] No
```
> fix(theming): md-theme leaks when child elements are removed

- README.md
docs(typo): an screenshot-> a screenshot
There is a typo in the README.md file on line 25 "an screenshot", should be "a screenshot".
```
[ ] Bugfix
[X] Documentation content changes
```
There is a typo in the README.md file on line 25 "an screenshot", should be "a screenshot".
Issue Number: 
a screenshot
```
[ ] Yes
[X] No
```
Just a typo fix
> docs(typo): an screenshot-> a screenshot

- docs/app/js/codepen.js
```
[ ] Bugfix
```
```
Copyright 2018 Google Inc. All Rights Reserved. 
Use of this source code is governed by an MIT-style license that can be foundin the LICENSE file at http://material.angularjs.org/HEAD/license.
```
Issue Number: 
#11187
```
Copyright 2018 Google Inc. All Rights Reserved. 
Use of this source code is governed by an MIT-style license that can be found
in the LICENSE file at …
```
> docs(codepen): fix missing line break in Copyright

- src/components/menu/demoMenuPositionModes/script.js
- src/components/menu/demoMenuWidth/index.html
- src/components/menu/demoMenuWidth/script.js
```
[ ] Bugfix
```
Broken link to MD spec in one of the menu demos.
Issue Number: 
Fixes #9959
Link is fixed.
```
[ ] Yes
[x] No
```
> docs(menu): fix broken link to spec

- src/core/services/theming/theming.js
```
[ ] Bugfix
```
Issue Number: 
Relates to #10044
```
[ ] Yes
[x] No
```
Also fixed some minor line length issues.
> docs(theming): fix invalid JSDoc syntax

- src/components/virtualRepeat/virtual-repeater.js
- src/core/util/util.js
```
[ ] Bugfix
```
There is invalid JSDoc, missing JSDoc, and lint issues. 
Issue Number: 
N/A
JSDoc is improved.
Link issues resolved.
```
[ ] Yes
[x] No
```
> refactor(virtual-repeat,util): lint and JSDoc cleanup

- src/components/select/select.js
This is to fix a problem with loosing the focus and not allowing
the keys to navigate through the options displayed in the dropdown menu.
Fixes #11357
```
[x] Bugfix
```
While loading the options asynchronously the focus is on the spinner.
When completed, the spinner is removed together with the focus.
Because of it the arrow keys cause search to be run again rather than allowing navigation within dropdown menu.
Issue …
> fix(select): give focus to the first option when loaded asynchronously

- src/components/list/list.js
```
[ ] Bugfix
```
current example causes confusion that it can be used with images
it also uses an icon set that is not defined in the docs site
Issue Number: 
Fixes #10382
uses an icon set defined on the docs site
uses an icon that is clearly an icon and not a possible image
```
[ ] Yes
[x] No
```
> docs(list): clarify that md-avatar-icon is for use with icons

- config/build.config.js
```
[ ] Bugfix
```
Docs run AngularJS 1.6.7
Issue Number: 
N/A
Docs run AngularJS 1.7.2
```
[ ] Yes
[x] No
```
> chore(docs): update from AngularJS 1.6.7 to 1.7.2

- src/components/autocomplete/autocomplete-theme.scss
> fix(autocomplete): apply theming to input element

- src/components/panel/panel.js
```
[ ] Bugfix
```
Some of the code in the example was getting parsed to `&amp;&amp;`.
Issue Number: 
N/A
Fixed to not use `&&` in this example.
```
[ ] Yes
[x] No
```
> docs(panel): fix ampersands getting parsed into &amp;

- src/components/tabs/demoDynamicTabs/index.html
- src/components/tabs/demoDynamicTabs/script.js
- src/components/tabs/demoDynamicTabs/style.scss
- src/components/tabs/js/tabsController.js
```
[ ] Bugfix
```
- the demo JS has lots of inline styles that make the example harder to read
- the demo styles are in SCSS but it's just pure CSS
- the demo styles have unused rules
- adjustOffset()'s JSDoc indicates that the param is required when it is actually optional
Issue Number: 
N/A
- remove inline styles that make the example harder to read
- improve SCSS and remove unused rules
- fix adjustOffset() JSDoc to mark …
> docs(tabs): clean up the dynamic tabs demo

- README.md
- docs/app/partials/home.tmpl.html
```
[ ] Bugfix
```
Developers looking for the latest features from the MD spec may be confused when reading our docs.
Issue Number: 
Relates to #11415. Relates to #11420.
- clarify that this project aligns with the MD spec from 2014-2017
- clearly reference that the Angular Material project is that place
to find an implementation of the new MD spec
- fix extra space in version string
- add Gitter and NPM badges to readme
``` …
```
> docs: clarify that this project aligns with the MD spec from 2014-2017

- src/core/util/util.js
```
[x] Bugfix
```
The `-ms-overflow-y: scroll` style is applied to the `html` element when a `md-select` is open. This causes an extra scrollbar.
Issue Number: 
Fixes #11227
Don't apply `-ms-overflow-y: scroll` to the `html` element. No extra scrollbar is created.
```
[ ] Yes
[x] No
```
Tested on Windows against IE11, Firefox, and Chrome.
Before:
After:
> fix(util,select): extra scrollbar when select dropdown is open

- package-lock.json
- package.json
- src/components/navBar/navBar.js
- src/components/navBar/navBar.spec.js
```
[x] Bugfix
```
1. You can't move focus out of `md-nav-bar` with shift+tab on keyboard.
1. You can't use the home or end keys to change tabs as defined in the [WAI-ARIA Authoring Practices](https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-2/tabs.html)
1. You can't wrap around to the first/last tab when hitting the end as as defined in the [WAI-ARIA Authoring …
> fix(nav-bar): update keyboard navigation to WAI-ARIA guidelines

- docs/content/CSS/typography.md
```
[ ] Bugfix
```
- Query string in link to the Roboto font doesn't work anymore
Issue Number: 
N/A
- fix link to Roboto font
- minor tweaks to intro styling and grammar
```
[ ] Yes
[x] No
```
> docs(typography): fix link to Roboto font

- src/components/datepicker/js/datepickerDirective.js
- src/components/datepicker/js/datepickerDirective.spec.js
```
[x] Bugfix
[ ] Feature
```
this fixes a regression introduced in v1.1.0 against IE
however the test is able to reproduce the issue on Chrome
Issue Number: 
Fixes #9994. Closes #10520. Relates to #10015.
The test passes and datepicker validation and ngMessages work properly on IE.
```
[ ] Yes
[x] No
```
thank you to Topher Fangio and Richard Hughes for the original solution
> fix(datepicker): validation error when adding text after date

- CHANGELOG.md
```
[ ] Bugfix
```
The changelog for 1.1.12 doesn't list the contributors.
Issue Number: 
N/A
The changelog for 1.1.12 does list the contributors.
```
[ ] Yes
[x] No
```
> docs(changelog): add contributors section for 1.1.12

- .eslintrc.json
- docs/app/js/codepen.js
- docs/config/processors/componentsData.js
- scripts/find-max-version.js
- src/components/autocomplete/autocomplete.spec.js
- src/components/chips/chips.spec.js
- src/components/chips/js/chipRemoveDirective.js
- src/components/content/content.spec.js
- src/components/input/input-animations.spec.js
- src/components/sidenav/sidenav.js
- src/components/sidenav/sidenav.spec.js
- src/components/slider/slider.js
- src/components/slider/slider.spec.js
- src/components/sticky/sticky.js
- src/components/tabs/js/tabsDummyWrapperDirective.js
- src/components/virtualRepeat/demoDeferredLoading/script.js
- src/components/whiteframe/demoDirectiveInterpolation/script.js
- src/core/services/interimElement/interimElement.spec.js
- src/core/util/media.spec.js
- src/core/util/prefixer.spec.js
```
[ ] Bugfix
```
Our rules allow for unlimited trailing spaces.
Issue Number: 
N/A
We now enforce that there should not be trailing spaces and enable quick fixing.
This would generate an error: "var messageLength = 10;         "
This would pass linting: "var messageLength = 10;"
```
[ ] Yes
[x] No
```
> style(eslint): enable no-trailing-spaces rule

- .mailmap
```
[ ] Bugfix
```
Certainly tools like `git shortlog -se` and other Git interfaces other than GitHub are unable to track contributions for a single person who uses different case in their name or email address or who uses multiple name formats or email addresses.
Issue Number: 
Relates to #10926
Clean up a lot of our disconnected contributions via `.mailmap`
reference: …
> chore(git): update .mailmap file

- .eslintrc.json
- config/ngModuleData.js
- docs/app/js/app.js
- docs/config/processors/buildConfig.js
- gulp/tasks/build-all-modules.js
- gulp/tasks/ddescribe-iit.js
- release.js
- src/components/button/button.js
- src/components/gridList/demoDynamicTiles/script.js
- src/components/menu/menu.spec.js
- src/components/progressLinear/demoBasicUsage/script.js
- src/components/progressLinear/progress-linear.js
- src/components/select/select.spec.js
- src/components/toast/toast.js
- src/core/services/gesture/gesture.js
- src/core/services/interimElement/interimElement.spec.js
- src/core/services/layout/layout.js
- src/core/services/registry/componentRegistry.js
- src/core/util/iterator.js
- src/core/util/iterator.spec.js
- src/core/util/util.js
```
[ ] Bugfix
```
Our rules allow inconsistent array bracket spacing.
Issue Number: 
N/A
We enforce consistent array bracket spacing and enable quick fixing.
This will cause an error: `var x = [ true, false ]`
This will pass linting: `var x = [true, false]`
```
[ ] Yes
[x] No
```
> style(eslint): enable array-bracket-spacing rule

- .circleci/config.yml
- scripts/circleci/update-snapshot-and-docs.sh
```
[ ] Bugfix
```
```bash
./scripts/circleci/update-snapshot-and-docs.sh
./scripts/circleci/update-snapshot-and-docs.sh: line 26: ./scripts/circleci/utils.inc: No such file or directory
Exited with code 1
```
Also we actually don't need the separate `bower_material_snapshot` job.
Issue Number: 
Relates to #11592. Relates to #11608.
- Removed unneeded `bower_material_snapshot` job.
- Fix path issue with …
> chore(ci): fix CircleCI snapshot and doc publishing

- scripts/circleci/update-snapshot-and-docs.sh
```
[ ] Bugfix
```
```shell
./scripts/circleci/update-snapshot-and-docs.sh --sha=${CIRCLE_SHA1}
sed: can't read package.json: No such file or directory
./scripts/circleci/update-snapshot-and-docs.sh: line 22: ./scripts/bower-material-release.sh: No such file or directory
Exited with code 127
```
Issue Number: 
Relates to #11592. Relates to #11608.
Go up one more directory to get to root from `scripts/circleci/` before …
> chore(ci): adjust working directory before running scripts

- .circleci/config.yml
```
[ ] Bugfix
```
```shell
checkPermissions Missing write access to /usr/local/lib/node_modules
```
Issue Number: 
Relates to #11592. Relates to #11608.
`sudo` when installing `gulp`.
```
[ ] Yes
[x] No
```
> chore(ci): sudo install gulp globally

- scripts/snapshot-docs-site.sh
```
[ ] Bugfix
```
The `snapshot-docs-site.sh` script fails after the following log message with `exit 5` which stands for an "I/O Error":
```shell
-- Copying docs site to snapshot...
```
Issue Number: 
Relates to #11592.
- use commands that should work with GNU and BSD sed
- add log statements
```
[ ] Yes
[x] No
```
> chore(ci): use portable sed commands

- scripts/bower-material-release.sh
- scripts/snapshot-docs-site.sh
```
[ ] Bugfix
```
```shell
-- Configuring Git...
Exited with code 5
```
Which is a generic "I/O Error" on Linux.
Issue Number: 
Relates to #11592.
- update git credential syntax based on syntax described in https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage
- add more log statements
- add cleanup to bower-material-release.sh
```
[ ] Yes
[x] No
```
> chore(ci): update git credential syntax

- .circleci/config.yml
- scripts/bower-material-release.sh
- scripts/snapshot-docs-site.sh
```
[ ] Bugfix
```
`git ` returns exit code `5` to indicate that "you try to unset an option which does not exist (ret=5),". ([Reference](https://git-scm.com/docs/git-config#_description))
Issue Number: 
Relates to #11592.
Only unset the SSH override once for the whole job.
```
[ ] Yes
[x] No
```
> chore(ci): only unset the CircleCI SSH override once

- src/components/autocomplete/js/autocompleteController.js
This reverts commit a37f7ccecf225bcb3cf96774a7a7b97091cbab62.
Creating this PR to investigate failure in google3 possibly caused by the reverted change
> Revert "fix(autocomplete): show dropdown on top only when there is room"

- src/components/checkbox/checkbox.js
```
[ ] Bugfix
```
```shell
angular/material/src/components/checkbox/checkbox.js
175:9  error  Expected space(s) after "switch"  keyword-spacing
✖ 1 problem (1 error, 0 warnings)
```
Issue Number: 
Relates to #11584.
Lint passes.
```
[ ] Yes
[x] No
```
> style(lint): fix missing space in checkbox.js

- src/core/util/util.js
```
[ ] Bugfix
```
Missing Closure types, incorrect JSDoc variable names, etc.
Issue Number: 
N/A
Properly formatted JSDoc with correct variable names and Closure types.
```
[ ] Yes
[x] No
```
> docs(util): fix incorrect Closure types and JSDoc

- src/core/services/ripple/ripple.js
```
[ ] Bugfix
```
Docs for $mdInkRippleProvider and $mdInkRipple are combined which is confusing as the docs mention `$mdInkRipple.disableInkRipple()` which isn't valid. Only `$mdInkRippleProvider.disableInkRipple()` is valid and it can only be called in the `config` phase.
Issue Number: 
N/A
Separate docs for $mdInkRippleProvider and $mdInkRipple.
fix some Closure types
```
[ ] Yes
[x] No
```
> docs(ripple): break out docs for $mdInkRippleProvider from $mdInkRipple

- src/components/radioButton/demoMultiColumn/script.js
```
[ ] Bugfix
[X] Documentation content changes
```
Two minor misspellings in Spanish names:
* change «Maria» to «María»
* change «Marquéz» to «Márquez»
```
[ ] Yes
[X] No
```
> docs(radiobutton): correct two misspellings on demo

- .github/ISSUE_TEMPLATE.md
```
[ ] Bugfix
[x] Other... Please describe: Issue template changes
```
Issue submitters often submit Angular Material issues to the AngularJS Material repo.
Issue Number: 
Relates to https://github.com/angular/material/issues/11665.
We now make it even more obvious at the top of the issue template that this repo is only for AngularJS Material.
```
[ ] Yes
[x] No
```
Requested in https://github.com/angular/material/issues/11665#issuecomment-470504702.
> docs(issue-template): make it more clear that this repo is for AngularJS

- CHANGELOG.md
```
[ ] Bugfix
```
Issue Number: 
```
[ ] Yes
[x] No
```
> docs(changelog): minor fixes

- test/angular-material-spec.js
setting up jasmine matchers and mockElementFocus don't need to be
evaluated every time a test runs.
Fixes N/A
```
[ ] Bugfix
[x] Other... Please describe:
```
Currently when tests are run there is a beforeEach block that sets up jasmine matchers and a mockElementFocus every time a test is evaluated. This only needs to happen once.
Issue Number: N/A
Now setting up matchers and "mockElementFocus" happen once before all tests are run. This should reduce the …
> chore(tests): use beforeAll where possible

- README.md
- docs/app/partials/home.tmpl.html
- docs/content/migration.md
- src/components/autocomplete/demoCustomTemplate/script.js
- src/components/autocomplete/demoRepeatMode/script.js
```
[ ] Bugfix
```
Docs and demos point to the old `material2` repo.
Issue Number: 
N/A
Updates to point to the new `components` repo.
Mention the CDK.
```
[ ] Yes
[x] No
```
> docs: update for new angular/components repo name

- .github/ISSUE_TEMPLATE.md
```
[ ] Bugfix
```
The template points to the old `angular/material2` repo.
Issue Number: 
Related to #11721.
- change link to use new components repo name, mention CDK
- add another warning about AngularJS vs Angular
```
[ ] Yes
[x] No
```
> docs(issue): components repo rename

- .github/CONTRIBUTING.md
```
[ ] Bugfix
```
- Some important topic headers aren't in the TOC, which sometimes makes it seem like you opened the wrong markdown file.
- We link to the Angular CoC, but not the GitHub Terms.
Issue Number: 
N/A
- Key topics added to the TOC.
- We link to the Angular CoC and the GitHub Terms, including the conduct guideines.
```
[ ] Yes
[x] No
```
> docs(contributing): add more links to ToC and link to GitHub Terms

- release.js
```
[ ] Bugfix
```
PR https://github.com/angular/material/pull/11735 updated `prompt-sync` and broke the `./release` script.
Issue Number: 
N/A
This change updates the release script to use the latest APIs for `prompt-sync`.
```
[ ] Yes
[x] No
```
> build(release): fix breaking changes from prompt-sync update

- src/components/radioButton/radio-button.js
```
[ ] Bugfix
```
There is some empty JSDoc that could be helpful.
Issue Number: 
N/A
There is new JSDoc with typings that could be helpful.
Cleaned up some whitespace.
```
[ ] Yes
[x] No
```
Noticed while investigating and testing radio-button issues on iOS.
> refactor(radio-button): improve JSDoc

- src/components/select/select.spec.js
```
[ ] Bugfix
```
Lint fails in CI.
Issue Number: 
#11156 
Lint passes in CI.
```
[ ] Yes
[x] No
```
> chore: fix lint issue caused by PR #11156

- package-lock.json
- package.json
```
[ ] Bugfix
```
A number of JSDoc/Closure types (i.e. `JQLite`, `angular.element`) cannot be resolved by IDE tooling as the types aren't defined.
Issue Number: 
N/A
A number of JSDoc/Closure types (i.e. `JQLite`, `angular.element`) can be resolved by IDE tooling as the types are defined.
```
[ ] Yes
[x] No
```
> build: add @types/angular

- gulp/tasks/docs.js
```
[ ] Bugfix
```
- The GitHub API is called for development mode rebuilds and it can take 5-10s to respond and the results to be processed.
Issue Number: 
N/A
- don't hit the GitHub API for development mode rebuilds
```
[ ] Yes
[x] No
```
> build(docs): speed up rebuilds in development mode

- .circleci/config.yml
- package-lock.json
- package.json
```
[ ] Bugfix
```
- we have a missing peer dependency
` acorn-jsx@5.1.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.`
- there's a new jquery with some security fixes
Issue Number: 
Closes #11898
- update to jquery 3.5.1
- update to latest `minimist`, `node-sass`, `graceful-fs`
- add missing peer dependency from eslint: `acorn`
- remove deprecated `natives` …
> build: update to jquery 3.5.1

- LICENSE
- docs/app/js/codepen.js
- docs/app/partials/license.tmpl.html
- src/components/chips/demoContactChips/script.js
```
[ ] Bugfix
[x] Other... Please describe:
```
- Our contact chips demos don't work when opened in CodePen because we can't inject CryptoJS in the same way.
- Copyright years are out of date
Issue Number: 
N/A
- Add CryptoJS's MD5 module to all our CodePens
- Update Copyright years to 2020
- Update our CodePen's `momentjs` version
```
[ ] Yes
[x] No
```
> docs: fix contact chips CodePens and update Copyright years

- .circleci/config.yml
```
[ ] Bugfix
```
We're using an old circleci/node image `10.20.0-browsers`.
Issue Number: 
N/A
- update to latest circleci/node image `14.1.0-browsers`
```
[ ] Yes
[x] No
```
I was also using this PR/commit to verify that my commit signing on GitHub was fixed again. Somehow my commits stopped getting signed recently.
> build(ci): update to latest circleci/node image

- config/karma.conf.js
```
[ ] Bugfix
```
- Karma tests use normal Chrome and Firefox by default
Issue Number: 
- Karma tests use headless Chrome and Firefox by default
```
[ ] Yes
[x] No
```
> test: enable headless browsers by default

- src/components/slider/slider.js
- src/components/slider/slider.spec.js
```
[ x ] Bugfix
[ x ] Enhancement
```
Issue Number: https://github.com/angular/material/issues/11800
```
[ ] Yes
[ ] No
```
> fix(slider): vertical slider in a scrolled container sets value to zero on all clicks

- src/core/services/interimElement/interimElement.js
```
[ ] Bugfix
```
- incomplete comments and JSDoc for `$$interimElementProvider`
Issue Number: 
N/A
- improves comments and JSDoc
- this service is still hidden on our docs site though
```
[ ] Yes
[x] No
```
Mostly updated so that it's easier and less confusing for me to read these comments while working with this service in the components that use it.
> docs(interimElement): improve documentation

- src/components/toast/toast.js
- src/core/util/util.js
```
[x] Bugfix
```
- position of "" uses undocumented default positioning
- "top left"
- position of "left" or "right" uses undocumented default vertical positioning: "top"
Issue Number: 
Closes #11843
- improve position handling to better align with docs
- position of "" uses documented default positioning
- "bottom left"
- position of "left" or "right" uses documented default vertical positioning: "bottom" …
> fix(toast): improve position handling to better align with docs

- .mailmap
> chore: Fix privacy concerns

- src/components/bottomSheet/bottom-sheet.js
- src/components/dialog/dialog.js
- src/components/panel/demoBasicUsage/index.html
- src/components/panel/demoBasicUsage/script.js
- src/components/panel/demoPanelAnimations/script.js
- src/components/panel/demoPanelProvider/script.js
- src/components/panel/demoReuse/script.js
- src/components/panel/panel.js
- src/components/toast/toast.js
```
[x] Bugfix
```
- panel basic demo's menu was throwing an exception
Issue Number: 
N/A
- panel basic demo's menu exception fixed
- fix missing div in panel basic demo template
- clean up comments and API docs for panel, toast, dialog, and bottom sheet
```
[ ] Yes
[x] No
```
This is needed after the changes in PR https://github.com/angular/material/pull/11967.
> fix(panel): demos need to access locals in controller's $onInit

- CHANGELOG.md
```
[ ] Bugfix
```
- changelog isn't complete
Issue Number: 
- full 1.2.0 changelog is included
```
[ ] Yes
[x] No
```
> docs(changelog): update 1.2.0 changelog

- src/components/sticky/sticky.js
```
[ ] Bugfix
```
- The `$mdSticky` docs include some grammar issues, typos, type issues, and don't clearly document the functionality.
Issue Number: 
N/A
- improve Closure types and JSDoc
- link to AngularJS `$compiler` docs and more clearly call out how it is used
- clean up grammar, typos
```
[ ] Yes
[x] No
```
> docs($mdSticky): update and clarify the usage and behavior

- docs/app/partials/home.tmpl.html
```
[ ] Bugfix
```
- The versions of Safari are out of date.
- Some rows have duplicate information and could be collapsed.
Issue Number: 
N/A
- clarify that `last 2 versions` means `major` versions
- Combine rows with similar information.
- update for Safari/iOS 14 release
```
[ ] Yes
[x] No
```
> docs(home): simplify and clarify policy is for major versions

- src/core/services/aria/aria.spec.js
update test name to removal usage of blacklist
> test: update test name to removal usage of blacklist

- src/components/icon/js/iconService.js
```
[ ] Bugfix
```
- There is a reference to whitelist in an example comment.
- typos, formatting, syntax, and type issues exist in the docs and examples
Issue Number: 
N/A
- remove reference to whitelist
- fix typos and formatting
- fix syntax issues with examples
- fix invalid Closure types
```
[ ] Yes
[x] No
```
> docs(icon): documentation refinement and cleanup

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/docs.md
- .github/PULL_REQUEST_TEMPLATE.md
- SECURITY.md
```
[ ] Bugfix
```
We use the legacy GitHub issue template system.
Issue Number: 
N/A
- update to latest GitHub issue templates
- mark the 1.2.x branch as the supported branch
- refine the PR template
- add community help links to new `config.yml` file
- auto label new issues
```
[ ] Yes
[x] No
```
> dev-infra: update to latest GitHub issue templates

- src/components/tabs/tabs.scss
```
[x] Bugfix
```
- it styles nested `md-tabs` as well as itself
Issue Number: 
Fixes #10541
- `md-align-tabs` only styles the current component
```
[ ] Yes
[x] No
```
> fix(tabs): md-align-tabs should only affect the current component

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/docs.md
```
[ ] Bugfix
```
- GitHub doesn't support `mailto:` links here which we tried to use
- we don't use quotes around YAML-reserved characters like `:` in `type: bug` 
Fixes # N/A
- use a HTTPS link to the `SECURITY.md` file
- use quotes around YAML-reserved characters like `:`
```
[ ] Yes
[x] No
```
Relates to https://github.com/angular/material/pull/12032
> dev-infra: fix security link

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/docs.md
```
[ ] Bugfix
```
- There are 2 security links on the new issue page
- The description for Gitter and StackOverflow are the same
- The instruction text shows up in docs issue reports
- refine new template descriptions
- remove security link as GitHub seems to be creating their own now
```
[ ] Yes
[x] No
```
> dev-infra: refine new template descriptions

- .github/ISSUE_TEMPLATE/bug.md
```
[ ] Bugfix
```
- docs label used for bugs
- bug label used for bugs
```
[ ] Yes
[x] No
```
> dev-infra: use type: bug label for bugs

- .github/CONTRIBUTING.md
```
[ ] Bugfix
```
- the contributing guide is out of date with the changes to GitHub to support multiple issue templates
- it also links directly to new issue creation rather than the issue type chooser
- the commit scope examples are not correct
- some passive voice and grammar issues exist
- update content and refine grammar
- use new issue type chooser for creating new issues
- add build and ci commit types
- fix commit scope …
> docs(contributing): update content and refine grammar

- README.md
- SECURITY.md
- docs/app/partials/home.tmpl.html
```
[ ] Bugfix
```
There is no information available about the AngularJS Material Long Term Support (LTS) policy.
Issue Number: 
N/A
- add details about long term support to README.md and home page
- update security policy
```
[ ] Yes
[x] No
```
> docs: add details about long term support

- src/components/checkbox/checkbox.js
- src/components/checkbox/checkbox.spec.js
```
[x] Bugfix
```
- After deselecting all checkboxes the `aria-checked` attribute is "mixed".
Fixes #12046
- After deselecting all checkboxes the `aria-checked` attribute is "false".
- Other variations are handled as well and tests are added
```
[ ] Yes
[x] No
```
> fix(checkbox): aria-checked state is not computed correctly in all cases

- .circleci/config.yml
```
[ ] Bugfix
```
- CI is trying to rebase when running versus commits on master
- CI checks ensures that its in a PR branch before trying to rebase
```
[ ] Yes
[x] No
```
I also opened https://github.com/CircleCI-Public/build-tools-orb/issues/25 to get this command better documented.
> ci: use CircleCI build-tools' merge-with-parent command

- package-lock.json
```
[ ] Bugfix
```
- the `ini` package is triggering dependabot and npm audit warnings
Closes #12055
- audits results are improved
```
[ ] Yes
[x] No
```
> build: fix audit warnings related to ini

- package-lock.json
- package.json
```
[ ] Bugfix
```
- details can be found in https://github.com/angular/material/pull/12073
Closes https://github.com/angular/material/pull/12073
- updated to version of socket.io that does not have the vulnerability
```
[ ] Yes
[x] No
```
> build(deps): bump socket.io from 2.3.0 to 2.4.1

- docs/app/partials/home.tmpl.html
- src/components/tooltip/tooltip.spec.js
```
[ ] Bugfix
```
There is an out of date description of current development efforts.
Remove the out of date info.
```
[ ] Yes
[x] No
```
This came out of a discussion that I had with Minko.
> docs(home): remove details about current dev efforts

- README.md
```
[ ] Bugfix
```
We mention AngularJS and Angular without qualifying them with the v1.x and v2+ hints and we link to the Angular Components GitHub instead of the website.
- link to https://material.angular.io/ website instead of github
- add v1.x and v2+ for clarity
- these changes are driven by feedback from @mgechev
```
[ ] Yes
[x] No
```
> docs(readme): link to mat-aio website instead of github

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/docs.md
- .github/PULL_REQUEST_TEMPLATE.md
```
[ ] Bugfix
```
While we have info on the LTS on our home page and README, we don't have any notes about it in our issue or PR templates or in our `CONTRIBUTING.md`.
Mention the LTS and point to the details on the home page from all of these places.
```
[ ] Yes
[x] No
```
These template updates are roughly based on what the AngularJS repo uses.
> chore: update GitHub templates for LTS

- .circleci/config.yml
```
[ ] Bugfix
```
There are some errors in the build-tools rebase command as seen in https://github.com/angular/material/pull/12080.
This new build-tools orb may resolve those git errors.
```
[ ] Yes
[x] No
```
> chore: update CircleCI NodeJS image and build-tools orb

- package-lock.json
- package.json
```
[ ] Bugfix
```
- from: found 31 vulnerabilities (7 low, 8 moderate, 16 high)
Closes #12097.
- to: found 18 vulnerabilities (5 low, 1 moderate, 12 high)
```
[ ] Yes
[x] No
```
> build: update hosted-git-info to fix security advisories

- package-lock.json
- package.json
```
[ ] Bugfix
```
- before: found 64 vulnerabilities (1 low, 43 moderate, 17 high, 3 critical)
Closes #12129. Closes #12121.
- after: found 43 vulnerabilities (1 low, 24 moderate, 15 high, 3 critical)
```
[ ] Yes
[x] No
```
> chore(npm): update dependencies and fix audit issues

- docs/app/partials/home.tmpl.html
```
[ ] Bugfix
```
```
[ ] Yes
[x] No
```
> docs(eol): Add EOL options text and link to LTS section of landing page

- docs/app/css/style.css
- docs/config/template/index.template.html
```
[ ] Bugfix
```
```
[ ] Yes
[x] No
```
> docs(eol): add EOL options banner to header of every page
